MConf: ng3Matrix< T > Class Template Reference
ng3Matrix< T > Class Template Reference
A 3-dimensional matrix type
This class represents a 3-dimensional matrix type that uses implicit and transparent data sharing. It is much like ng2Matrix<T>, except that it has a third dimension.
#include <ngarray.h>
Public Member Functions
ng3Matrix ()
ng3Matrix (int min1, int max1, int min2, int max2, int min3, int max3, const T &val=T())
ng3Matrix (size_t s1, size_t s2, size_t s3, const T &val=T())
void fill (const T &val)
void init (int min1, int max1, int min2, int max2, int min3, int max3, const T &val=T())
void init (size_t s1, size_t s2, size_t s3, const T &val=T())
Detailed Description
template<class T>
class MConf::pBase::ng3Matrix< T >
A 3-dimensional matrix type
This class represents a 3-dimensional matrix type that uses implicit and transparent data sharing. It is much like ng2Matrix<T>, except that it has a third dimension.
It is possible for the matrix to be empty (to contain not a single element) In this case, you must not use the access operators - they will fail and cause a segmentation fault. Rather, you may check whether the matrix is empty by calling empty(). If you want the matrix to contain at least a single element, use a proper constructor or the init() function and pass a value of 0 to each index.
Definition at line 497 of file ngarray.h.
Constructor & Destructor Documentation
ng3Matrix ()
Definition at line 501 of file ngarray.h.
ng3Matrix (int min1, int max1, int min2, int max2, int min3, int max3, const T & val = T())
Definition at line 502 of file ngarray.h.
References ng3Matrix< T >::init().
ng3Matrix (size_t s1, size_t s2, size_t s3, const T & val = T())
Definition at line 506 of file ngarray.h.
References ng3Matrix< T >::init().
Member Function Documentation
void fill (const T & val)
Definition at line 511 of file ngarray.h.
References ngArray< ng2Matrix< T > >::detach(), and ngArray< ng2Matrix< T > >::p.
void init (int min1, int max1, int min2, int max2, int min3, int max3, const T & val = T())
Definition at line 522 of file ngarray.h.
References ngArray< ng2Matrix< T > >::p.
Referenced by ng3Matrix< T >::init(), and ng3Matrix< T >::ng3Matrix().
void init (size_t s1, size_t s2, size_t s3, const T & val = T())
Definition at line 533 of file ngarray.h.
References ng3Matrix< T >::init().
The documentation for this class was generated from the following file:
ngarray.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik