MConf: StopWatch Class Reference
StopWatch Class Reference
StopWatch provides functions for timings 2006.12.28 turkin 2007.09.12.
#include <mathf.h>
Public Member Functions
StopWatch ()
Constructor.
void setPrint (bool flag)
Resets the stopwatch.
void reset ()
Resets the stopwatch.
void start ()
Start the stopwatch.
void restart ()
Restart the stopwatch.
void stop ()
Stop the stopwatch.
void split ()
Split the time.
void unsplit ()
Remove a split.
void suspend ()
Suspend the stopwatch for later resumption.
void resume ()
Resume the stopwatch after a suspend.
double getTime ()
Get the time (in sec) on the stopwatch.
void printTime (const char *comment, bool reStart=false)
double getSplitTime ()
Get the split time (in sec) on the stopwatch.
Detailed Description
StopWatch provides functions for timings 2006.12.28 turkin 2007.09.12.
Definition at line 217 of file mathf.h.
Constructor & Destructor Documentation
StopWatch ()
Constructor.
Definition at line 227 of file mathf.h.
References StopWatch::reset().
Member Function Documentation
void setPrint (bool flag)
Resets the stopwatch.
Definition at line 232 of file mathf.h.
void reset ()
Resets the stopwatch.
Definition at line 236 of file mathf.h.
Referenced by StopWatch::start(), and StopWatch::StopWatch().
void start ()
Start the stopwatch.
Definition at line 241 of file mathf.h.
References StopWatch::reset().
Referenced by StopWatch::restart().
void restart ()
Restart the stopwatch.
Definition at line 248 of file mathf.h.
References StopWatch::start(), and StopWatch::stop().
Referenced by StopWatch::printTime().
void stop ()
Stop the stopwatch.
Definition at line 253 of file mathf.h.
Referenced by StopWatch::restart().
void split ()
Split the time.
Definition at line 261 of file mathf.h.
void unsplit ()
Remove a split.
Definition at line 270 of file mathf.h.
void suspend ()
Suspend the stopwatch for later resumption.
Definition at line 276 of file mathf.h.
void resume ()
Resume the stopwatch after a suspend.
Definition at line 282 of file mathf.h.
double getTime ()
Get the time (in sec) on the stopwatch.
Definition at line 288 of file mathf.h.
Referenced by StopWatch::printTime().
void printTime (const char * comment, bool reStart = false)
Definition at line 293 of file mathf.h.
References StopWatch::getTime(), and StopWatch::restart().
double getSplitTime ()
Get the split time (in sec) on the stopwatch.
Definition at line 299 of file mathf.h.
The documentation for this class was generated from the following file:
mathf.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik