MConf: CProfile Class Reference
CProfile Class Reference
This class provides the plasma profile which can be set by set of points or parameterized by CPfunction().
#include <CPfunction.h>
Public Member Functions
CProfile ()
CProfile (double v0, double *param)
Constructor sets parameters for analitic representation of the profile function.
CProfile (double v0, double g, double p, double q, double h=0, double w=0, double c=0)
Constructor sets parameters for analitic representation of the profile function.
virtual ~CProfile ()
void set (double v0, double *param, double c=0)
The method sets parameters for analitic representation of the profile function.
void setXmax (double xmax)
The method sets xmax for analitic representation of the profile function.
void set (const double *x, const double *p, int n)
The method sets points of the profile function from arrays.
void set (const double *r, const double *p, double rmax, int n)
The method sets points of the profile function from arrays.
void clear ()
The method clears the profile, it becomes empty.
bool empty () const
The method returns true if profile was not set.
double operator() (const double x) const
The operator returns function value at point x.
double mmin ()
The method returns minimal value of function.
double mmax ()
The method returns maximal value of function.
double xmax ()
void scale (double factor)
The method scales the function.
Detailed Description
This class provides the plasma profile which can be set by set of points or parameterized by CPfunction().
F(x) =n0[g-h+(1-g+h)(1-xp)q + h(1-e-x2/w2)], where 0<=x<=1,
properties: g=F(1)/F(0), F(0) = 1, F(x)>0,
usage:
  CProfile ne;
  // n0 is the value in the center
  // parm is the array[5] with coefficients: g,p,q,h,w.
  ne.set(n0,parm);
  double n = ne(x);
Examples:
cpp2for.cpp, and raytrace2.cpp.
Definition at line 65 of file CPfunction.h.
Constructor & Destructor Documentation
CProfile ()
Definition at line 77 of file CPfunction.h.
CProfile (double v0, double * param)
Constructor sets parameters for analitic representation of the profile function.
Parameters:
v0 is the value in the center
param is the array[5] of coefficients: g,p,q,h,w. See detailed description of CProfile::set()
Definition at line 83 of file CPfunction.h.
CProfile (double v0, double g, double p, double q, double h = 0, double w = 0, double c = 0)
Constructor sets parameters for analitic representation of the profile function.
Parameters:
v0 is the value in the center
g,p,q,h,w are the coefficients. See detailed description of CProfile::set()
Definition at line 89 of file CPfunction.h.
References CPfunction::setHoleCenter().
virtual ~CProfile () [virtual]
Definition at line 99 of file CPfunction.h.
Member Function Documentation
void set (double v0, double * param, double c = 0)
The method sets parameters for analitic representation of the profile function.
F(x) = c[g-h+(1-g+h)(1-xp)q + h(1-e-x2/w2)], where 0<=x<=1,
Parameters:
v0 is the value in the center
param is the array[5] of coefficients: g,p,q,h,w.
c is the center of the hole.
Definition at line 108 of file CPfunction.h.
References CProfile::clear(), and CPfunction::setHoleCenter().
void setXmax (double xmax)
The method sets xmax for analitic representation of the profile function.
Definition at line 118 of file CPfunction.h.
void set (const double * x, const double * p, int n)
The method sets points of the profile function from arrays.
For evaluating the function in intermediate points linear interpolation is used, see interpolate()
Parameters:
x is the abscissa points, array of size n, 0<=x<=1 (dimentionless flux label)
p is the ordinate set, array of size n.
n is the size of arrays.
Definition at line 128 of file CPfunction.h.
void set (const double * r, const double * p, double rmax, int n)
The method sets points of the profile function from arrays.
For evaluating the function in intermediate points linear interpolation is used, see interpolate()
Parameters:
r is the abscissa points, array of size n, 0<=r<=rmax
p is the ordinate set, array of size n.
rmax is the max value of abscissa, can be larger than last r, internally r is normalized by rmax
n is the size of arrays.
Definition at line 139 of file CPfunction.h.
References ngArray< T >::init().
void clear ()
The method clears the profile, it becomes empty.
Definition at line 155 of file CPfunction.h.
References ngArray< T >::clear(), and CPfunction::setHoleCenter().
Referenced by CProfile::set().
bool empty () const
The method returns true if profile was not set.
Definition at line 163 of file CPfunction.h.
References ngArray< T >::empty().
Referenced by CProfile::mmax(), CProfile::mmin(), and CProfile::scale().
double operator() (const double x) const
The operator returns function value at point x.
Parameters:
x is the abscissa see also usage of CProfile
Definition at line 169 of file CPfunction.h.
double mmin ()
The method returns minimal value of function.
Definition at line 173 of file CPfunction.h.
References CProfile::empty().
double mmax ()
The method returns maximal value of function.
Definition at line 177 of file CPfunction.h.
References CProfile::empty().
double xmax ()
Definition at line 180 of file CPfunction.h.
void scale (double factor)
The method scales the function.
Parameters:
factor is the scale-factor
Definition at line 185 of file CPfunction.h.
References CProfile::empty(), and ngArray< T >::size().
The documentation for this class was generated from the following file:
CPfunction.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik