MConf: CRayTrace Class Reference
CRayTrace Class Reference
Find intersections of straight ray with the flux surfaces, this class is obsolete.
#include <CRayTrace.h>
Public Member Functions
CRayTrace ()
The constructor creates an empty instance of CRayTrace.
virtual ~CRayTrace ()
The destructor is a virtual method that frees all memory used.
void clearTrace ()
This method frees trace arrays.
virtual void clear ()
This method frees all internal arrays (including base class) and makes this object empty.
int traceLCMS (const Vector3d &r1, const Vector3d &r2, Vector3d &entrypoint, Vector3d &exitpoint, double dpol=1., double dtor=1.)
The method traces the Last Closed Magnetic Surface (LCMS).
void traceLast (const Vector3d &r0, const Vector3d &rd, double dtheta=0., double dphi=0.)
The method traces the Last Closed Magnetic Surface (LCMS); obsolete method.
void traceAll (const Vector3d &r0, const Vector3d &rd, double dtheta=0., double dphi=0., int nSurf=50)
The method traces magnetic surfaces; obsolete method.
int getTraceSize () const
The method returns numbers of intersections of the ray with the magnetic surface or surfaces.
const Vector3d * getTraceRxyz () const
The method returns pointer to the array of intersections.
const double * getTraceLen () const
The method returns pointer to the array of lengths.
const double * getTracereff () const
The method returns pointer to the array of effective radii.
const double * getTraceVolume () const
The method returns pointer to the array of volumes.
const int * getTraceSurfNum () const
The method returns pointer to the array of surface numbers.
Protected Member Functions
void freeTrace ()
Free all memory used by CRayTrace.
Protected Attributes
Vector3d rayR0
origin of ray=rayR0+rayRd*len
Vector3d rayRd
direction of ray=rayR0+rayRd*len
CArray2d< Vector3d > svertex
2d-array to hold vertixes of the surface
CArray1d< Vector3d > Rxyz
array of intersection points of the ray with the surfaces
CArray1d< double > len
array of distances from Ray Origin to intersection points
CArray1d< double > reffc
radius reff, which corresponds intersection points
CArray1d< double > vol
volume inside a surface
CArray1d< int > snumber
array of surface numbers
int maxTrace
max number of allocated elements in above arrays
int sizeTrace
number of actual intersections
int mNsurf
number of surfaces to trace
Detailed Description
Find intersections of straight ray with the flux surfaces, this class is obsolete.
CRayTrace is derived from CStconfig and is used for straight line tracing through flux surfaces. Usually you need only one method from this class,namely CRayTrace::traceLCMS(), to find the first intersection with LCMS. Then you can use CStconfig::xyz2mag() to get magnetic coordinates along the ray, see raytrace2::cpp.
Note:
This class is obsolete;
use the method CStconfig::getRayEntryPoint() and CStconfig::xyz2mag();
or C3dMesh::M3DgetRayEntryPoint() and C3dMesh::M3Dxyz2s()
See also:
class CStconfig, class C3dMesh, and raytrace2::cpp
Examples:
raytrace1.cpp.
Definition at line 28 of file CRayTrace.h.
Constructor & Destructor Documentation
CRayTrace ()
The constructor creates an empty instance of CRayTrace.
virtual ~CRayTrace () [virtual]
The destructor is a virtual method that frees all memory used.
Definition at line 48 of file CRayTrace.h.
References CRayTrace::freeTrace().
Member Function Documentation
void freeTrace () [protected]
Free all memory used by CRayTrace.
Referenced by CRayTrace::~CRayTrace().
void clearTrace ()
This method frees trace arrays.
virtual void clear () [virtual]
This method frees all internal arrays (including base class) and makes this object empty.
Reimplemented from CStconfig.
Reimplemented in C3dMesh.
int traceLCMS (const Vector3d & r1, const Vector3d & r2, Vector3d & entrypoint, Vector3d & exitpoint, double dpol = 1., double dtor = 1.)
The method traces the Last Closed Magnetic Surface (LCMS).
The method finds intersections of the ray with the LCMS, where the ray is R(t)=r1+(r2-r1)/|r2-r1|*t, and t>=0.
Parameters:
r1 is the cartesian coordinates of the first point of the ray, must be outside with respect to the LCMS.
r2 is the cartesian coordinates of the second point of the ray
entrypoint this vector at return contains the coordinates of the entry point of the ray into plasma
exitpoint this vector at return contains the coordinates of the exit point
dpol is the angle step in degree along poloidal direction
dtor is the angle step in degree along toroidal direction
Returns:
-2 -- the origin r1 of the ray lies inside LCMS;
-1 -- the ray does not enters into plasma;
0 -- segment r1--r2 is outside plasma;
1 -- only entry point lies on the segment r1--r2, i.e. r2 is inside plasma;
2 -- entry and exit points lie on the segment r1--r2, i.e. r1 and r2 are outside plasma;
if returned value >= 0 then entry and exit points of the ray are saved in entrypoint and exitpoint
Examples:
raytrace1.cpp.
void traceLast (const Vector3d & r0, const Vector3d & rd, double dtheta = 0., double dphi = 0.)
The method traces the Last Closed Magnetic Surface (LCMS); obsolete method.
The method finds intersections of the ray with the LCMS. The ray is R(t)=r0+rd*t/|rd| with t>=0.
Parameters:
r0 is the origin of the ray, must be outside with respect to the LCMS.
rd is the direction of the ray
dtheta is the poloidal step for the triangulization of the LCMS
dphi is the toroidal step for the triangulization of the flux suface
Note:
Obsolete function; use traceLCMS() in stead of this method.
Referenced by MCTRACELCMS().
void traceAll (const Vector3d & r0, const Vector3d & rd, double dtheta = 0., double dphi = 0., int nSurf = 50)
The method traces magnetic surfaces; obsolete method.
The method finds intersections of the ray with the flux surfaces. The ray is R(t)=r0+rd*t/|rd| with t>=0.
Parameters:
r0 is the origin of the ray, must be outside with respect to the LCMS.
rd is the direction of the ray
dtheta is the poloidal step for the triangulization of the flux sufaces
dphi is the toroidal step for the triangulization of the flux sufaces
nSurf is the number of sufaces to trace, the surfaces are distributed equidistantly on reff.
Use getTraceSize(),getTraceRxyz(),getTraceLen() methods to get trace information
Note:
Obsolete function; it is better(and faster) to use traceLCMS() and then xyz2mag(), see raytrace1::cpp
int getTraceSize () const
The method returns numbers of intersections of the ray with the magnetic surface or surfaces.
This method is used after traceLast() or traceAll() to get numbers of intersections.
Returns:
numbers of intersections or 0 if no intersections were found.
Definition at line 103 of file CRayTrace.h.
References CRayTrace::sizeTrace.
Referenced by MCTRACELCMS().
const Vector3d* getTraceRxyz () const
The method returns pointer to the array of intersections.
The array contains cartesian coordinates of intersections of the ray with the magnetic surface/s. This method is used after traceAll() or traceLast(). The array size is getTraceSize()
Definition at line 108 of file CRayTrace.h.
References ngArray< T >::constArray(), and CRayTrace::Rxyz.
Referenced by MCTRACELCMS().
const double* getTraceLen () const
The method returns pointer to the array of lengths.
The array contains lengths between the first and successive intersections of the ray with the magnetic surface/s. This method is used after traceAll() or traceLast(). The array size is getTraceSize()
Definition at line 114 of file CRayTrace.h.
References ngArray< T >::constArray(), and CRayTrace::len.
const double* getTracereff () const
The method returns pointer to the array of effective radii.
The array contains effective radii of surfaces, which the ray intersects. This method is used after traceAll() or traceLast(). The array size is getTraceSize()
Definition at line 119 of file CRayTrace.h.
References ngArray< T >::constArray(), and CRayTrace::reffc.
const double* getTraceVolume () const
The method returns pointer to the array of volumes.
The array contains volumes of surfaces, which the ray intersects. This method is used after traceAll() or traceLast(). The array size is getTraceSize()
Definition at line 124 of file CRayTrace.h.
References ngArray< T >::constArray(), and CRayTrace::vol.
const int* getTraceSurfNum () const
The method returns pointer to the array of surface numbers.
The array contains surface numbers, which the ray intersects. This method is used after traceAll() or traceLast(). The array size is getTraceSize()
Definition at line 129 of file CRayTrace.h.
References ngArray< T >::constArray(), and CRayTrace::snumber.
Member Data Documentation
Vector3d rayR0 [protected]
origin of ray=rayR0+rayRd*len
Definition at line 30 of file CRayTrace.h.
Vector3d rayRd [protected]
direction of ray=rayR0+rayRd*len
Definition at line 31 of file CRayTrace.h.
CArray2d<Vector3d> svertex [protected]
2d-array to hold vertixes of the surface
Definition at line 32 of file CRayTrace.h.
CArray1d<Vector3d> Rxyz [protected]
array of intersection points of the ray with the surfaces
Definition at line 33 of file CRayTrace.h.
Referenced by CRayTrace::getTraceRxyz().
CArray1d<double> len [protected]
array of distances from Ray Origin to intersection points
Definition at line 34 of file CRayTrace.h.
Referenced by CRayTrace::getTraceLen().
CArray1d<double> reffc [protected]
radius reff, which corresponds intersection points
Definition at line 35 of file CRayTrace.h.
Referenced by CRayTrace::getTracereff().
CArray1d<double> vol [protected]
volume inside a surface
Definition at line 36 of file CRayTrace.h.
Referenced by CRayTrace::getTraceVolume().
CArray1d<int> snumber [protected]
array of surface numbers
Definition at line 37 of file CRayTrace.h.
Referenced by CRayTrace::getTraceSurfNum().
int maxTrace [protected]
max number of allocated elements in above arrays
Definition at line 38 of file CRayTrace.h.
int sizeTrace [protected]
number of actual intersections
Definition at line 39 of file CRayTrace.h.
Referenced by CRayTrace::getTraceSize().
int mNsurf [protected]
number of surfaces to trace
Definition at line 40 of file CRayTrace.h.
The documentation for this class was generated from the following file:
CRayTrace.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik