MConf: CArray2d< TV > Class Template Reference
CArray2d< TV > Class Template Reference
This class provides 2d-array.
#include <CArray2d.h>
Public Member Functions
CArray2d ()
Default constructor.
CArray2d (int dim1, int dim2)
Constructor, creates array with dimentions dim1 and dim2.
CArray2d (int low1, int upper1, int low2, int upper2)
Constructor.
bool isOK () const
Copy constructor, creates array with the same content and shape as z.
int size1 () const
get the the first dimention of the array.
int size2 () const
get the the second dimention of the array.
int lowbound1 () const
get the first value of the first array index.
int lowbound2 () const
get the first value of the second array index.
int upperbound1 () const
get the last value of the first array index.
int upperbound2 () const
get the last value of the second array index
bool isIndexOK (int i, int j) const
check whether indexes within bounds
TV & operator() (int i, int j)
The operator returns the value of array element.
const TV & operator() (int i, int j) const
const TV * operator[] (int i) const
Returns a constant reference to the element at i.
CArray2d & operator+= (CArray2d const &v)
Addition assignment Both arrays must have the same shape.
CArray2d & operator-= (CArray2d const &v)
Subtraction assignment Both arrays must have the same shape.
CArray2d & operator*= (TV d)
Multiplication assignment.
CArray2d & operator/= (TV d)
Division assignment.
CArray2d & addweighted (CArray2d const &v, TV w)
Product of CArray2d and double.
TV & w (int i, int j)
int index (int i, int j) const
TV * ptr ()
const TV * cptr () const
CArray2d & operator= (const TV &x)
The operator assigns x to all elements.
CArray2d & operator= (const CArray2d &z)
Assignment operator.
bool init (int d1, int d2)
The method changes the dimentions of the array.
bool init (int low1, int upper1, int low2, int upper2)
The method changes the shape of the array.
bool resize (int low_1, int upper1, int low_2, int upper2)
The method changes the shape of the array.
bool resize (int d1, int d2)
The method changes the dimentions of the array.
void clear ()
The method frees memory This function will clear the array.
void print () const
The method prints all elements of the array.
template<class T >
size_t write (T x, FILE *fp) const
Write into binary file.
template<class T >
size_t read (T x, FILE *fp)
Read from binary file the array that was written by write() method.
template<class T >
size_t write0 (T x, FILE *fp) const
The same as write() but the shape of the array are not saved, only dimensions are saved.
template<class T >
size_t read0 (T x, FILE *fp)
The method reads the array that was written by write0() method.
Detailed Description
template<class TV>
class MConf::CArray2d< TV >
This class provides 2d-array.
For internal use only.
Usage:
 #include "CArray2d.h"
 int main() {
   MConf::CArray2d<MConf::Vector3d> vertex;
   vertex.init(100,200);
   vertex.init(-10,20, -1,200); // resize to another shape
   vertex(-10,200) = MConf::Vector3d(1,2,3);
   MConf::Vector3d r = vertex(20,-1);
   MConf::Vector3d r = vertex[20][-1];  // important! operator[] provides read only access
   FILE *fp=fopen("test","wb");
   vertex.write(float(1),fp);
 }
Definition at line 28 of file CArray2d.h.
Constructor & Destructor Documentation
CArray2d ()
Default constructor.
Definition at line 35 of file CArray2d.h.
CArray2d (int dim1, int dim2)
Constructor, creates array with dimentions dim1 and dim2.
Use isOK() method to check whether the method succeeds.
Definition at line 38 of file CArray2d.h.
CArray2d (int low1, int upper1, int low2, int upper2)
Constructor.
Parameters:
low1,upper1 are the bounds for the 1st index,
low2,upper2 are the bounds for the 2nd index, Use isOK() method to check whether the method succeeds.
Definition at line 45 of file CArray2d.h.
Member Function Documentation
bool isOK () const
Copy constructor, creates array with the same content and shape as z.
Use isOK() method to check whether the method succeeds. The method returns true if no error occurs for the last operation with array.
Definition at line 52 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::print(), CArray2d< Vector3d >::resize(), CArray2d< Vector3d >::write(), and CArray2d< Vector3d >::write0().
int size1 () const
get the the first dimention of the array.
Definition at line 54 of file CArray2d.h.
int size2 () const
get the the second dimention of the array.
Definition at line 56 of file CArray2d.h.
int lowbound1 () const
get the first value of the first array index.
Definition at line 58 of file CArray2d.h.
int lowbound2 () const
get the first value of the second array index.
Definition at line 60 of file CArray2d.h.
int upperbound1 () const
get the last value of the first array index.
Definition at line 62 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::isIndexOK().
int upperbound2 () const
get the last value of the second array index
Definition at line 64 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::isIndexOK().
bool isIndexOK (int i, int j) const
check whether indexes within bounds
Definition at line 66 of file CArray2d.h.
TV& operator() (int i, int j)
The operator returns the value of array element.
Parameters:
i,j -- element indexes
Returns:
reference to the correspondent element.
Definition at line 73 of file CArray2d.h.
const TV& operator() (int i, int j) const
Definition at line 74 of file CArray2d.h.
const TV* operator[] (int i) const
Returns a constant reference to the element at i.
The function returns a constant reference to the element at i. i should be limited to min ... max, otherwise it is made to fit into that range.
Note:
You should check that the array is not empty. Accessing elements from an empty ngArray will cause a segmentation fault.
This operator usually returns quite fast, no copying will be performed.
Reimplemented from ngArray< TV >.
Definition at line 75 of file CArray2d.h.
CArray2d& operator+= (CArray2d< TV > const & v)
Addition assignment Both arrays must have the same shape.
Definition at line 79 of file CArray2d.h.
CArray2d& operator-= (CArray2d< TV > const & v)
Subtraction assignment Both arrays must have the same shape.
Definition at line 90 of file CArray2d.h.
CArray2d& operator*= (TV d)
Multiplication assignment.
Definition at line 100 of file CArray2d.h.
CArray2d& operator/= (TV d)
Division assignment.
Definition at line 109 of file CArray2d.h.
CArray2d& addweighted (CArray2d< TV > const & v, TV w)
Product of CArray2d and double.
Definition at line 118 of file CArray2d.h.
TV& w (int i, int j)
Definition at line 129 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::print(), CArray2d< Vector3d >::read(), CArray2d< Vector3d >::read0(), CArray2d< Vector3d >::write(), and CArray2d< Vector3d >::write0().
int index (int i, int j) const
Definition at line 131 of file CArray2d.h.
TV* ptr ()
Definition at line 133 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::operator=(), and CArray2d< Vector3d >::resize().
const TV* cptr () const
Definition at line 134 of file CArray2d.h.
CArray2d& operator= (const TV & x)
The operator assigns x to all elements.
Definition at line 136 of file CArray2d.h.
CArray2d& operator= (const CArray2d< TV > & z)
Assignment operator.
Definition at line 142 of file CArray2d.h.
bool init (int d1, int d2)
The method changes the dimentions of the array.
Previous content of the array is not preserved. The method is the same as resize(int d1,int d2).
Parameters:
d1,d2 are the new dimentions.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 159 of file CArray2d.h.
bool init (int low1, int upper1, int low2, int upper2)
The method changes the shape of the array.
Previous content of the array is not preserved.
Parameters:
low1,upper1 are the bounds for the 1st index,
low2,upper2 are the bounds for the 2nd index, indexes can take the values of bounds.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds. The method is the same as resize(int low1,int upper1,int low2,int upper2).
Definition at line 171 of file CArray2d.h.
bool resize (int low_1, int upper1, int low_2, int upper2)
The method changes the shape of the array.
Previous content of the array is not preserved.
Parameters:
low_1,upper1 are the bounds for the 1st index,
low_2,upper2 are the bounds for the 2nd index, indexes can take the values of bounds.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds.
Definition at line 181 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::CArray2d(), CArray2d< Vector3d >::init(), CArray2d< Vector3d >::read(), CArray2d< Vector3d >::read0(), and CArray2d< Vector3d >::resize().
bool resize (int d1, int d2)
The method changes the dimentions of the array.
Previous content of the array is not preserved.
Parameters:
d1,d2 are the new dimentions.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 194 of file CArray2d.h.
void clear ()
The method frees memory This function will clear the array.
Afterwards, you can't access any element or you might get a segmentation fault.
Note:
All stored data will be forgotten.
Reimplemented from ngArray< TV >.
Definition at line 204 of file CArray2d.h.
void print () const
The method prints all elements of the array.
Definition at line 210 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::print().
size_t write (T x, FILE * fp) const
Write into binary file.
Parameters:
x is a dummy parameter used to choose char or float or double format for writing of array elements; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure.
Returns:
number of elements actually written, which may be less than dim1*dim2(or dim1*dim2*3 for TV==Vector3d) if an error occurs; see fwrite in <stdio.h>
Note:
fwrite from <stdio.h> is used because it fast; file must be opened in binary mode before writing: FILE *fp=fopen("test","wb");
Definition at line 222 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::write(), and CArray2d< Vector3d >::write0().
size_t read (T x, FILE * fp)
Read from binary file the array that was written by write() method.
Parameters:
x is a dummy parameter used to specify the file format; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure
Returns:
number of elements actually read. which may be less than dim1*dim2(or dim1*dim2*3 for TV==Vector3d) if an error occurs or if the end of the file is encountered; see fread in <stdio.h>
Note:
fread from <stdio.h> is used because it fast file must be opened in binary mode before reading: FILE *fp=fopen("test","rb");
Definition at line 241 of file CArray2d.h.
Referenced by CArray2d< Vector3d >::read(), and CArray2d< Vector3d >::read0().
size_t write0 (T x, FILE * fp) const
The same as write() but the shape of the array are not saved, only dimensions are saved.
Returns:
number of elements actually written.
Definition at line 254 of file CArray2d.h.
size_t read0 (T x, FILE * fp)
The method reads the array that was written by write0() method.
Returns:
number of elements actually read.
Definition at line 263 of file CArray2d.h.
The documentation for this class was generated from the following file:
CArray2d.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik