MConf: CArray1d< TV > Class Template Reference
CArray1d< TV > Class Template Reference
This class provides 1d-array.
#include <CArray1d.h>
Public Member Functions
CArray1d ()
Default constructor.
CArray1d (int dim1)
Constructor, creates array with dimention dim1.
CArray1d (int low1, int upper1)
Constructor.
CArray1d (CArray1d const &z)
Copy constructor, creates array with the same content and shape as z.
CArray1d (TV *z, int size)
Copy constructor, creates array1d with the same content z.
bool assign (const TV *z, int size)
The method creates array from TV * z.
bool scale (const TV fact)
The method scales array.
bool isOK () const
The method returns true if no error occurs for the last operation with array.
int size () const
get the the first dimention of the array.
int lowbound () const
get the first value of the first array index.
int upperbound () const
get the last value of the first array index.
bool isIndexOK (int i) const
check whether indexes within bounds
int bsearch (double u) const
Perform a binary search of the segment in which given value lies.
TV interp1 (double x, const CArray1d< double > &Xa) const
Linear interpolation of this array in x with Xa as the abscissa array.
TV interp2 (double x, const CArray1d< double > &Xa) const
Quadratic interpolation of this array in x with Xa as the abscissa array.
TV & at (int i)
The operator returns the reference to the array element.
TV * rw ()
The operator returns the address to the memory allocated for the array.
const TV & operator[] (int i) const
Returns a constant reference to the element at i.
TV & w (int i)
TV * w ()
CArray1d & operator= (const TV &x)
The operator assigns x to all elements.
CArray1d & operator= (const CArray1d &z)
Assignment operator.
bool init (int dim)
The method changes the dimentions of the array.
bool init (int low, int upper, const TV &val=TV())
The method changes the shape of the array.
bool resize (int low, int upper, const TV &val=TV())
The method changes the shape of the array.
bool resize (int dim)
The method changes the dimentions of the array.
void clear ()
The method frees memory This function will clear the array.
void print () const
The method prints all elements of the array.
template<class T >
size_t write (T x, FILE *fp) const
Write into binary file.
template<class T >
size_t read (T x, FILE *fp)
Read from binary file the array that was written by write() method.
template<class T >
size_t write0 (T x, FILE *fp) const
The same as write() but the shape of the array are not saved, only dimensions are saved.
template<class T >
size_t read0 (T x, FILE *fp)
The method reads the array that was written by write0() method.
Detailed Description
template<class TV>
class MConf::CArray1d< TV >
This class provides 1d-array.
For internal use only.
Usage:
 #include "CArray1d.h"
 int main() {
   MConf::CArray1d<MConf::Vector3d> vertex;
   vertex.resize(100);    // resize to array[0:99]
   vertex.resize(-10,20); // resize to array[-10:20]
   vertex.at(-10) = MConf::Vector3d(1,2,3);
   vertex.rw()[-10] = MConf::Vector3d(1,2,3);
   MConf::Vector3d r = vertex[20];  // important! operator[] provides read only access
   FILE *fp=fopen("test","wb");
 }
Definition at line 27 of file CArray1d.h.
Constructor & Destructor Documentation
CArray1d ()
Default constructor.
Definition at line 32 of file CArray1d.h.
CArray1d (int dim1)
Constructor, creates array with dimention dim1.
Use isOK() method to check whether the method succeeds.
Definition at line 35 of file CArray1d.h.
CArray1d (int low1, int upper1)
Constructor.
Parameters:
low1,upper1 are the bounds for the array index Use isOK() method to check whether the method succeeds.
Definition at line 41 of file CArray1d.h.
CArray1d (CArray1d< TV > const & z)
Copy constructor, creates array with the same content and shape as z.
Use isOK() method to check whether the method succeeds.
Definition at line 46 of file CArray1d.h.
CArray1d (TV * z, int size)
Copy constructor, creates array1d with the same content z.
Use isOK() method to check whether the method succeeds.
Definition at line 49 of file CArray1d.h.
Member Function Documentation
bool assign (const TV * z, int size)
The method creates array from TV * z.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 54 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::CArray1d().
bool scale (const TV fact)
The method scales array.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 61 of file CArray1d.h.
bool isOK () const
The method returns true if no error occurs for the last operation with array.
Definition at line 66 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::assign(), CArray1d< Vector3d >::print(), CArray1d< Vector3d >::resize(), CArray1d< Vector3d >::scale(), CArray1d< Vector3d >::write(), and CArray1d< Vector3d >::write0().
int size () const
get the the first dimention of the array.
Reimplemented from ngArray< TV >.
Definition at line 68 of file CArray1d.h.
Referenced by CStconfig::getBorderSize(), CArray1d< Vector3d >::interp2(), and CArray1d< Vector3d >::scale().
int lowbound () const
get the first value of the first array index.
Definition at line 70 of file CArray1d.h.
int upperbound () const
get the last value of the first array index.
Definition at line 72 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::isIndexOK().
bool isIndexOK (int i) const
check whether indexes within bounds
Definition at line 74 of file CArray1d.h.
int bsearch (double u) const
Perform a binary search of the segment in which given value lies.
Parameters:
u is the value to search for the segment
Returns:
left end of the segment in which u lies.
Note:
This array must be in ascending order.
Definition at line 81 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::interp1(), and CArray1d< Vector3d >::interp2().
TV interp1 (double x, const CArray1d< double > & Xa) const
Linear interpolation of this array in x with Xa as the abscissa array.
Parameters:
x is the abscissa point at which the interpolated value is needed.
Xa is the abscissa array.
Returns:
the interpolated value of this array in the point x.
Note:
The arrays (Xa and this) must have the same shape, test for consistensy is not perfomed.
Definition at line 105 of file CArray1d.h.
TV interp2 (double x, const CArray1d< double > & Xa) const
Quadratic interpolation of this array in x with Xa as the abscissa array.
Returns:
the interpolated value of this array in the point x.
Note:
The arrays (Xa and this) must have the same shape, test for consistensy is not perfomed.
Definition at line 118 of file CArray1d.h.
TV& at (int i)
The operator returns the reference to the array element.
Parameters:
i is the element index
Returns:
reference to the correspondent array element.
Definition at line 139 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::assign(), and CArray1d< Vector3d >::scale().
TV* rw ()
The operator returns the address to the memory allocated for the array.
Returns:
(address of allocated memory) - (lowest array index), so that rw()[lowestIndex] is the first array element.
Definition at line 143 of file CArray1d.h.
const TV& operator[] (int i) const
Returns a constant reference to the element at i.
The function returns a constant reference to the element at i. i should be limited to min ... max, otherwise it is made to fit into that range.
Note:
You should check that the array is not empty. Accessing elements from an empty ngArray will cause a segmentation fault.
This operator usually returns quite fast, no copying will be performed.
Reimplemented from ngArray< TV >.
Definition at line 144 of file CArray1d.h.
TV& w (int i)
Definition at line 147 of file CArray1d.h.
TV* w ()
Definition at line 148 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::print(), CArray1d< Vector3d >::read(), CArray1d< Vector3d >::read0(), CArray1d< Vector3d >::write(), and CArray1d< Vector3d >::write0().
CArray1d& operator= (const TV & x)
The operator assigns x to all elements.
Definition at line 151 of file CArray1d.h.
CArray1d& operator= (const CArray1d< TV > & z)
Assignment operator.
Definition at line 157 of file CArray1d.h.
bool init (int dim)
The method changes the dimentions of the array.
Previous content of the array is not preserved. The method is the same as resize(int dim1,int dim2).
Parameters:
dim is the new dimention.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 173 of file CArray1d.h.
bool init (int low, int upper, const TV & val = TV())
The method changes the shape of the array.
Previous content of the array is not preserved.
Parameters:
low,upper are the bounds for the 1st index.
val is the value to initialize array.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds. The method is the same as resize(int low1,int upper1,const TV & val = TV()).
Reimplemented from ngArray< TV >.
Definition at line 184 of file CArray1d.h.
bool resize (int low, int upper, const TV & val = TV())
The method changes the shape of the array.
Previous content of the array is not preserved.
Parameters:
low,upper are the bounds for the 1st index.
val is the value to initialize array.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds.
Definition at line 194 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::assign(), CArray1d< Vector3d >::CArray1d(), CArray1d< Vector3d >::init(), CArray1d< Vector3d >::read(), CArray1d< Vector3d >::read0(), and CArray1d< Vector3d >::resize().
bool resize (int dim)
The method changes the dimentions of the array.
Previous content of the array is not preserved.
Parameters:
dim is the new dimention.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 206 of file CArray1d.h.
void clear ()
The method frees memory This function will clear the array.
Afterwards, you can't access any element or you might get a segmentation fault.
Note:
All stored data will be forgotten.
Reimplemented from ngArray< TV >.
Definition at line 216 of file CArray1d.h.
void print () const
The method prints all elements of the array.
Definition at line 222 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::print().
size_t write (T x, FILE * fp) const
Write into binary file.
Parameters:
x is a dummy parameter used to choose char or float or double format for writing of array elements; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure.
Returns:
number of elements actually written, which may be less than dim1(or dim1*3 for TV==Vector3d) if an error occurs; see fwrite in <stdio.h>
Note:
fwrite from <stdio.h> is used because it fast; file must be opened in binary mode before writing: FILE *fp=fopen("test","wb");
Definition at line 234 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::write(), and CArray1d< Vector3d >::write0().
size_t read (T x, FILE * fp)
Read from binary file the array that was written by write() method.
Parameters:
x is a dummy parameter used to specify the file format; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure
Returns:
number of elements actually read. which may be less than dim1*dim2(or dim1*dim2*3 for TV==Vector3d) if an error occurs or if the end of the file is encountered; see fread in <stdio.h>
Note:
fread from <stdio.h> is used because it fast file must be opened in binary mode before reading: FILE *fp=fopen("test","rb");
Definition at line 251 of file CArray1d.h.
Referenced by CArray1d< Vector3d >::read(), and CArray1d< Vector3d >::read0().
size_t write0 (T x, FILE * fp) const
The same as write() but the shape of the array are not saved, only dimensions are saved.
Returns:
number of elements actually written.
Definition at line 261 of file CArray1d.h.
size_t read0 (T x, FILE * fp)
The method reads the array that was written by write0() method.
Returns:
number of elements actually read.
Definition at line 269 of file CArray1d.h.
The documentation for this class was generated from the following file:
CArray1d.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik