MConf: CBtrace< Bfield > Class Template Reference
CBtrace< Bfield > Class Template Reference
The class is used for B-field line tracing.
#include <CBtrace.h>
Classes
class RightHand
Public Member Functions
CBtrace ()
CBtrace (Bfield &B, double fiStep=0.0017453)
The constructor creates an instance of tracing object.
virtual ~CBtrace ()
void init (Bfield &B, double fiStep=0.0017453, double atol=ATOL, double rtol=RTOL)
void init ()
void setStep (double fiStep)
void advance (double dfi, Vector3d &cyl)
void advancePoloidally (double dtheta, double q, Vector3d &cyl)
Detailed Description
template<class Bfield>
class MConf::CBtrace< Bfield >
The class is used for B-field line tracing.
The following equations are solved:
dr/dfi=Br*r/Bfi
dz/dfi=Bz*r/Bfi
Usage:
 #include "CStconfig.h"
 int main() {
   MConf::CStconfig mConf;
   mConf.load ("w7x-sc1.bin4");
   if(!mConf.isOK()) exit(1);   // exit with error
   mConf.truncate(1e-6);        //truncate spectrum
   mConf.setAccuracy(1e-3);     //set accuracy of transformation
  //Function object returns vector of magnetic field for point in cylindrical coordinates.
   class Bfield {
     MConf::CStconfig *mC;
   public:
     Bfield(MConf::CStconfig &magConf) { mC = &magConf; }
   // The operator returns vector of magnetic field for point in cylindrical coordinates
     Vector3d operator() ( const Vector3d &cyl ) const {
       return mC->getBcyl(cyl);
     }
   };
   // create function object that returns magnetic field
   Bfield Bf(magConf);
   // create B-trace object
   MConf::CBtrace<Bfield> btrace(Bf,dfi);
   MConf::Vector3d cyl(6,0,0);              // starting point in cylindrical coordinates
   double fi_increment = 1*(pi/180); // 1 degree increment in toroidal angle
   btrace.advance(fi_increment,cyl); // move to new point, cyl is updated
 }
Definition at line 52 of file CBtrace.h.
Constructor & Destructor Documentation
CBtrace ()
Definition at line 67 of file CBtrace.h.
CBtrace (Bfield & B, double fiStep = 0.0017453)
The constructor creates an instance of tracing object.
Parameters:
B is the function object that returns vector of magnetic field for given point in cylindrical coordinates,
fiStep is the Runge-Kutta step along magnetic field line in toroidal direction.
Note:
Bfield object have to provide B-vector:
   MConf::CStconfig magConf
   Bfield B(magConf);
   Vector3d cyl(6,0,0);
   Vector3d Bcyl = B(cyl);
See also:
MConf::CStconfig::Bfield and usage of CBtrace
Definition at line 81 of file CBtrace.h.
References rkf45::init().
virtual ~CBtrace () [virtual]
Definition at line 89 of file CBtrace.h.
Member Function Documentation
void init (Bfield & B, double fiStep = 0.0017453, double atol = ATOL, double rtol = RTOL)
Definition at line 90 of file CBtrace.h.
References rkf45::init().
void init ()
Definition at line 98 of file CBtrace.h.
References rkf45::init().
void setStep (double fiStep)
Definition at line 103 of file CBtrace.h.
void advance (double dfi, Vector3d & cyl)
Definition at line 108 of file CBtrace.h.
References rkf45::advance().
void advancePoloidally (double dtheta, double q, Vector3d & cyl)
Definition at line 137 of file CBtrace.h.
References rkf45::advance().
The documentation for this class was generated from the following file:
CBtrace.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik