MConf: ng2Matrix< T > Class Template Reference
ng2Matrix< T > Class Template Reference
a 2 dimensional matrix type
This class is based on ngArray<T> and represents a 2-dimensional matrix. The init() and fill() functions work as expected for a matrix - they perform the initialization of all elements in the array. Indexing is the same as for the C-style matrices - i.e. matrix[i][j] will return a reference to the appropriate value.
#include <ngarray.h>
Public Member Functions
ng2Matrix ()
constructor. Creates an empty matrix that contains no elements.
ng2Matrix (int min1, int max1, int min2, int max2, const T &val=T())
constructor. Creates a matrix that is shaped according to the dimensions supplied. All elements are initialized with the supplied val. If no val is given, the default constructor for the type is called.
ng2Matrix (size_t s1, size_t s2, const T &val=T())
constructor. Creates a matrix that has the dimensions (0:s1-1, 0:s2-1). All elements are initialized with the supplied val. If no val is given, the default constructor for the type is called.
void fill (const T &val)
initialize all elements with a constant value.
void init (int min1, int max1, int min2, int max2, const T &val=T())
reshape and initialize the matrix
void init (size_t s1, size_t s2, const T &val=T())
reshape and initialize the matrix
Detailed Description
template<class T>
class MConf::pBase::ng2Matrix< T >
a 2 dimensional matrix type
This class is based on ngArray<T> and represents a 2-dimensional matrix. The init() and fill() functions work as expected for a matrix - they perform the initialization of all elements in the array. Indexing is the same as for the C-style matrices - i.e. matrix[i][j] will return a reference to the appropriate value.
This class is optimized to be passed around as argument and handles copy operations quite fast. It uses data sharing between multiple instances as much as possible and so tries to minimize the memory footprint.
Because the data sharing happens transparently to the user, assignments of values to an element might require deep copies of some part of the data that is shared between multiple instances.
It is possible for the matrix to be empty (to contain not a single element) In this case, you must not use the access operators - they will fail and cause a segmentation fault. Rather, you may check whether the matrix is empty by calling empty(). If you want the matrix to contain at least a single element, use a proper constructor or the init() function and pass a value of 0 to each index.
Definition at line 405 of file ngarray.h.
Constructor & Destructor Documentation
ng2Matrix ()
constructor. Creates an empty matrix that contains no elements.
Definition at line 411 of file ngarray.h.
ng2Matrix (int min1, int max1, int min2, int max2, const T & val = T())
constructor. Creates a matrix that is shaped according to the dimensions supplied. All elements are initialized with the supplied val. If no val is given, the default constructor for the type is called.
Definition at line 415 of file ngarray.h.
References ng2Matrix< T >::init().
ng2Matrix (size_t s1, size_t s2, const T & val = T())
constructor. Creates a matrix that has the dimensions (0:s1-1, 0:s2-1). All elements are initialized with the supplied val. If no val is given, the default constructor for the type is called.
Definition at line 423 of file ngarray.h.
References ng2Matrix< T >::init().
Member Function Documentation
void fill (const T & val)
initialize all elements with a constant value.
This function will initialize all elements of the matrix with a constant value. Data sharing is used as much as possible between the rows of the matrix.
Definition at line 434 of file ngarray.h.
References ngArray< ngArray< T > >::detach(), and ngArray< ngArray< T > >::p.
void init (int min1, int max1, int min2, int max2, const T & val = T())
reshape and initialize the matrix
This function makes the matrix forget all stored data, reshape itself to the new dimensions, and initialize all elements with the constant value supplied. Data sharing is used as much as possible to keep the memory requirements low. If no initialization value is given, the default constructor for the type is called.
Definition at line 455 of file ngarray.h.
References ngArray< ngArray< T > >::p.
Referenced by ng2Matrix< T >::init(), and ng2Matrix< T >::ng2Matrix().
void init (size_t s1, size_t s2, const T & val = T())
reshape and initialize the matrix
This function makes the matrix forget all stored data, reshape itself to the new dimensions, and initialize all elements with the constant value supplied. Data sharing is used as much as possible to keep the memory requirements low. If no initialization value is given, the default constructor for the type is called.
Note:
After calling this function, the array will have the dimensions (0:s1-1,0:s2-1).
Definition at line 477 of file ngarray.h.
References ng2Matrix< T >::init().
The documentation for this class was generated from the following file:
ngarray.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik