MConf: CStconfig Class Reference
CStconfig Class Reference
Magnetic configuration of a stellarator.
#include <CStconfig.h>
Classes
struct __allEps
This class is for internal use only.
struct __allFbs
This class is for internal use only.
class __averagedData
This class is for internal use only.
class __booz
This class is for internal use only.
class __epsilon
This class is for internal use only.
class __Fbs
This class is for internal use only.
class __lcms
This class is for internal use only.
class __spline
This class is for internal use only used for splining of Ip, It, iota, Volume, Vprime,.
class amoebaFunc
Function object returns the magnetic field for given point in magnetic coordinates.
class Bfield
Function object returns vector of magnetic field for given point in cylindrical coordinates.
class CComplex
This class is for internal use only.
struct ctResults
The internal structure holds things after last coordinate transformation/NJacobian calculation.
struct ctStack
The internal fast stack for ctResults.
struct splineCoeffs
internal structure holds things for splining
class sumDat
This class is for internal use only.
Public Types
enum fileFormat {
UNDEFINED, W7X_FMT, W7X_BIN4, W7X_BIN8,
LHD, LHD1, VMEC, VMECNETCDF,
W7X_DB, EFIT, W7X_FMT_TSFC, W7X_FMT_VMEC,
W7X_FMT_VMEC_FP, TORBEAM, NEMEC
}
Public Member Functions
CStconfig * clone ()
The method creates a clone of CStconfig using operator new.
CStconfig ()
The constructor creates an empty instance of CStconfig.
CStconfig (const char *filename)
The constructor creates an instance of CStconfig loading file.
virtual ~CStconfig ()
The destructor is a virtual method.
virtual void clear ()
The method frees all internal arrays and makes this object empty.
int setRightCoordinateSystem ()
The method reload the current magnetic configuration to the right oriented (s,theta,phi) coordinate system.
int setLeftCoordinateSystem ()
The method reload the current magnetic configuration to the left oriented (s,theta,phi) coordinate system.
int reverseCoordinateSystem ()
The method reload the current magnetic configuration to opposite oriented coordinate system.
int flipZcoordinate ()
The method reload the current magnetic configuration to opposite oriented coordinate system by fliping z-coordinate.
bool loadEfitAndScale (const char *fname, double scaleBpol=0, double scaleBtor=0, int signBpol=0, int signBtor=0, int signQ=0, int psiOverTwopi=0)
The method loads the G EQDSK file and transforms it to the tokamak-symmetry flux coordinates.
bool loadTokamak (const CStconfig *mconf)
The method creates the circular tokamak with the same R0, a, and iota as in the mconf.
Accuracy, B value
virtual void setB0 (double B0, double ficyl)
Set the value of magnetic field on magnetic axis at given cylindrical angle.
virtual void setB0 (double B0)
Set minimum magnetic field on magnetic axis.
virtual void setB00 (double B00)
Set the B00 value of magnetic field on magnetic axis.
virtual void scaleB (double multiplier)
Set normalization factor for value of the magnetic field.
virtual void setIcoil (double I)
Set the Ipol value of the coil currents at LCMS.
virtual double getBscaleFactor ()
double getIcoil ()
Get the minimum value of the magnetic field on axis Get the Ipol value of the coil currents at LCMS.
virtual void restoreB0 ()
Restore initial value of the magnetic field(which is stored in a bc-file).
double getB00 ()
Get the B00 value of the magnetic field on axis.
double getB0 ()
Get the minimum value of the magnetic field on axis.
double getB0max ()
Get the maximum value of the magnetic field on axis.
double getB0 (double ficyl)
Get the value of the magnetic field on axis at cylindrical angle ficyl.
int getBdirection ()
The method returns the direction of B with respect to cylindrical angle of the right handed cylindrical coordinate system.
void setBdirection (int sign)
The method sets the direction of B with respect to cylindrical angle of the right handed coordinate system.
void restoreBdirection ()
The method sets the original direction of B with respect to cylindrical angle of the right handed coordinate system.
double truncate (double level)
Set truncation level to reduce number of harmonics used in summation.
double truncate () const
The method returns the current value of truncation level.
void setAccuracy (double epsA, double epsR=1e-5)
Set accuracy of coordinate transformation.
Info
double Z0 () const
The method returns the tokamak magnetic axis position in [m].
double R0 () const
The method returns the major radius in [m].
double rminor () const
The method returns the minor radius [m].
int Mpol () const
The method returns the number of poloidal harmonics.
int Ntor () const
The method returns the number of toroidal harmonics.
int MpolMinTruncated () const
The method returns the number of poloidal harmonics after the truncation level was set.
int MpolMaxTruncated () const
The method returns the number of poloidal harmonics after the truncation level was set.
int NtorMinTruncated () const
The method returns the number of toroidal harmonics after the truncation level was set.
int NtorMaxTruncated () const
The method returns the number of toroidal harmonics after the truncation level was set.
int nPeriods () const
The method returns the number of periods.
int nSurfaces () const
The method returns the number of flux surfaces used.
int nSurfacesInitial () const
The method returns the number of flux surfaces stored in the magnetic configuration file.
bool isTokamak () const
The method returns true if the opened file has tokamak symmetry.
bool isTokamakSymmetryFluxCoordinates () const
The method returns true if the opened file is a Tokamak Symmetry Flux Coordinates file.
bool isVmecCoordinates () const
The method returns true if the opened file is a VMEC file.
bool isVmecCoordinatesFromFP () const
The method returns true if the opened file is a VMEC file from the Function Parametrization procedure.
int vmecReturnCode () const
The method returns VMEC completion code.
Surface quantity
double r (double s) const
The method returns the effective radius r=a*sqrt(s), where a is the plasma minor radius defined as sqrt(averageCrossSectionArea(s=1)/pi), this definition of a is used by VMEC code.
double rdkes (double s) const
The method returns the effective radius defined as sqrt(Flux(s)/B00(s)/pi).
double rdkes2 (double s)
double rgraz (double s)
The method returns the minor radius dr=ds/<|grad(s)|> (Graz definition of the radius).
double drgraz_dr (double s)
The method returns dr_graz/dr, where r=a*sqrt(s) is the VMEC definition of minor radius.
double drdkes_dr (double s)
The method returns dr_dkes/dr, where r=a*sqrt(s) is the VMEC definition of minor radius.
double drdkes2_dr (double s)
double epsEffGraz (double s)
The method returns the effective helical ripple for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
double epsEffDkes (double s)
The method returns the effective helical ripple for transport, using DKES definition of minor radius r=sqrt(Flux(s)/(pi*B_00(s))), where s is the normalized toroidal flux.
double epsEffVmec (double s)
The method returns the effective helical ripple for transport, using VMEC definition of minor radius r=a*sqrt(s), where s is the normalized toroidal flux.
double epsEffNorm (double s)
The method returns the normalized effective helical ripple for transport, using normalized diffusion coefficient.
double epsEffHat (double s)
The method returns the effective helical ripple for transport, using definition (2), (5) in http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , 28th EPS, EGA Vol.25A (2001) 1985-1988.
double Gw (double s)
eq(21) in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
double Gs (double s)
eq(26) in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
double Gv (double s)
The methods return the bounce-averade gradB drift velocity of trapped particles averaged over flux surface.
void epsEffSetXeffParam (double xmin=.05, double xmax=.95, int size=51)
The method sets parameters for calculating eps_eff and Gw, Gs, Gv.
void epsEffSetTracingParam (int turns=100, bool doAccuracyTest=true, double dphi=0.017453)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
void epsEffSetIotaParam (bool avoidResonances=false, bool useRationalIota=false, int iotaDenominator=150)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
void epsEffSetMagnMomentParam (int nBLevels=513)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
void epsEffCreate ()
The method calculates and stores the eps_eff in the look-up table.
void epsEffInvalidate ()
The method clears the look-up table with the eps_eff and Gw, Gs, Gv.
void FbsSetSlabelParam (double smin=0.0025, double smax=0.9, int size=101)
The method sets parameters for calculating the bootstrap current geometric factor.
void FbsSetXeffParam (double xmin=.05, double xmax=.95, int size=101)
The method sets parameters for calculating the bootstrap current geometric factor.
void FbsSetTracingParam (int turns=100, bool doAccuracyTest=true, double dphi=0.017453)
The method sets parameters for calculating the bootstrap current geometric factor.
void FbsSetIotaParam (bool avoidResonances=false, bool useRationalIota=false, int iotaDenominator=150)
The method sets parameters for calculating the bootstrap current geometric factor.
void FbsSetMagnMomentParam (int lambdaLevels=257, double yMax=15)
The method sets parameters for calculating the bootstrap current geometric factor.
void FbsCreate ()
The method calculates and stores the bootstrap current geometric factor in the look-up table.
void FbsInvalidate ()
The method clears the look-up table with the bootstrap current geometric factors.
double FbsVmec (double s)
The method returns the bootstrap current geometric factor for transport, using VMEC definition of minor radius r=a*sqrt(s), where s is the normalized toroidal flux.
double FbsDkes (double s)
The method returns the bootstrap current geometric factor for transport, using DKES definition of minor radius r=sqrt(Flux(s)/(pi*B_00(s))), where s is the normalized toroidal flux.
double FbsGraz (double s)
The method returns the bootstrap current geometric factor for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
double GrazLambdab (double s)
The method returns the bootstrap current geometric factor for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
double FbsFtrap (double s)
double Fbsg2Vmec (double s)
double Fbsg2Dkes (double s)
double Fbsg2Graz (double s)
double Fbsg2 (double s)
The method returns flux surface average of g2, where g2 is defined as B*grad(g2/B^2) = B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
double Fbsu (double s)
The method returns flux surface average of u, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
double FbsuB2 (double s)
The method returns flux surface average of u*B^2, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
double Fbsu2B2 (double s)
The method returns flux surface average of u^2*B^2, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
double FbsB2 (double s)
The method returns flux surface average of B^2.
double Fbsg4 (double s, double mu)
The method returns flux surface average of g4, where g4 is defined as B*grad(g4/xi) = B x grad(s) * grad(1/xi) and xi = sqrt(1 - mu*B/Bmax), s is the normalized toroidal flux.
double Fbsg4Vmec (double s, double mu)
Vector3d omega_d_BounceAveraged (const Vector3d &mag0, double dphi=0.00698, int iotaDenominator=0)
The method returns bounce average of according formula for elecrons, where , , , is the curvature vector.
std::vector< double > Jinvariant (const Vector3d &mag, double dphi=0.00698, int iotaDenominator=0)
The method returns the parallel adiabatic invariant with the integral taken between two turning points according formula .
std::vector< double > Jinv_omega_d_BounceAveraged (const Vector3d &mag0, double dphi=0.00698, int iotaDenominator=0)
The method returns bounce average of (see omega_d_BounceAveraged()) and the parallel adiabatic invariant with the integral taken between two turning points according formula (see Jinvariant()).
Vector3d getMagCoordAtB (const Vector3d &mag, double Bt)
The method returns the magnetic coordinates of the point (that belongs to the given field line) at which the magnetic field is equal to the given value.
std::vector< Vector3d > getAllMagCoordAtB (const Vector3d &mag0, double Bt)
Vector3d getNextMagCoordAtB (const Vector3d &mag0, double Bt)
double GradsAvrg (double s)
The method returns <|grad(s)|> .
double Grads2Avrg (double s)
The method returns <(grad(s))^2> .
double Grads2overB2Avrg (double s)
The method returns <(grad(s)/B)^2> .
double sPol (double s)
The method returns the normalized poloidal flux, where s is the normalized toroidal flux.
double PoloidalFlux (double s)
The method returns the poloidal flux, where s is the normalized toroidal flux.
double sToroidal (double sPoloidal)
The method returns the normalized toroidal flux, where s is the normalized poloidal flux.
double iota (double s) const
The method returns the iota, where s is the normalized toroidal flux.
double pressure (double s) const
The method returns the pressure in Pa, where s is the normalized toroidal flux.
double iotaRational (double s, int denom_guess, int &numerator, int &denominator)
The method returns rational aproximation to iota: iota = numerator/denominator.
double iotaPrime (double s) const
The method returns the diota/ds, where s is the normalized toroidal flux.
double Ip (double s) const
The method returns the poloidal current in [A].
double It (double s) const
The method returns the toroidal current in [A].
double Flux (double s) const
The method returns the toroidal flux in [Wb].
double pp (double s)
The method returns dp/ds [Pa], where p is the pressure in [Pa].
double crossSectionArea (double s, double ficyl)
The method returns the area of the cross section of the surface s at angle fi.
double averageCrossSectionArea (double s=1.)
The method returns the average area of the cross section of the surface s.
double Volume (double s)
The method returns Volume in [m3] inside surface s.
double Vprime (double s) const
The method returns Vprime=dVolume/ds in [m3].
double VprimeIntJ (double s, int nth=120, int nph=120)
The method calculates dVolume/ds in [m^3], integrating the Jacobian.
Vector3d * SMatrix (double s, int npol=180, int ntor=200)
The method calculates the Susceptance matrix in (Flux,theta,phi)-coordinates.
double S11 (double s)
Susceptance matrix: S11 in (Flux,theta,phi)-coordinates.
double S12 (double s)
Susceptance matrix: S12 in (Flux,theta,phi)-coordinates.
double S21 (double s)
Susceptance matrix: S21 in (Flux,theta,phi)-coordinates.
double S22 (double s)
Susceptance matrix: S22 in (Flux,theta,phi)-coordinates.
Vector3d curvatureAvrg (double s, int nth=120, int nph=120)
The method calculates the flux average of normal and geodesic curvatures.
Surface quantity for estimation of trapped particle fraction
void findBminBmaxPosition (double s, Vector3d &magcrdBmin, Vector3d &magcrdBmax, bool useInputAsGuess=false)
The method returns the position of Bmax on the surface s.
double Bmin (double s)
The method returns the minimum value of magnetic field on the surface s.
double Bmax (double s)
The method returns the maximum value of magnetic field on the surface s.
double Bmin ()
The method returns the minimum value of magnetic field.
double Bmax ()
The method returns the maximum value of magnetic field.
double Bavrg (double s)
The method returns the <B> -- flux average of magnetic field on the surface s.
double B2avrg (double s)
The method returns the <B2> -- flux average of magnetic field on the surface s.
double B2VolAvrg ()
The method returns the volume average of B2.
double B_2avrg (double s)
The method returns the <B-2> -- flux average of magnetic field on the surface s.
double grads2B_2avrg (double s)
The method returns the <grads^2*B^-2> -- flux average on the surface s.
double R2avrg (double s)
The method returns the <R2> -- flux average of R^2 on the surface s.
double R_2avrg (double s)
The method returns the <R-2> -- flux average of R^-2 on the surface s.
double NeoPolarizationPass (double s)
The method returns the contribution of passed particles to the neoclassical polarization on the surface s.
double NeoPolarizationTrap (double s)
The method returns the contribution of traped particles to the neoclassical polarization on the surface s.
double NeoPolarization (double s)
The method returns the neoclassical polarization on the surface s.
double db12Avrg (double s)
The method returns the value of <(1-b)0.5>, where b=B(s,th,ph)/Bmax(s).
double db32Avrg (double s)
The method returns the value of <(1-b)1.5>, where b=B(s,th,ph)/Bmax(s).
double ftrapped (double s)
The method returns the fraction of trapped particles on the surface s.
double roParInvAvrg (double s, double x) const
double pavrg (double s, double x) const
The method returns the <p> -- flux average of pitch angle on the surface s.
double integralInvPavrg (double s, double x) const
The method returns the Integral(from x to 1) dx'/P(s,x') on the surface s.
void getBminmax (double s, double &Bmin, double &Bmax, int npol=120, int ntor=120)
The method returns Bmin and Bmax -- the minimum and maximum values of magnetic field on the surface s.
void getFtrappedBminmax (double s, double &Ftrapped, double &Bmin, double &Bmax, double &Bavr, double &B2avr, int nth=120, int nph=120)
The method returns the fraction of trapped particles on the surface s.
Splined Fourier coefficients
double Bmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of |B|-expansion.
double Rmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of R-expansion, for parameters see Bmn_sp().
double Zmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of Z-expansion, for parameters see Bmn_sp().
double Phimn_sp (double s, int m, int n) const
The method returns Fourier coefficient of Phi-expansion, for parameters see Bmn_sp().
double lmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of VMEC lambda expansion, for parameters see Bmn_sp().
double gmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of VMEC Jacobian expansion, for parameters see Bmn_sp().
double BcontrPolmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of expansion of poloidal contravariant B, for parameters see Bmn_sp().
double BcontrTormn_sp (double s, int m, int n) const
The method returns Fourier coefficient of expansion of toroidal contravariant B, for parameters see Bmn_sp().
double Bmn_sp_prime (double s, int m, int n) const
double Boozer2Bmn (double s, int m, int n)
double BoozerBmn (double s, int m, int n)
s-grid info
double get_s (int is) const
The method returns flux surface label s(norm.tor.flux).
double get1st_s () const
The method returns the s value of the first surface stored in a file.
double getLast_s () const
The method returns the s value of the last surface stored in a file.
int getIdx1st_s () const
The method returns the index of the first flux surface in array CStconfig::ms.
int getIdxLst_s () const
The method returns the index of the last flux surface in array CStconfig::ms.
int SearchSindx (double s, bool halfMesh=true) const
The method returns the index in array CStconfig::ms, which corresponds to s.
Coordinate transformation from magnetic coordinates to real space
Vector3d mag2xyz (const Vector3d &magCoord) const
The method returns the cartesian coordinates of the point.
Vector3d mag2xyz (double s, double theta, double phi) const
The method makes transformation from magnetic coordinates to cartesian.
Vector3d mag2cyl (const Vector3d &magCoord) const
The method makes transformation from magnetic coordinates to cylindrical.
Vector3d mag2cyl (double s, double theta, double phi) const
The method makes transformation from magnetic coordinates to cylindrical.
Vector3d mixcoord2cyl (double s, double theta, double fi, double *phi=0, sumDat *sdat=0) const
The method returns cylindrical coordinates which correspond to the mixed coordinates.
Vector3d mixcoord2cyl (const Vector3d &mixcoord, double *phi=NULL) const
The method returns cylindrical coordinates which correspond to the mixed coordinates.
Vector3d mixcoord2xyz (const Vector3d &mixcoord, double *phi=NULL) const
The method returns cartesian coordinates which correspond to the mixed coordinates.
Vector3d Axiscyl (double ficyl) const
The method returns cylindrical coordinates of the magnetic axis.
Transformation between VMEC and Boozer Coordinates
Vector3d Vmec2Boozer (const Vector3d &vmecCoord)
The method transforms the VMEC coordinates to Boozer.
Vector3d Boozer2Vmec (const Vector3d &boozer)
The method transforms the Boozer coordinates to VMEC.
bool writeVmec2Boozer (const char *fname, int method=0, int M=0, int N=0)
The method transforms the VMEC wout-file to Boozer-coordinate data file.
double Vmec2BoozerTest (const Vector3d &vmecCoord)
The method peforms test, that d(theta_booz,phi_booz)/d(theta_vmec,phi_vmec) == (Jacobian_vmec/Jacobian_booz).
Inquire position
bool cylIsInside (const Vector3d &cyl, double *distance=0) const
The method tests whether the point lies inside LCMS.
bool xyzIsInside (const Vector3d &xyz, double *distance=0) const
The method tests whether the point lies inside LCMS.
bool cylIsInsideBorder (const Vector3d &cyl, double *distance=0, Vector3d *point=0, Vector3d *magCoord=0) const
The method tests whether the point lies inside the given border.
bool createBorder (double s, double ficyl, int borderSize=150)
The method creates the border -- 's'-contour at cylindrical angle 'ficyl'.
int getBorderSize ()
The method returns the number of points in the border created by createBorder() method.
const Vector3d & getBorder (int k) const
The method returns the cylindrical cooordinates of the k-point of the border.
const Vector3d & getBorderMag (int k) const
The method returns the magnetic cooordinates of the k-point of the border.
const double & getBorderRmin () const
The method returns the min value of R-cooordinate of the border.
const double & getBorderRmax () const
The method returns the max value of R-cooordinate of the border.
const double & getBorderZmin () const
const double & getBorderZmax () const
bool getRayEntryPoint (const Vector3d &r0, const Vector3d &rd, Vector3d &entryPoint)
The method traces the Last Closed Magnetic Surface (LCMS).
bool getRayIntersectionPoints (const Vector3d &r0, const Vector3d &rd, Vector3d &entryPoint, Vector3d &exitPoint)
The method traces the Last Closed Magnetic Surface (LCMS).
Vector3d xyzAtB (double Bres, const Vector3d &r0, const Vector3d &rd, const Vector3d &entryPoint)
void getCoeffForAstraCode (double sqrts, double &r, double &gradr2, double &J, double &G2, double &hV, double &B0, double &R0, double &h)
Statistics
void zeroStatistics ()
Clear statistics.
int & nJac ()
The method returns the number of NJacobian calls.
int & n2mag ()
The method returns the number of coordinate transformations from real space to magnetic coordinates.
double MAverage () const
The method returns the average number of poloidal harmonics used in summation during coordinate transformations from real space to magnetic coordinates.
double NAverage () const
The method returns the average number of toroidal harmonics used in summation during coordinate transformations from real space to magnetic coordinates.
double NNjacCalls () const
The method returns the number of NJacobian calls.
double Nmag2cylCalls () const
The method returns the number of mag2cyl calls.
double Ncyl2magCalls () const
The method returns the number of cyl2mag calls.
double NGuessCalls () const
Misc
double phimag (double s, double theta, double ficyl) const
The method returns the magnetic toroidal angle which corresponds to the mixed coordinates.
double phimag (const Vector3d &mixcoord) const
The method returns the magnetic toroidal angle which corresponds to the mixed coordinates.
void getExtent (double &Rmin, double &Rmax, double &Zmin, double &Zmax, double s, double fi) const
The method returns the sizes of a rectangle circumscribed about the cross section of the surface s at cylindrical angle fi.
void getExtent (double &Rmin, double &Rmax, double &Zmin, double &Zmax, double s) const
The method returns the sizes of a rectangle circumscribed about the cross section of the surface s.
void getExtentLCMS (double &Rmin, double &Rmax, double &Zmin, double &Zmax) const
The method returns the sizes of a rectangle circumscribed about the cross section of the LCMS.
void getExtent (Vector3d &rmin, Vector3d &rmax, double s, double f1, double f2) const
The method returns the sizes of parallelepiped circumscribed about the segment f1-f2<pi of the 's' surface, 'f' is the cylindrical angle.
int getJacobianSign ()
The method returns the sign of the Jacobian calculating the mixed product dX/ds*(dX/dtheta^dX/dphi).
int getThetaDirection ()
The method returns the direction of the poloidal angle.
int getPhiDirection ()
The method returns the direction of the toroidal angle.
int getSignOfCurrentThatIncreasesAbsIota () const
The method returns the direction of the toroidal current j^phi (in the right-handed cylindrical coordinates system), that increases the absolute value of the iota.
int getDeltaIotaSign (double Itor) const
The method returns the sign of iota increment due to non-inductive current <j*B>/<|B|>.
const CArray2d< Vector3d > * LCMS ()
The method returns the pointer to the 2d-array of vertexes of LCMS.
const CArray2d< Vector3d > * BLCMS ()
The method returns the pointer to the 2d-array of the magnetic field value at the LCMS.
double mod2pi (double x) const
The method reduces x to the interval 0..2pi.
double mod2piNoWrap (double x) const
The method reduces x to the interval 0.
double modPeriod (double x) const
The method reduces x to the interval 0..2pi/mNp, where mNp is the number of stellarator periods.
void sortAngles (double &f1, double &f2) const
The method sorts angles, so that f1<f2 and f2-f1<pi.
bool createSurface (double s, int nTheta, int nPhi, CArray2d< Vector3d > &vertex, CArray2d< Vector3d > *Bfld=0, bool cylPhi=true)
The method creates array of vertexes of the surface s.
void createNormals (const CArray2d< Vector3d > &Vertexes, CArray2d< Vector3d > &normals, int sign=1) const
The method creates array of normals to the surface Vertexes.
Vector3d curvature (const Vector3d &magCoord)
The method calculates curvature at given point.
Static Public Member Functions
static const char * getVersion ()
The method returns the version of MConf in format year.month.
Protected Member Functions
bool loadfile (const char *filename, fileFormat t, long fPostn=0)
helper function for CStconfig::load()
bool loadTopfile (const char *fname)
The method loads torbeam equilibria file.
void adjustNumbersForSimpson (int &Npol, int &Ntor, double &dpol, double &dtor) const
Adjust number of integration points and steps.
void calculateCurrents ()
The method calculates currents and dV/ds if needed.
void calculateVprime ()
The method calculates dV/ds and then Volume integrating Jacobian.
void calculateFluxAverages1 (int npol=180, int ntor=200)
void calculateSMatrixArrays (int npol=180, int ntor=200)
The method tabulate arrays for finding Sij(s).
void ajustFourierCoeffMeshes ()
ajust Fourier coefficients and create radial meshes
void addSurfacesNearAxis ()
The method adds surfaces near magnetic axis and calculates spline coefficients.
void addSurfacesAfterLCMS ()
void createSplineCoeff ()
int getSsegMN (double s, int &M, int &N) const
The method searches nearest to s segment in array ms.
double VolumeInt (double s) const
The method returns the Volume inside surface s integrating Jacobian.
double VolumeInt (double s1, double s2) const
The method returns the volume between surfaces s1 and s2 integrating Jacobian.
bool createLCMS ()
The method creates array of vertexes of LCMS.
void signOfJacobianAndAngles ()
The method calculates the sign of Jacobian and angle directions.
double FluxPoloidal (double s1, double s2) const
The method is used to create flux label based on normalized poloidal flux.
void init ()
init everything before loading magnetic configuration
void clearImportantFlags ()
the method is called when the configuration is reloaded to another coordinate system (L.H.S.
void freeConf ()
Free all memory used.
void writeIdentificationComment (FILE *fp) const
write identification and comments into bc-file.
int getSignOfBnormFactor () const
return the sign of B-normalization factor
template<class T >
bool writebin (const char *fname, T szType, FILE *ff=NULL) const
helper function for write(), see also C3dMesh::writeMeshbin();
bool writebin4 (const char *fname, FILE *ff) const
helper function for write(), see also C3dMesh::writeMeshbin();
bool writebin8 (const char *fname, FILE *ff) const
helper function for write(), see also C3dMesh::writeMeshbin();
template<class T >
bool loadbin (const char *fname, T szType, FILE *ff=NULL)
helper function for load(), see also C3dMesh::loadMeshbin();
bool loadbin4 (const char *fname, FILE *ff)
helper function for load(), see also C3dMesh::loadMeshbin();
bool loadbin8 (const char *fname, FILE *ff)
helper function for load(), see also C3dMesh::loadMeshbin();
bool initAfterLoad (fileFormat fmt=UNDEFINED)
calculate spline coeffitients and add surfaces near axis.
int isInsideTriangle (const Vector3d *r, const Vector3d &n, Vector3d &ri) const
test whether point ri lies inside triangle r
int isTriangleHitted (const Vector3d *r, const Vector3d &rayR0) const
const char * fname_ext (const char *buf) const
Returns a pointer to the last period in buf.
const char * fname_name (const char *name) const
returns a pointer to the filename, or null if name ends with '/'
bool cylIsInsideEx (const Vector3d &cyl, const CArray2d< Vector3d > &vertex, double dFi, double *distance) const
The method tests whether the point lies inside LCMS.
template<class T >
void Swap (T &v1, T &v2) const
template<class T >
void SwapN (T &v1, T &v2) const
template<class T >
T square (const T x) const
template<class T >
T cube (const T x) const
template<class T >
T mmin (T x, T y) const
template<class T >
T mmax (T x, T y) const
template<class T >
T abs (T x) const
template<class T >
T setSign (T target, T sign) const
template<class T >
int sign (T x) const
template<class T >
double mantissa (T x)
double smoothHeaviside (double x, double w=1)
Static Protected Member Functions
static double Heaviside (double x)
Protected Attributes
bool mOK
result of the last operation
std::string mfname
name of the file, that was read
double pi
= 3.14159265358979
double twopi
double twopiinv
double degree
= pi/180;
double mu0
= pi*4e-7 [N/A^2 = henry/m]
int mNp
number of periods
double mPeriod
twopi/mNp
double mepsA
double mepsR
absolute and relative accuracy of coordinate transformation
int mNGuessCalls
int mNjac
number of jacobian calculation
int mMsum
number of poloiodal mod
int mNsum
number of toroidal mod
int mNcyl2mag
number of calling of cyl2mag-function(Newton's iteration)
int mNmag2cyl
number of calling of mag2cyl-function
int mMsum2
int mNsum2
int mRoughCalculation
used in cyl2guess for
ctStack ct
bool jacobianIsMixedProduct
bool Averages1Ready
bool ftrappedReady
bool BminmaxReady
bool SMatrixReady
bool tokamakSymmetryFluxCoordinates
bool vmecCoordinates
VMEC Coordinates if true.
bool vmecAsym
VMEC additional fourier coefficients in asymmetrical mode if true.
bool fpCoordinates
VMEC Coordinates from FP if true.
bool fpCoordinates2
bool fpCoordinates5
bool tokamakEQDSK
same as tokamakSymmetryFluxCoordinates
bool tokamakConfig
mN==0 && mNp==1
bool polCurrentNeeded
signal to load() function that currents must be calculated
bool torCurrentNeeded
signal to load() function that currents must be calculated
bool vprimeNeeded
signal to load() function that dV/ds must be calculated
Friends
class sumDat
class __lcms
class __epsilon
class __Fbs
class __averagedData
class __booz
class __spline
struct ctStack
Load & save functions
virtual bool load (const char *filename)
The method loads the magnetic configuration stored in the file filename.
bool load (const char *filename, long filePosition)
The method loads the magnetic configuration stored in the file filename.
bool loadEFIT (const char *filename)
The method loads the G EQDSK file and transforms it to the tokamak-symmetry flux coordinates.
bool loadLHD (const char *filename)
The method loads the magnetic configuration with Boozer coordinates from the file in LHD-format.
bool loadVMEC (const char *filename)
The method loads the VMEC wout-file.
bool loadVMECFP (const char *filename)
The method loads the VMEC netCDF wout-file.
bool loadFromDB (const void *mcdb, int equilibrium_id)
The method loads Boozer coordinates from Magnetic Configuration Data Base.
bool deleteFromDB (const void *mcdb, int equilibrium_id) const
The method deletes magnetic configuration from database.
bool writeIntoDB (const void *mcdb, const char *confname, const char *machine_name, int Nsmax, bool magAxis) const
The method inserts magnetic configuration Data into database.
bool write (const char *fname) const
Store current magnetic configuration into file.
bool writeasciiReduced (const char *fname, int nsmax=0, double newVolume=0, double newLastSurface=1, bool varNumberMods=true, bool magAxis=false, bool circular=false, bool append=false) const
The methods transform the current magnetic configuration to new volume or to new mesh on s.
bool writeasciiBmod (const char *fname, double s) const
Write |B|-spectrum on the surface s into file fname.
bool isOK () const
The method returns true if file is loaded without error.
bool isValid () const
const char * fname () const
The method returns the name of the file loaded.
|B| and Jacobian
double B (const Vector3d &magCoord) const
The function returns B=sum_mn B_mn(s)*cos(m*theta-n*Np*phi).
double BonFieldLine (const Vector3d &magCoord0, double phi)
The method returns |B| on the field line that passes through the point given by (s0,theta0,phi0).
Vector3d magCoordFieldLine (const Vector3d &magCoord0, double phi, double iota=0)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,phi0).
Vector3d mixCoordFieldLine (const Vector3d &mixCoord0, double fcyl)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,ficyl0).
Vector3d gradB (const Vector3d &magCoord)
The method returns grad(|B|).
Vector3d getCovaGradB (const Vector3d &magCoord) const
The method returns covariant components of grad(|B|).
void getBandGradients (const Vector3d &u, Vector3d &B, Vector3d &gradB, Vector3d &grads, Vector3d &gradTh, Vector3d &gradPh)
The method returns B and gradients in cylindrical coordinates.
void getBandGradientsxyz (const Vector3d &u, Vector3d &B, Vector3d &gradB, Vector3d &grads, Vector3d &gradTh, Vector3d &gradPh)
Get B and gradients in cartesian coordinates.
void getBandBasisVectorsxyz (const Vector3d &u, Vector3d &xyz, Vector3d &Bxyz, Vector3d &gradBxyz, Vector3d &e1con, Vector3d &e2con, Vector3d &e3con, Vector3d &e1cov, Vector3d &e2cov, Vector3d &e3cov)
Get B and basis vectors in cartesian coordinates.
double getdBGradscyl (const Vector3d &cyl, Vector3d &B, Vector3d &dBdr, Vector3d &dBdfir, Vector3d &dBdz, Vector3d &grads)
double getdBGradsxyz (const Vector3d &xyz, Vector3d &B, Vector3d &dBdx, Vector3d &dBdy, Vector3d &dBdz, Vector3d &grads)
Vector3d getBcurlBGradscyl (const Vector3d &u, Vector3d &B, Vector3d &curlB, Vector3d &grads)
The method returns B and curl(B) in cylindrical coordinates.
double getLocalShear (const Vector3d &magCrd, Vector3d &B, Vector3d &cyl, Vector3d &grads)
The method returns the local shear.
double getLocalShear (const Vector3d &magCrd)
void useMixedProductForJacobian (bool sw)
If sw==true then the method forces to use Jacobian=dX/dFlux*(dX/dtheta^dX/dphi) for calculating B field.
double Jacobian (const Vector3d &magCoord, double *Bmod=0) const
Jacobian: dV = Jacobian(s,theta,phi)*ds*dtheta*dphi.
Coordinate transformation from real to magnetic coordinates
void useVmecLambdaOn ()
The method forces to use the stream function lambda for B-field calculatioins, the method works only for VMEC representation, otherwise it does nothing.
void useVmecLambdaOff ()
The method forces to use the VMEC contravariant B in B-field calculatioins, the method works only for VMEC representation, otherwise it does nothing.
Vector3d * NJacobian (const Vector3d &magCoord)
The method calculates Jacobian matrix for Newton's iteration.
Vector3d * NJacobianL (const Vector3d &magCoord)
The method calculates Jacobian matrix for Newton's iteration using linear interpolation on s.
Vector3d cyl2mag (const Vector3d &cyl)
The method makes transformation from cylindrical to magnetic coordinates.
Vector3d cyl2mag (const Vector3d &cyl, const Vector3d &magCoordGuess)
The method makes transformation from cylindrical to magnetic coordinates using guess value.
Vector3d xyz2mag (const Vector3d &xyz)
The method makes transformation from cartesian to magnetic coordinates.
double cyl2s (const Vector3d &cyl)
The method finds the flux label s which corresponds to the point in space.
double xyz2s (const Vector3d &xyz)
The method finds the flux label s which corresponds to the point in space.
Vector3d cyl2guess (const Vector3d &cyl, double eps, double smax=1, bool *inside=0)
The method makes transformation from cylindrical to magnetic coordinates using 2d-iteration on R-Z plane.
double getmodB () const
The method returns |B|.
double getmodB (const Vector3d &cyl)
The method returns |B|.
double getJac () const
The method returns Jacobian=mu0*(Ipol+iota*Itor)/(4pi2B2).
double getJac (const Vector3d &cyl)
The method returns Jacobian=mu0*(Ipol+iota*Itor)/(4pi2B2).
double getJ () const
The method returns Jacobian=Flux(1)*mu0*(Ipol+iota*Itor)/(4pi2B2).
double getJ (const Vector3d &cyl)
Jacobian for coordinates (s,theta,phi).
double getJac2 () const
The method returns Jacobian=dX/dFlux*(dX/dtheta^dX/dphi).
double getJac2 (const Vector3d &cyl)
The method returns Jacobian=dX/dFlux*(dX/dtheta^dX/dphi).
double getJ2 () const
The method returns Jacobian=dX/ds*(dX/dtheta^dX/dphi).
double getJ2 (const Vector3d &cyl)
The method returns Jacobian=dX/ds*(dX/dtheta^dX/dphi).
const Vector3d & getBxyz ()
The method returns cartesian B-vector.
const Vector3d & getBxyz (const Vector3d &xyz)
The method returns cartesian B-vector at cartesian point xyz.
const Vector3d & getBcyl () const
The method returns cylindrical B-vector.
const Vector3d & getBcyl (const Vector3d &cyl)
The method returns cylindrical B-vector.
const Vector3d & getGradtheta () const
The method returns cylindrical vector grad(theta).
const Vector3d & getGradtheta (const Vector3d &cyl)
The method returns cylindrical vector grad(theta).
Vector3d getGradlambda (const Vector3d &cyl)
The method returns cylindrical vector grad(lambda) for VMEC coordinates, where lambda is the stream function.
Vector3d getGradlambda () const
The method returns cylindrical vector grad(lambda) for VMEC coordinates, where lambda is the stream function.
const Vector3d & getGradphi () const
The method returns cylindrical vector grad(phi).
const Vector3d & getGradphi (const Vector3d &cyl)
The method returns cylindrical vector grad(phi).
const Vector3d & getGradFlux () const
The method returns cylindrical vector grad(Flux).
const Vector3d & getGradFlux (const Vector3d &cyl)
The method returns cylindrical vector grad(Flux).
const Vector3d & getGrads () const
The method returns cylindrical vector grad(s).
const Vector3d & getGrads (const Vector3d &cyl)
The method returns cylindrical vector grad(s).
Vector3d getGradsxyz () const
The method returns cartesian vector grad(s).
Vector3d getGradsxyz (const Vector3d &xyz)
The method returns cartesian vector grad(s).
const Vector3d & getGradreff () const
The method returns cylindrical vector grad(reff).
const Vector3d & getGradreff (const Vector3d &cyl)
The method returns cylindrical vector grad(reff).
const Vector3d * getNJmatrix ()
The method retuns pointer to the Jacobian matrix for Newton's iteration calculated by CStconfig::NJacobian().
const Vector3d * getNJmatrix (const Vector3d &cyl)
The method retuns pointer to the Jacobian matrix for Newton's iteration calculated by CStconfig::NJacobian() for point cyl.
const Vector3d * getMetricTensor ()
The method retuns pointer to the MetricTensor calculated by CStconfig::NJacobian.
const Vector3d * getMetricTensor (const Vector3d &cyl)
The method returns pointer to the metricTensor calculated in the point cyl.
Vector3d getRcyl () const
The method returns the cylindrical coordinates of the last point used in coordinate transformation.
Vector3d getRxyz () const
The method returns the cartesian coordinates of the last point used in coordinate transformation.
const Vector3d & getBcova () const
The method returns covariant components of B = (B_s,B_theta,B_phi) in (s,theta,phi) coordinates.
const Vector3d & getBcontra () const
The method returns contravariant components of B = (0,B^theta,B^phi).
void getCovaBasis (Vector3d &e1, Vector3d &e2, Vector3d &e3) const
The method returns covariant-basis vectors e_i = dX/du^i in cylindrical coordinates.
void getContraBasis (Vector3d &e1, Vector3d &e2, Vector3d &e3) const
The method returns contravariant-basis vectors e^i = grad(u^i) in cylindrical coordinates.
Vector3d getGradBcyl ()
The method returns grad(|B|) in cylindrical coordinates.
Vector3d getGradBcyl (const Vector3d &cyl)
The method returns grad(|B|) in cylindrical coordinates.
Vector3d getGradBxyz ()
The method returns grad(|B|) in cartesian coordinates.
Vector3d getGradBxyz (const Vector3d &xyz)
The method returns grad(|B|) in cartesian coordinates.
Vector3d Vmec2Pest (const Vector3d &vmec)
VMEC coordinates vmecCoord=(s,theta,phi).
Vector3d Pest2Vmec (const Vector3d &pest)
Vector3d SFLcoordOnBlineAtTheta (const Vector3d &pest0, double theta, double iotA=0)
void SFLcontraBasis (const Vector3d &pest, Vector3d &e1, Vector3d &e2, Vector3d &e3, Vector3d &vmec)
void BoozerContraBasis (const Vector3d &booz, Vector3d &e1, Vector3d &e2, Vector3d &e3, Vector3d &vmec)
void Vmec2PestContraBasis (const Vector3d &vmec, Vector3d &e1, Vector3d &e2, Vector3d &e3, Vector3d &pest)
Detailed Description
Magnetic configuration of a stellarator.
Class for geometric calculation. This class provides the coordinate transformation between magnetic coordinates and real space coordinates.
Usage:
 #include "CStconfig.h"
 int main() {
   CStconfig mConf;
   mConf.load ("w7x-sc1.bin4"); //load configuration with Boozer coordinates
   if(!mConf.isOK()) exit(1);   //exit with error
   mConf.truncate(1e-5);        //truncate spectrum
   mConf.setAccuracy(epsA);     //set accuracy of transformation
   mConf.setB0(2.5);            //set minimum value of B on magn. axis
   Vector3d cyl(6,0.01745,0.5);// R=6,fi=1deg,Z=0.5
 //  coordinate transformation form cylindrical to magnetic coordinates
   Vector3d boozer = mConf.cyl2mag(cyl); // boozer is (s,theta,phi)
   Vector3d B = mConf.getBcyl(cyl);         // B-vector in cylindrical coord.
   double s = boozer[0];               // normalized toroidal flux
   double reff = mConf.r(s);           // effective r in [m]
 }
Todo:
add function void setWarningLevel(int level);
Examples:
1stexample.cpp, accuracytest.cpp, cpp2for.cpp, eeff_example.cpp, Fbs_example.cpp, Gv_example.cpp, and remesh.cpp.
Definition at line 63 of file CStconfig.h.
Member Enumeration Documentation
enum fileFormat
Enumerator:
UNDEFINED file-format types, for internal use
unknown file format
W7X_FMT ascii W7X format(J.Geiger)
W7X_BIN4 4-byte(float) binary W7X format(Y.Turkin)
W7X_BIN8 8-byte(double) binary W7X format(Y.Turkin)
LHD LHD format.
LHD1 LHD format.
VMEC VMEC wout-format; use without transformation to Boozer coordinates.
VMECNETCDF VMEC netCDF wout-format; use without transformation to Boozer coordinates.
W7X_DB W7X format from database.
EFIT G EQDSK File from EFIT.
W7X_FMT_TSFC ascii W7X format(Y.Turkin) for Tokamak Symmetry Flux Coordinates
W7X_FMT_VMEC ascii W7X format(Y.Turkin) for VMEC Coordinates
W7X_FMT_VMEC_FP ascii W7X format(J.Geiger) for VMEC Coordinates after FP
TORBEAM
NEMEC
Definition at line 65 of file CStconfig.h.
Constructor & Destructor Documentation
CStconfig ()
The constructor creates an empty instance of CStconfig.
Definition at line 873 of file CStconfig.h.
References CStconfig::init().
CStconfig (const char * filename)
The constructor creates an instance of CStconfig loading file.
Definition at line 875 of file CStconfig.h.
References CStconfig::init(), CStconfig::loadfile(), and CStconfig::UNDEFINED.
virtual ~CStconfig () [virtual]
The destructor is a virtual method.
Definition at line 877 of file CStconfig.h.
References CStconfig::clear().
Member Function Documentation
CStconfig* clone ()
The method creates a clone of CStconfig using operator new.
The caller is responsible for deleting the clone.
Reimplemented in C3dMesh.
Definition at line 865 of file CStconfig.h.
static const char* getVersion () [static]
The method returns the version of MConf in format year.month.
virtual void clear () [virtual]
The method frees all internal arrays and makes this object empty.
Reimplemented in C3dMesh, and CRayTrace.
Referenced by CStconfig::~CStconfig().
int setRightCoordinateSystem ()
The method reload the current magnetic configuration to the right oriented (s,theta,phi) coordinate system.
int setLeftCoordinateSystem ()
The method reload the current magnetic configuration to the left oriented (s,theta,phi) coordinate system.
int reverseCoordinateSystem ()
The method reload the current magnetic configuration to opposite oriented coordinate system.
int flipZcoordinate ()
The method reload the current magnetic configuration to opposite oriented coordinate system by fliping z-coordinate.
virtual bool load (const char * filename) [virtual]
The method loads the magnetic configuration stored in the file filename.
The method recognizes the format of the file by analyzing its contents; bc-, bc-binary-, LHD- and VMEC(wout, version>=6.20)-format are supported. For bc-format please see W7-X format or ask J.Geiger. The binary-format file is produced by the CStconfig::write() method. Usually you may want to use this format for faster loading of the magnetic configuration; and probably you don't need to know the exact structure of the binary-format file.
Returns:
if the method succeeds, the return value is true; false otherwise.
  #include "CStconfig.h"
  int main() {
    CStconfig mConf;
    mConf.load("w7x-sc1.bc");
    if(!mConf.isOK()) exit(1);   // exit if not OK
    if(!mConf.load("w7x-sc1.bin4")) exit(1); // exit if not OK
    if(!mConf.load("w7x-sc1.bin8")) exit(1); // exit if not OK
  }
Reimplemented in C3dMesh.
Examples:
1stexample.cpp, accuracytest.cpp, raytrace1.cpp, and remesh.cpp.
Definition at line 912 of file CStconfig.h.
References CStconfig::loadfile(), and CStconfig::UNDEFINED.
bool load (const char * filename, long filePosition)
The method loads the magnetic configuration stored in the file filename.
Parameters:
filename is the name of a file to read.
filePosition is the file starting position from which the data will be read, the function fseek(fp,filePosition,SEEK_SET) is used;
Returns:
if the method succeeds, the return value is true; false otherwise.
Note:
file must be in text format.
Definition at line 919 of file CStconfig.h.
References CStconfig::loadfile(), and CStconfig::UNDEFINED.
bool loadEFIT (const char * filename)
The method loads the G EQDSK file and transforms it to the tokamak-symmetry flux coordinates.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 923 of file CStconfig.h.
References CStconfig::EFIT, and CStconfig::loadfile().
bool loadLHD (const char * filename)
The method loads the magnetic configuration with Boozer coordinates from the file in LHD-format.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 927 of file CStconfig.h.
References CStconfig::LHD, and CStconfig::loadfile().
bool loadVMEC (const char * filename)
The method loads the VMEC wout-file.
No transformation to Boozer representation is performed.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 931 of file CStconfig.h.
References CStconfig::loadfile(), and CStconfig::VMEC.
bool loadVMECFP (const char * filename)
The method loads the VMEC netCDF wout-file.
No transformation to Boozer representation is performed.
Returns:
if the method succeeds, the return value is true; false otherwise. The method loads the Vmec Coordinates resulting from FP (function parametrization). No transformation to Boozer representation is performed.
Parameters:
filename is the name of a file.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 942 of file CStconfig.h.
References CStconfig::loadfile(), and CStconfig::NEMEC.
bool loadFromDB (const void * mcdb, int equilibrium_id)
The method loads Boozer coordinates from Magnetic Configuration Data Base.
Parameters:
mcdb -- address of the MCDB control structure, see MCDB documentation
equilibrium_id -- the value of id field from the equilibrium table.
Returns:
if the method succeeds, the return value is true; false otherwise.
bool deleteFromDB (const void * mcdb, int equilibrium_id) const
The method deletes magnetic configuration from database.
Parameters:
mcdb -- address of the MCDB control structure, see MCDB documentation
equilibrium_id -- the value of id field from the equilibrium table.
Returns:
if the method succeeds, the return value is true; false otherwise.
bool writeIntoDB (const void * mcdb, const char * confname, const char * machine_name, int Nsmax, bool magAxis) const
The method inserts magnetic configuration Data into database.
Parameters:
mcdb -- address of the MCDB control structure, see MCDB documentation
confname -- configuration name.
machine_name -- machine name (for example W7-X).
Nsmax -- the number of flux surfaces to save or zero if original number of surfaces is needed to save.
magAxis -- if true then store magnetic axis.
Returns:
if the method succeeds, the return value is true; false otherwise.
bool write (const char * fname) const
Store current magnetic configuration into file.
The format of the file is derived from the file extension. The following file extention are possible:
bc -- write("w.bc"); //save into ascii file, see W7-X format
bin4 -- write("w.bin4"); //save into binary file using float numbers
bin8 -- write("w.bin8"); //save into binary file using double numbers
Parameters:
fname -- filename
Returns:
if the method succeeds, the return value is true; false otherwise.
Attention:
Current truncation level and value of magnetic field are used.
Referenced by MCwrite(), and MCWRITE().
bool writeasciiReduced (const char * fname, int nsmax = 0, double newVolume = 0, double newLastSurface = 1, bool varNumberMods = true, bool magAxis = false, bool circular = false, bool append = false) const
The methods transform the current magnetic configuration to new volume or to new mesh on s.
Parameters:
fname is the filename under which the configuration is saved.
nsmax is the number of surfaces to store, if zero then the original flux surfaces are stored, otherwise store the surfaces using a new mesh which is equidistant on sqrt(s).
newVolume is the new volume if not zero.
newLastSurface if not zero then this is the value of new last-closed-flux-surface in inits of current s, this parameter is used to reduce volume.
varNumberMods if true then variable number of harmonics for each flux surface are stored.
magAxis if true then store magnetic axis.
circular is applicable only for tokamak, if true then only cosine Fourier series for R coordinate and sine Fourier series for Z coordinate are stored.
append if true then append to the file fname .
Returns:
if the method succeeds, the return value is true; false otherwise.
Attention:
Current truncation level and value of magnetic field are used;
Examples:
remesh.cpp.
Referenced by MCSAVEREDUCED(), and MCsetLCMS().
bool writeasciiBmod (const char * fname, double s) const
Write |B|-spectrum on the surface s into file fname.
Returns:
if the method succeeds, the return value is true; false otherwise.
Attention:
Current truncation level and value of magnetic field are used.
bool isOK () const
The method returns true if file is loaded without error.
Examples:
2ndexample.cpp, accuracytest.cpp, eeff_example.cpp, Fbs_example.cpp, Gv_example.cpp, and remesh.cpp.
Definition at line 1000 of file CStconfig.h.
References CStconfig::mOK.
Referenced by MCISOK(), and MCTRACELCMS().
bool isValid () const
Definition at line 1001 of file CStconfig.h.
References CStconfig::mOK.
const char* fname () const
The method returns the name of the file loaded.
Definition at line 1003 of file CStconfig.h.
References CStconfig::mfname.
virtual void setB0 (double B0, double ficyl) [virtual]
Set the value of magnetic field on magnetic axis at given cylindrical angle.
Parameters:
B0 is the value[Tesla] of magnetic field to set
ficyl is the value[radians] of cylindrical angle
Reimplemented in C3dMesh.
Examples:
1stexample.cpp, and accuracytest.cpp.
virtual void setB0 (double B0) [virtual]
Set minimum magnetic field on magnetic axis.
Parameters:
B0 is the value[Tesla] of magnetic field to set
Reimplemented in C3dMesh.
virtual void setB00 (double B00) [virtual]
Set the B00 value of magnetic field on magnetic axis.
Parameters:
B00 is the value[Tesla] of magnetic field to set
Reimplemented in C3dMesh.
virtual void scaleB (double multiplier) [virtual]
Set normalization factor for value of the magnetic field.
Parameters:
multiplier is the scaling factor
Reimplemented in C3dMesh.
virtual void setIcoil (double I) [virtual]
Set the Ipol value of the coil currents at LCMS.
Parameters:
I is the value[Ampers] of the current to set
Reimplemented in C3dMesh.
virtual double getBscaleFactor () [virtual]
Returns:
the absolute value scale factor for B.
Reimplemented in C3dMesh.
double getIcoil ()
Get the minimum value of the magnetic field on axis Get the Ipol value of the coil currents at LCMS.
Returns:
the absolute value of Ipol in Ampers.
virtual void restoreB0 () [virtual]
Restore initial value of the magnetic field(which is stored in a bc-file).
Reimplemented in C3dMesh.
double getB00 ()
Get the B00 value of the magnetic field on axis.
Returns:
the B00 value of the magnetic field on magnetic axis.
Referenced by MCgetB00(), and MCGETB00().
double getB0 ()
Get the minimum value of the magnetic field on axis.
Returns:
the minimum value of the magnetic field on magnetic axis
Referenced by MCgetB0(), and MCGETB0().
double getB0max ()
Get the maximum value of the magnetic field on axis.
Returns:
the maximum value of the magnetic field on magnetic axis
double getB0 (double ficyl)
Get the value of the magnetic field on axis at cylindrical angle ficyl.
Parameters:
ficyl is the value[radians] of cylindrical angle
Returns:
the value of the magnetic field on magnetic axis at cylindrical angle ficyl
int getBdirection ()
The method returns the direction of B with respect to cylindrical angle of the right handed cylindrical coordinate system.
Referenced by MCgetBdirection(), and MCGETBDIRECTION().
void setBdirection (int sign)
The method sets the direction of B with respect to cylindrical angle of the right handed coordinate system.
Parameters:
sign is the positive or negative integer number.
Referenced by MCsetBdirection(), and MCSETBDIRECTION().
void restoreBdirection ()
The method sets the original direction of B with respect to cylindrical angle of the right handed coordinate system.
The original direction is the direction of B stored in the equilibrium file.
Referenced by MCrestoreBdirection(), and MCRESTOREBDIRECTION().
double truncate (double level)
Set truncation level to reduce number of harmonics used in summation.
For each flux surface this method calculates M and N such that Bmn/B00 > level for m<M and |n|<N. Then only harmonics with m<M and |n|<N are used in summation.
Parameters:
level is the new truncation level. The method returns the value of the old truncation level
Examples:
1stexample.cpp, 2ndexample.cpp, accuracytest.cpp, eeff_example.cpp, Fbs_example.cpp, Gv_example.cpp, raytrace1.cpp, and remesh.cpp.
Referenced by MCSAVEREDUCED(), MCtruncate(), and MCTRUNCATE().
double truncate () const
The method returns the current value of truncation level.
Definition at line 1072 of file CStconfig.h.
void setAccuracy (double epsA, double epsR = 1e-5)
Set accuracy of coordinate transformation.
Parameters:
epsA is the absolute accuracy[m] of the transformation from cylindrycal to magnetic coordinates.
epsR is the relative accuracy of the transformation from cylindrycal to magnetic coordinates.
Note:
the default accuracy epsA is 10-5m if this function is not used.
Examples:
1stexample.cpp, 2ndexample.cpp, accuracytest.cpp, and raytrace1.cpp.
Referenced by MCsetAccuracy(), and MCSETACCURACY().
double Z0 () const
The method returns the tokamak magnetic axis position in [m].
Definition at line 1082 of file CStconfig.h.
double R0 () const
The method returns the major radius in [m].
Definition at line 1084 of file CStconfig.h.
Referenced by MCelongation(), and MCR0().
double rminor () const
The method returns the minor radius [m].
Definition at line 1086 of file CStconfig.h.
References CStconfig::r().
Referenced by MCRMINOR().
int Mpol () const
The method returns the number of poloidal harmonics.
Definition at line 1088 of file CStconfig.h.
int Ntor () const
The method returns the number of toroidal harmonics.
Definition at line 1090 of file CStconfig.h.
int MpolMinTruncated () const
The method returns the number of poloidal harmonics after the truncation level was set.
See also:
truncate()
Definition at line 1093 of file CStconfig.h.
int MpolMaxTruncated () const
The method returns the number of poloidal harmonics after the truncation level was set.
See also:
truncate()
Definition at line 1096 of file CStconfig.h.
int NtorMinTruncated () const
The method returns the number of toroidal harmonics after the truncation level was set.
See also:
truncate()
Definition at line 1099 of file CStconfig.h.
int NtorMaxTruncated () const
The method returns the number of toroidal harmonics after the truncation level was set.
See also:
truncate()
Definition at line 1102 of file CStconfig.h.
int nPeriods () const
The method returns the number of periods.
Examples:
accuracytest.cpp, and remesh.cpp.
Definition at line 1104 of file CStconfig.h.
References CStconfig::mNp.
Referenced by MCNPERIODS().
int nSurfaces () const
The method returns the number of flux surfaces used.
The method returns the size of internal arrays CStconfig::ms,CStconfig::miota, CStconfig::mreff, CStconfig::mItor, CStconfig::mIpol, CStconfig::mpprime, see Member Data Documentation here.
Definition at line 1108 of file CStconfig.h.
int nSurfacesInitial () const
The method returns the number of flux surfaces stored in the magnetic configuration file.
Definition at line 1110 of file CStconfig.h.
bool isTokamak () const
The method returns true if the opened file has tokamak symmetry.
Definition at line 1112 of file CStconfig.h.
References CStconfig::tokamakConfig.
bool isTokamakSymmetryFluxCoordinates () const
The method returns true if the opened file is a Tokamak Symmetry Flux Coordinates file.
Definition at line 1114 of file CStconfig.h.
References CStconfig::tokamakSymmetryFluxCoordinates.
Referenced by MCISTOKPEST().
bool isVmecCoordinates () const
The method returns true if the opened file is a VMEC file.
Definition at line 1116 of file CStconfig.h.
References CStconfig::vmecCoordinates.
Referenced by MCISVMEC().
bool isVmecCoordinatesFromFP () const
The method returns true if the opened file is a VMEC file from the Function Parametrization procedure.
Definition at line 1119 of file CStconfig.h.
References CStconfig::fpCoordinates.
int vmecReturnCode () const
The method returns VMEC completion code.
Definition at line 1121 of file CStconfig.h.
double r (double s) const
The method returns the effective radius r=a*sqrt(s), where a is the plasma minor radius defined as sqrt(averageCrossSectionArea(s=1)/pi), this definition of a is used by VMEC code.
Parameters:
s is the normalized toroidal flux.
Returns:
effective radius in [m]
See also:
averageCrossSectionArea()
Examples:
2ndexample.cpp, and raytrace1.cpp.
Referenced by MCelongation(), MCFbs(), MCgradRho2Avrg(), MCgradRhoAvrg(), MCreff(), MCREFF(), and CStconfig::rminor().
double rdkes (double s) const
The method returns the effective radius defined as sqrt(Flux(s)/B00(s)/pi).
This definition (where is the toroidal flux) is used in DKES code.
Returns:
effective radius in [m]
double rdkes2 (double s)
Returns:
effective radius in [m]
double rgraz (double s)
The method returns the minor radius dr=ds/<|grad(s)|> (Graz definition of the radius).
double drgraz_dr (double s)
The method returns dr_graz/dr, where r=a*sqrt(s) is the VMEC definition of minor radius.
double drdkes_dr (double s)
The method returns dr_dkes/dr, where r=a*sqrt(s) is the VMEC definition of minor radius.
double drdkes2_dr (double s)
double epsEffGraz (double s)
The method returns the effective helical ripple for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
V.V.Nemov, S.V.Kasilov, W. Kernbichler, and M.F.Heyn, Physics of Plasmas, vol. 6, 4622(1999), http://link.aip.org/link/PHPAEN/v6/i12/p4622/s1
28th EPS, http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , EGA Vol.25A (2001) 1985-1988
Note:
At first call the method creates a look-up table using multithreading technique to spread callculation among several CPU cores; this table is used for interpolating over the flux surface label.
Use the following methods to set parameters: epsEffSetXeffParam(), epsEffSetTracingParam(), epsEffSetIotaParam(), epsEffSetMagnMomentParam()
Referenced by MCGETEPSEFF().
double epsEffDkes (double s)
The method returns the effective helical ripple for transport, using DKES definition of minor radius r=sqrt(Flux(s)/(pi*B_00(s))), where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
V.V.Nemov, S.V.Kasilov, W. Kernbichler, and M.F.Heyn, Physics of Plasmas, vol. 6, 4622(1999), http://link.aip.org/link/PHPAEN/v6/i12/p4622/s1
28th EPS, http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , EGA Vol.25A (2001) 1985-1988
Note to epsEffGraz()
Referenced by MCGETEPSEFF().
double epsEffVmec (double s)
The method returns the effective helical ripple for transport, using VMEC definition of minor radius r=a*sqrt(s), where s is the normalized toroidal flux.
epsEffVmec^1.5 = epsEffGraz^1.5 * <|grad(s)|>^2 * (r/(2s))^2
Parameters:
s is the normalized toroidal flux.
See also:
V.V.Nemov, S.V.Kasilov, W. Kernbichler, and M.F.Heyn, Physics of Plasmas, vol. 6, 4622(1999), http://link.aip.org/link/PHPAEN/v6/i12/p4622/s1
28th EPS, http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , EGA Vol.25A (2001) 1985-1988
Note to epsEffGraz()
Examples:
eeff_example.cpp.
Referenced by MCepsEff(), and MCGETEPSEFF().
double epsEffNorm (double s)
The method returns the normalized effective helical ripple for transport, using normalized diffusion coefficient.
See also:
28th EPS, http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , EGA Vol.25A (2001) 1985-1988
Parameters:
s is the normalized toroidal flux
See also:
Note to epsEffGraz()
double epsEffHat (double s)
The method returns the effective helical ripple for transport, using definition (2), (5) in http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , 28th EPS, EGA Vol.25A (2001) 1985-1988.
Parameters:
s is the normalized toroidal flux
See also:
Note to epsEffGraz()
double Gw (double s)
eq(21) in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
See also:
Note to epsEffGraz()
Referenced by MCGETGFACTORS().
double Gs (double s)
eq(26) in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
See also:
Note to epsEffGraz()
Referenced by MCGETGFACTORS().
double Gv (double s)
The methods return the bounce-averade gradB drift velocity of trapped particles averaged over flux surface.
See eq(28) in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
See also:
Note to epsEffGraz()
Examples:
Gv_example.cpp.
Referenced by MCGETGFACTORS().
void epsEffSetXeffParam (double xmin = .05, double xmax = .95, int size = 51)
The method sets parameters for calculating eps_eff and Gw, Gs, Gv.
Parameters:
xmin is the minimal value of sqrt(s), where s is the normalized toroidal flux,
xmax is the maximal value of sqrt(s),
size is the number of points for creating look-up table
See also:
Note to epsEffGraz()
Referenced by MCEPSEFFPARAMS().
void epsEffSetTracingParam (int turns = 100, bool doAccuracyTest = true, double dphi = 0.017453)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
Parameters:
turns is the maximal number of toroidal turns for a magnetic field line following,
doAccuracyTest -- if true then integrating along magnetic field line is stopped when relative accuracy is less then 1%
dphi is the toroidal angle step in radian for the magnetic field line following.
See also:
Note to epsEffGraz()
void epsEffSetIotaParam (bool avoidResonances = false, bool useRationalIota = false, int iotaDenominator = 150)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
Parameters:
avoidResonances -- if true then change of flux surface label to avoid iota resonances is attempted,
useRationalIota -- if true then rational iota aproximation is used,
iotaDenominator is the denominator guess for the rational iota aproximation.
See also:
Note to epsEffGraz()
void epsEffSetMagnMomentParam (int nBLevels = 513)
The method sets parameters for calculating the eps_eff and Gw, Gs, Gv.
Parameters:
nBLevels is the number of integration points over magnetic moment, see V.V.Nemov,S.V.Kasilov,W.Kernbichler,M.F.Heyn, Physics of Plasmas, vol.6,4622(1999), http://link.aip.org/link/doi/10.1063/1.873749
See also:
Note to epsEffGraz()
void epsEffCreate ()
The method calculates and stores the eps_eff in the look-up table.
See also:
Note to epsEffGraz()
void epsEffInvalidate ()
The method clears the look-up table with the eps_eff and Gw, Gs, Gv.
void FbsSetSlabelParam (double smin = 0.0025, double smax = 0.9, int size = 101)
The method sets parameters for calculating the bootstrap current geometric factor.
Parameters:
smin is the minimal value of s, where s is the normalized toroidal flux,
smax is the maximal value of s,
size is the number of points for creating look-up table
Referenced by MCFbsSetSlabelParam().
void FbsSetXeffParam (double xmin = .05, double xmax = .95, int size = 101)
The method sets parameters for calculating the bootstrap current geometric factor.
Parameters:
xmin is the minimal value of sqrt(s), where s is the normalized toroidal flux,
xmax is the maximal value of sqrt(s),
size is the number of points for creating look-up table
Referenced by MCFbsSetXeffParam().
void FbsSetTracingParam (int turns = 100, bool doAccuracyTest = true, double dphi = 0.017453)
The method sets parameters for calculating the bootstrap current geometric factor.
Parameters:
turns is the maximal number of toroidal turns for a magnetic field line following,
doAccuracyTest -- if true then integrating along magnetic field line is stopped when relative accuracy is less then 1%
dphi is the toroidal angle step in radian for the magnetic field line following.
Referenced by MCFbsSetTracingParam().
void FbsSetIotaParam (bool avoidResonances = false, bool useRationalIota = false, int iotaDenominator = 150)
The method sets parameters for calculating the bootstrap current geometric factor.
Parameters:
avoidResonances -- if true then change of flux surface label value to avoid iota resonances is attempted,
useRationalIota -- if true then rational iota aproximation is used,
iotaDenominator is the denominator guess for the rational iota aproximation.
Referenced by MCFbsSetIotaParam().
void FbsSetMagnMomentParam (int lambdaLevels = 257, double yMax = 15)
The method sets parameters for calculating the bootstrap current geometric factor.
Parameters:
lambdaLevels is the number of integration points over magnetic moment,
yMax is the new integration limit after variable change from the magnetic moment lambda to y with lambda = tanh(y), see N.Nakajima et al, Nuclear Fusion,29,605(1989), http://dx.doi.org/10.1088/0029-5515/29/4/006
Referenced by MCFbsSetMagnMomentParam().
void FbsCreate ()
The method calculates and stores the bootstrap current geometric factor in the look-up table.
void FbsInvalidate ()
The method clears the look-up table with the bootstrap current geometric factors.
double FbsVmec (double s)
The method returns the bootstrap current geometric factor for transport, using VMEC definition of minor radius r=a*sqrt(s), where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
P.Helander et al,Phys.Plasmas 18,092505(2011), http://link.aip.org/link/doi/10.1063/1.3633940
Note:
At first call the method creates a look-up table using multithreading technique to spread calculation among several CPU cores; this table is used for interpolating over the flux surface label.
Use the following methods to set parameters: FbsSetXeffParam(), FbsSetTracingParam(), FbsSetIotaParam(), FbsSetMagnMomentParam()
Examples:
Fbs_example.cpp.
Referenced by MCFbs(), and MCFbsVmec().
double FbsDkes (double s)
The method returns the bootstrap current geometric factor for transport, using DKES definition of minor radius r=sqrt(Flux(s)/(pi*B_00(s))), where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
Note to FbsVmec()
double FbsGraz (double s)
The method returns the bootstrap current geometric factor for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
Note to FbsVmec()
double GrazLambdab (double s)
The method returns the bootstrap current geometric factor for transport, using Graz definition of the minor radius dr=ds/<|grad(s)|>, where s is the normalized toroidal flux.
See also:
lambda_b in V.Nemov,V.Kalyuzhnyj,S.Kasilov et al,PPCF,46,179(2004), http://dx.doi.org/10.1088/0741-3335/46/1/011
Parameters:
s is the normalized toroidal flux
See also:
Note to FbsVmec()
double FbsFtrap (double s)
double Fbsg2Vmec (double s)
double Fbsg2Dkes (double s)
double Fbsg2Graz (double s)
double Fbsg2 (double s)
The method returns flux surface average of g2, where g2 is defined as B*grad(g2/B^2) = B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
P.Helander et al,Phys.Plasmas 18,092505(2011), http://link.aip.org/link/doi/10.1063/1.3633940
Note:
At first call the method creates a look-up table using multithreading technique to spread calculation among several CPU cores; this table is used for interpolating over the flux surface label.
Use the following methods to set parameters: FbsSetXeffParam(), FbsSetTracingParam(), FbsSetIotaParam(), FbsSetMagnMomentParam()
Referenced by MCFbsg2().
double Fbsu (double s)
The method returns flux surface average of u, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
Referenced by MCFbsu().
double FbsuB2 (double s)
The method returns flux surface average of u*B^2, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
Referenced by MCFbsuB2().
double Fbsu2B2 (double s)
The method returns flux surface average of u^2*B^2, where u is defined as B*grad(u) = -B x grad(s) * grad(1/B^2), s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
Referenced by MCFbsu2B2().
double FbsB2 (double s)
The method returns flux surface average of B^2.
Parameters:
s is the normalized toroidal flux
Referenced by MCFbsB2().
double Fbsg4 (double s, double mu)
The method returns flux surface average of g4, where g4 is defined as B*grad(g4/xi) = B x grad(s) * grad(1/xi) and xi = sqrt(1 - mu*B/Bmax), s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux
See also:
P.Helander et al,Phys.Plasmas 18,092505(2011), http://link.aip.org/link/doi/10.1063/1.3633940
Note:
At first call the method creates a look-up table using multithreading technique to spread calculation among several CPU cores; this table is used for interpolating over the flux surface label.
Use the following methods to set parameters: FbsSetXeffParam(), FbsSetTracingParam(), FbsSetIotaParam(), FbsSetMagnMomentParam()
Referenced by MCFbsg4().
double Fbsg4Vmec (double s, double mu)
Vector3d omega_d_BounceAveraged (const Vector3d & mag0, double dphi = 0.00698, int iotaDenominator = 0)
The method returns bounce average of according formula for elecrons, where , , , is the curvature vector.
Parameters:
mag0 is the magnetic coordinates of the point from which integrating along field line is started and where
dphi is the toroidal step in radians for fild line integration (0.4degree)
iotaDenominator if not zero then this number is the denominator in iota aproximation by rational number.
Returns:
Vector3d with bounce average of in the first element and bounce time in the second element.
std::vector<double> Jinvariant (const Vector3d & mag, double dphi = 0.00698, int iotaDenominator = 0)
The method returns the parallel adiabatic invariant with the integral taken between two turning points according formula .
Parameters:
mag is the magnetic coordinates of the point from which integrating along field line is started and where
dphi is the toroidal step in radians for fild line integration (default value is 0.4 degree)
iotaDenominator if not zero then this number is the denominator in iota aproximation by rational number.
Returns:
std::vector with the parallel adiabatic invariant J , partial derivative dJ/ds , partial derivative dJ/dalpha (alpha=theta/iota - phi) with the bounce time in the fourth element, in the fifth element
See also:
getMagCoordAtB()
Referenced by MCJINVARIANT().
std::vector<double> Jinv_omega_d_BounceAveraged (const Vector3d & mag0, double dphi = 0.00698, int iotaDenominator = 0)
The method returns bounce average of (see omega_d_BounceAveraged()) and the parallel adiabatic invariant with the integral taken between two turning points according formula (see Jinvariant()).
Returns:
std::vector<double> = {J, dJds, dJda, t_bounce, Bma, omegaDaverage} with the parallel adiabatic invariant J , partial derivative dJ/ds , partial derivative dJ/dalpha (alpha=theta/iota - phi) with the bounce time in the fourth element, in the fifth element, and with the bounce average of in the sixth element
See also:
getMagCoordAtB(), omega_d_BounceAveraged(), Jinvariant()
Vector3d getMagCoordAtB (const Vector3d & mag, double Bt)
The method returns the magnetic coordinates of the point (that belongs to the given field line) at which the magnetic field is equal to the given value.
Parameters:
mag defines the field line;
Bt is the magnetic field value, must be within the interval Bmin..Bmax for the considered field line;
Returns:
Vector3d with the magnetic coordinates at which the magnetic field value is Bt or Vector3d with (-1,Bmin,Bmax) if Bt is not within the interval Bmin..Bmax;
Note:
the method seaches the point of interest starting from the point where B=Bmin, Bmin is seached within one machine period: 0<=phi<2*pi/Np
See also:
Jinvariant(), Bmin(double s), Bmax(double s)
Referenced by MCGETMAGCOORDATB().
std::vector<Vector3d> getAllMagCoordAtB (const Vector3d & mag0, double Bt)
Vector3d getNextMagCoordAtB (const Vector3d & mag0, double Bt)
double GradsAvrg (double s)
The method returns <|grad(s)|> .
Referenced by MCgradRhoAvrg(), and MCgradsAvrg().
double Grads2Avrg (double s)
The method returns <(grad(s))^2> .
Referenced by MCgradRho2Avrg(), and MCgrads2Avrg().
double Grads2overB2Avrg (double s)
The method returns <(grad(s)/B)^2> .
double sPol (double s)
The method returns the normalized poloidal flux, where s is the normalized toroidal flux.
Referenced by MCtorFlux2polFlux(), and MCTORFLUX2POLFLUX().
double PoloidalFlux (double s)
The method returns the poloidal flux, where s is the normalized toroidal flux.
Referenced by MCPoloidalFlux().
double sToroidal (double sPoloidal)
The method returns the normalized toroidal flux, where s is the normalized poloidal flux.
Referenced by MCsToroidal().
double iota (double s) const
The method returns the iota, where s is the normalized toroidal flux.
Examples:
raytrace1.cpp.
Referenced by CStconfig::getSignOfCurrentThatIncreasesAbsIota(), MCiota(), and MCIOTA().
double pressure (double s) const
The method returns the pressure in Pa, where s is the normalized toroidal flux.
Referenced by MCPRESSURE().
double iotaRational (double s, int denom_guess, int & numerator, int & denominator)
The method returns rational aproximation to iota: iota = numerator/denominator.
Parameters:
[in] s is the normalized toroidal flux.
[in] denom_guess is the guess value for the denominator.
[out] numerator is the numerator.
[out] denominator is the denominator.
Returns:
iota = numerator/double(denominator).
double iotaPrime (double s) const
The method returns the diota/ds, where s is the normalized toroidal flux.
Parameters:
s is the normalized toroidal flux.
Referenced by MCiotaPrime(), and MCIOTAPRIME().
double Ip (double s) const
The method returns the poloidal current in [A].
Parameters:
s is the normalized toroidal flux.
Referenced by CStconfig::getSignOfCurrentThatIncreasesAbsIota(), MCBPHI(), MCIp(), MCIPOL(), and MCRHPOTENCIAL().
double It (double s) const
The method returns the toroidal current in [A].
Parameters:
s is the normalized toroidal flux.
Referenced by MCIt(), and MCITOR().
double Flux (double s) const
The method returns the toroidal flux in [Wb].
Parameters:
s is the normalized toroidal flux.
Referenced by MCFlux(), MCGETBANDGRADIENTS(), MCGETBCURLBGRADFCYL(), and MCTORFLUX().
double pp (double s)
The method returns dp/ds [Pa], where p is the pressure in [Pa].
Parameters:
s is the normalized toroidal flux.
Referenced by MCPRESSUREPRIME().
double crossSectionArea (double s, double ficyl)
The method returns the area of the cross section of the surface s at angle fi.
Parameters:
s is the normalized toroidal flux
ficyl is the cylindrical angle in radians
Returns:
area in [m]
double averageCrossSectionArea (double s = 1.)
The method returns the average area of the cross section of the surface s.
Parameters:
s is the normalized toroidal flux.
Returns:
average area in [m]
Referenced by MCAVERAGECROSSSECTIONAREA().
double Volume (double s)
The method returns Volume in [m3] inside surface s.
Volume is negative if (s,theta,phi)-coordinate system is left handed
Parameters:
s is the normalized toroidal flux.
Returns:
Volume in [m3]
Examples:
2ndexample.cpp.
Referenced by MCVolume(), and MCVOLUME().
double Vprime (double s) const
The method returns Vprime=dVolume/ds in [m3].
Vprime is negative if (s,theta,phi)-coordinate system is left handed
Parameters:
s is the normalized toroidal flux.
Referenced by MCVprime(), and MCVPRIME().
double VprimeIntJ (double s, int nth = 120, int nph = 120)
The method calculates dVolume/ds in [m^3], integrating the Jacobian.
Simpson method is used.
Parameters:
s is the flux label - the normalized toroidal flux.
nth specifies the number of points for poloidal integration.
nph specifies the number of points for toroidal integration.
Returns:
dVolume/ds in [m3]
Note:
this function is intended for testing of method Vprime(s); normally it's better to use Vprime(s). dVolume/ds is negative if (s,theta,phi)-coordinate system is left handed
Vector3d* SMatrix (double s, int npol = 180, int ntor = 200)
The method calculates the Susceptance matrix in (Flux,theta,phi)-coordinates.
See definition of the Susceptance matrix in P.I.Strand,W.A.Houlberg, Physics of Plasmas, 8, 2782(2001)
Parameters:
s is the normalized toroidal flux, s = Flux/Flux_max
npol specifies the number of points for poloidal integration.
ntor specifies the number of points for toroidal integration.
Returns:
Susceptance matrix Sij, see example:
 #include "CStconfig.h"
 int main() {
   CStconfig mConf;
   if(!mConf.load("w7x-sc1.bc")) exit(1);
   Vector3d *S = mConf.SMatrix(0.5,200,200);
   double S12 =  S[1][2];
 }
Note:
The Susceptance matrix in (s,theta,phi)-coordinates can be expressed through relation S_ij(Flux,theta,phi)=S_ij(s,theta,phi)* dFlux/ds
The method is obsolete, use it for testing only. See S11(), S12(), S21(), S22() for faster and better alternative.
double S11 (double s)
Susceptance matrix: S11 in (Flux,theta,phi)-coordinates.
The method calculates the Susceptance matrix in (Flux,theta,phi)-coordinates. See definition of the Susceptance matrix in P.I.Strand,W.A.Houlberg, Physics of Plasmas, 8, 2782(2001)
Parameters:
s is the normalized toroidal flux, s = Flux/Flux_max
Returns:
S11 element of susceptance matrix.
Referenced by MCS11().
double S12 (double s)
Susceptance matrix: S12 in (Flux,theta,phi)-coordinates.
Parameters:
s is the normalized toroidal flux, s = Flux/Flux_max
Returns:
S12 element of susceptance matrix.
Referenced by MCS12().
double S21 (double s)
Susceptance matrix: S21 in (Flux,theta,phi)-coordinates.
Referenced by MCS21().
double S22 (double s)
Susceptance matrix: S22 in (Flux,theta,phi)-coordinates.
Referenced by MCS22().
Vector3d curvatureAvrg (double s, int nth = 120, int nph = 120)
The method calculates the flux average of normal and geodesic curvatures.
Parameters:
s is the normalized toroidal flux.
nth specifies the number of points for poloidal integration.
nph specifies the number of points for toroidal integration.
Returns:
Vector3d k with k[0] = <|kN|> and k[1] = <|kG|>, see example:
 #include "CStconfig.h"
 int main() {
   CStconfig mConf;
   if(!mConf.load("w7x-sc1.bc")) exit(1);
   Vector3d k = mConf.curvatureAvrg(0.5,200,200);
   double kN =  k[0];
   double kG =  k[1];
 }
void findBminBmaxPosition (double s, Vector3d & magcrdBmin, Vector3d & magcrdBmax, bool useInputAsGuess = false)
The method returns the position of Bmax on the surface s.
double Bmin (double s)
The method returns the minimum value of magnetic field on the surface s.
Referenced by MCBMIN(), MCGETBMINMAX(), and MCGETBMINMAXGLOBAL().
double Bmax (double s)
The method returns the maximum value of magnetic field on the surface s.
Referenced by MCBmax(), MCBMAX(), MCGETBMINMAX(), and MCGETBMINMAXGLOBAL().
double Bmin ()
The method returns the minimum value of magnetic field.
double Bmax ()
The method returns the maximum value of magnetic field.
double Bavrg (double s)
The method returns the <B> -- flux average of magnetic field on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCBAVRG().
double B2avrg (double s)
The method returns the <B2> -- flux average of magnetic field on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCB2AVRG().
double B2VolAvrg ()
The method returns the volume average of B2.
double B_2avrg (double s)
The method returns the <B-2> -- flux average of magnetic field on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCB_2AVRG(), and MCRHPOTENCIAL().
double grads2B_2avrg (double s)
The method returns the <grads^2*B^-2> -- flux average on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCGRADS2B_2AVRG().
double R2avrg (double s)
The method returns the <R2> -- flux average of R^2 on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCR2AVRG(), and MCRHPOTENCIAL().
double R_2avrg (double s)
The method returns the <R-2> -- flux average of R^-2 on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCR_2AVRG().
double NeoPolarizationPass (double s)
The method returns the contribution of passed particles to the neoclassical polarization on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCNEOPOLARIZATIONPASS().
double NeoPolarizationTrap (double s)
The method returns the contribution of traped particles to the neoclassical polarization on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCNEOPOLARIZATIONTRAP().
double NeoPolarization (double s)
The method returns the neoclassical polarization on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCNEOPOLARIZATION(), and MCRHPOTENCIAL().
double db12Avrg (double s)
The method returns the value of <(1-b)0.5>, where b=B(s,th,ph)/Bmax(s).
Parameters:
s is the normalized toroidal flux.
Referenced by MCBDB12AVRG(), and MCDB12AVRG().
double db32Avrg (double s)
The method returns the value of <(1-b)1.5>, where b=B(s,th,ph)/Bmax(s).
Parameters:
s is the normalized toroidal flux.
Referenced by MCBDB12AVRG(), and MCDB32AVRG().
double ftrapped (double s)
The method returns the fraction of trapped particles on the surface s.
Parameters:
s is the normalized toroidal flux.
Referenced by MCftrapped(), and MCFTRAPPED().
double roParInvAvrg (double s, double x) const
Referenced by MCROPARINVAVRG().
double pavrg (double s, double x) const
The method returns the <p> -- flux average of pitch angle on the surface s.
The method returns the value of function P(s,x) = <sqrt(1-x*B(s,th,ph)/Bmax(s))>, where 0<=x<=1, 0<=s<=1, and definition of x is the following x=(1-p^2)/b, p is the pitch angle, b=B(s,th,ph)/Bmax(s).
Referenced by MCPAVRG().
double integralInvPavrg (double s, double x) const
The method returns the Integral(from x to 1) dx'/P(s,x') on the surface s.
The method returns the Integral(from x to 1) dx'/P(s,x'), where P(s,x) = <sqrt(1-x*B(s,th,ph)/Bmax(s))>,
Referenced by MCINTINVPAVRG().
void getBminmax (double s, double & Bmin, double & Bmax, int npol = 120, int ntor = 120)
The method returns Bmin and Bmax -- the minimum and maximum values of magnetic field on the surface s.
Parameters:
s is the flux surface label, 0<=s<=1.
Bmin is the reference for returned value of Bmin.
Bmax is the reference for returned value of Bmax.
npol specifies the number of points in poloidal direction, which are used for finding of minimum and maximum.
ntor specifies the number of points in toroidal direction, which are used for finding of minimum and maximum.
Returns:
Bmin,Bmax -- the minimum and maximum values of magnetic field on the surface s.
Note:
this function is intended for testing of methods Bmin() and Bmax(); normally it's better to use Bmin() or Bmax().
void getFtrappedBminmax (double s, double & Ftrapped, double & Bmin, double & Bmax, double & Bavr, double & B2avr, int nth = 120, int nph = 120)
The method returns the fraction of trapped particles on the surface s.
Parameters:
s is the flux surface label, 0<=s<=1.
Ftrapped is the reference for returned value of the trapped particles fraction.
Bmin is the reference for returned value of Bmin.
Bmax is the reference for returned value of Bmax.
Bavr is the flux average B on the surface s.
B2avr is the flux average B^2 on the surface s.
nth specifies the number of points in poloidal direction, which are used for integration (surface averaging).
nph specifies the number of points in toroidal direction, which are used for integration.
Returns:
Ftrapped -- the fraction of trapped particles on the surface s.
Bmin,Bmax -- the minimum and maximum values of magnetic field on the surface s.
Bavr,B2avr -- are the flux average B and B^2 on the surface s.
Note:
this function is intended for internal use and testing of method ftrapped(); normally it's better to use ftrapped(),Bmin(),Bmax(),Bavrg(),B2avrg().
double Bmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of |B|-expansion.
Cubic spline interpolation is used.
Parameters:
s is the flux surface label, 0<=s<=1.
m is the poloidal mode number, 0<=m<= Mpol().
n is the toroidal mode number. |n|<=Ntor().
Returns:
Fourier coefficient.
Note:
extrapolation to s>1 is possible, but is not reliable for big s.
Referenced by MCBMN().
double Rmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of R-expansion, for parameters see Bmn_sp().
Referenced by MCRMN().
double Zmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of Z-expansion, for parameters see Bmn_sp().
Referenced by MCZMN().
double Phimn_sp (double s, int m, int n) const
The method returns Fourier coefficient of Phi-expansion, for parameters see Bmn_sp().
Referenced by MCFMN().
double lmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of VMEC lambda expansion, for parameters see Bmn_sp().
double gmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of VMEC Jacobian expansion, for parameters see Bmn_sp().
double BcontrPolmn_sp (double s, int m, int n) const
The method returns Fourier coefficient of expansion of poloidal contravariant B, for parameters see Bmn_sp().
double BcontrTormn_sp (double s, int m, int n) const
The method returns Fourier coefficient of expansion of toroidal contravariant B, for parameters see Bmn_sp().
double Bmn_sp_prime (double s, int m, int n) const
double Boozer2Bmn (double s, int m, int n)
double BoozerBmn (double s, int m, int n)
Referenced by MCBoozerBmn(), MCBOOZERBMN(), and MCelongation().
double get_s (int is) const
The method returns flux surface label s(norm.tor.flux).
Parameters:
is is the flux surface number, 0<=is< nSurfaces().
Definition at line 1653 of file CStconfig.h.
double get1st_s () const
The method returns the s value of the first surface stored in a file.
Definition at line 1655 of file CStconfig.h.
double getLast_s () const
The method returns the s value of the last surface stored in a file.
Definition at line 1657 of file CStconfig.h.
int getIdx1st_s () const
The method returns the index of the first flux surface in array CStconfig::ms.
The first surface means here the first surface stored in a file.
Definition at line 1660 of file CStconfig.h.
int getIdxLst_s () const
The method returns the index of the last flux surface in array CStconfig::ms.
The last surface means here the last surface stored in a file.
Definition at line 1663 of file CStconfig.h.
int SearchSindx (double s, bool halfMesh = true) const
The method returns the index in array CStconfig::ms, which corresponds to s.
The left index of segment ms[i] - ms[i+1] in which s lies is returned.
double B (const Vector3d & magCoord) const
The function returns B=sum_mn B_mn(s)*cos(m*theta-n*Np*phi).
Parameters:
magCoord is the vector with magnetic coordinates (s,theta,phi).
Examples:
remesh.cpp.
Referenced by MCB().
double BonFieldLine (const Vector3d & magCoord0, double phi)
The method returns |B| on the field line that passes through the point given by (s0,theta0,phi0).
Parameters:
[in] magCoord0 is the point of B-line in magnetic coordinates
[in] phi is the toroidal angle
Returns:
B(s0,theta(phi),phi)
See also:
magCoordFieldLine()
Vector3d magCoordFieldLine (const Vector3d & magCoord0, double phi, double iota = 0)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,phi0).
The method calculates function
where is non zero for VMEC coordinates.
Parameters:
magCoord0 is the point of B-line in magnetic coordinates
phi is the toroidal angle
iota is the rational approximation to the iota, the genuine iota is used if this parameter is zero.
Returns:
Vector3d(s0,theta(phi),phi)
Vector3d mixCoordFieldLine (const Vector3d & mixCoord0, double fcyl)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,ficyl0).
The method calculates function
where is non zero for VMEC coordinates.
Parameters:
mixCoord0 is the point of B-line in mixed coordinates, where s, theta coincide with correspondent magnetic coordinates, but toroidal angle is cylindricyl angle
fcyl is the cylindricyl angle
Returns:
Vector3d(s0,theta(ficyl),phi(ficyl))
Note:
for VMEC coordinats this method is the same as magCoordFieldLine()
Referenced by MCCOORDFIELDLINE().
Vector3d gradB (const Vector3d & magCoord)
The method returns grad(|B|).
Parameters:
magCoord is the magnetic coordinates
Returns:
grad(|B|) in cylindrical coordinates
Referenced by MCGETGRADB().
Vector3d getCovaGradB (const Vector3d & magCoord) const
The method returns covariant components of grad(|B|).
Parameters:
magCoord is the magnetic coordinates
Returns:
Vector3d with covariant components of grad(|B|), Vector3d(dB/ds,dB/dtheta,dB/dphi)
Referenced by MCGETCOVAGRADB().
void getBandGradients (const Vector3d & u, Vector3d & B, Vector3d & gradB, Vector3d & grads, Vector3d & gradTh, Vector3d & gradPh)
The method returns B and gradients in cylindrical coordinates.
Parameters:
[in] u is the point (s,theta,phi) in magnetic coordinates,
[out] B is the magnetic field in cylindrical coordinates,
[out] gradB is the grad(|B|),
[out] grads is the grad(s),
[out] gradTh is the grad(theta),
[out] gradPh is the grad(phi),
Referenced by MCGETBANDGRADIENTS().
void getBandGradientsxyz (const Vector3d & u, Vector3d & B, Vector3d & gradB, Vector3d & grads, Vector3d & gradTh, Vector3d & gradPh)
Get B and gradients in cartesian coordinates.
Parameters:
[in] Vector3d u(s,theta,phi) is a point in magnetic coordinates,
[out] B is the magnetic field in cartesian coordinates
[out] gradB is the grad(|B|) in cartesian coordinates
[out] grads is the grad(s)
[out] gradTh is the grad(theta)
[out] gradPh is the grad(phi)
Referenced by MCgetBandGradientsxyz().
void getBandBasisVectorsxyz (const Vector3d & u, Vector3d & xyz, Vector3d & Bxyz, Vector3d & gradBxyz, Vector3d & e1con, Vector3d & e2con, Vector3d & e3con, Vector3d & e1cov, Vector3d & e2cov, Vector3d & e3cov)
Get B and basis vectors in cartesian coordinates.
Parameters:
[in] u = (s,theta,phi) is the point magnetic-coordinates,
[out] xyz is the point cartesian-coordinates,
[out] Bxyz is the magnetic field in cartesian coordinates
[out] gradBxyz is the grad(|B|) in cartesian coordinates
[out] e1con,e2con,e3con are the contravariant-basis vectors e^i = grad(u^i) in cartesian coordinates
[out] e1cov,e2cov,e3cov are the covariant-basis vectors e_i = dX/du^i in cartesian coordinates
Referenced by MCgetBandBasisVectorsxyz().
double getdBGradscyl (const Vector3d & cyl, Vector3d & B, Vector3d & dBdr, Vector3d & dBdfir, Vector3d & dBdz, Vector3d & grads)
Returns:
s
Referenced by MCGETDBCYL().
double getdBGradsxyz (const Vector3d & xyz, Vector3d & B, Vector3d & dBdx, Vector3d & dBdy, Vector3d & dBdz, Vector3d & grads)
Returns:
s
Referenced by MCGETALLXYZ(), and MCgetdB_Gradsxyz().
Vector3d getBcurlBGradscyl (const Vector3d & u, Vector3d & B, Vector3d & curlB, Vector3d & grads)
The method returns B and curl(B) in cylindrical coordinates.
Parameters:
[in] u is the point (s,theta,phi) in magnetic coordinates,
[out] B is the magnetic field in cylindrical coordinates,
[out] curlB is the curl(B),
[out] grads is the grad(s)
Returns:
cylindrical coordinates of the point (s,theta,phi)
Referenced by MCGETBCURLBGRADFCYL().
double getLocalShear (const Vector3d & magCrd, Vector3d & B, Vector3d & cyl, Vector3d & grads)
The method returns the local shear.
Parameters:
[in] Vector3d magCoord(s,theta,phi) is a point in magnetic coordinates,
Returns:
local_shear = -H*curl(H), where H = grad(s)/abs(grad(s) ^ B/abs(B), ^ is the cross product
cyl, B, grads in cylindrical coordinates
Referenced by MCgetLocalShear().
double getLocalShear (const Vector3d & magCrd)
void useMixedProductForJacobian (bool sw)
If sw==true then the method forces to use Jacobian=dX/dFlux*(dX/dtheta^dX/dphi) for calculating B field.
Referenced by MCuseMixedProductForJacobian(), and MCUSEMIXEDPRODUCTFORJACOBIAN().
double Jacobian (const Vector3d & magCoord, double * Bmod = 0) const
Jacobian: dV = Jacobian(s,theta,phi)*ds*dtheta*dphi.
Parameters:
magCoord is the vector with magnetic coordinates (s,theta,phi).
Returns:
the value of Jacobian at the point (s,theta,phi)
Parameters:
[out] *Bmod is the B(s,theta,phi) if Bmod is not NULL
Note:
Jacobian in coordinates (s,theta,phi)
Boozer Jacobian = FluxTor'*mu0*(Ip*Np+iota*It)/B^2/twopi^2)
Tokamak Jacobian = FluxTor'*R*R/(mu0*Ipol)
Vmec Jacobian = Sum gmn*cos(....)
Jacobian has sign
Examples:
remesh.cpp.
Referenced by MCBANDJACOBIAN(), MCJacobian(), and MCJACOBIAN().
Vector3d mag2xyz (const Vector3d & magCoord) const
The method returns the cartesian coordinates of the point.
Parameters:
magCoord is the Vector3d(s,theta,phi) in magnetic coordinates
Returns:
cartesian coordinates.
Examples:
remesh.cpp.
Referenced by MCmag2xyz(), and MCMAG2XYZ().
Vector3d mag2xyz (double s, double theta, double phi) const
The method makes transformation from magnetic coordinates to cartesian.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters:
s,theta,phi are the magnetic coordinates.
Returns:
cartesian coordinates.
Vector3d mag2cyl (const Vector3d & magCoord) const
The method makes transformation from magnetic coordinates to cylindrical.
Parameters:
magCoord is the Vector3d(s,theta,phi) in magnetic coordinates
Returns:
cylindrical coordinates.
Examples:
accuracytest.cpp.
Referenced by MCMAG2CYL().
Vector3d mag2cyl (double s, double theta, double phi) const
The method makes transformation from magnetic coordinates to cylindrical.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters:
s,theta,phi are the magnetic coordinates.
Returns:
cylindrical coordinates.
Vector3d mixcoord2cyl (double s, double theta, double fi, double * phi = 0, sumDat * sdat = 0) const
The method returns cylindrical coordinates which correspond to the mixed coordinates.
Parameters:
s is the flux surface label
theta is the magnetic poloidal angle.
fi is the cylindrical angle.
Returns:
cylindrical coordinates.
Parameters:
[out] phi if not NULL then this address at return will contain the magnetic toroidal angle.
[in] sdat for internal use only.
Referenced by CStconfig::Axiscyl(), MCMIXCOORD2CYL(), and MCRAXIS().
Vector3d mixcoord2cyl (const Vector3d & mixcoord, double * phi = NULL) const
The method returns cylindrical coordinates which correspond to the mixed coordinates.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters:
mixcoord are the mixed coordinates.
phi if not NULL then this address at return will contain the magnetic toroidal angle.
Vector3d mixcoord2xyz (const Vector3d & mixcoord, double * phi = NULL) const
The method returns cartesian coordinates which correspond to the mixed coordinates.
Parameters:
mixcoord are the mixed coordinates.
Returns:
cartesian coordinates.
Parameters:
phi if not NULL then this address at return will contain the magnetic toroidal angle.
Referenced by MCmix2xyz(), and MCMIXCOORD2XYZ().
Vector3d Axiscyl (double ficyl) const
The method returns cylindrical coordinates of the magnetic axis.
Parameters:
ficyl is the value of cylindrical angle in radians.
Returns:
cylindrical coordinates of the magnetic axis.
Definition at line 1824 of file CStconfig.h.
References CStconfig::mixcoord2cyl().
void useVmecLambdaOn ()
The method forces to use the stream function lambda for B-field calculatioins, the method works only for VMEC representation, otherwise it does nothing.
Definition at line 1830 of file CStconfig.h.
void useVmecLambdaOff ()
The method forces to use the VMEC contravariant B in B-field calculatioins, the method works only for VMEC representation, otherwise it does nothing.
Definition at line 1835 of file CStconfig.h.
References CStconfig::vmecCoordinates.
Vector3d* NJacobian (const Vector3d & magCoord)
The method calculates Jacobian matrix for Newton's iteration.
Parameters:
magCoord is the vector with magnetic coordinates (s,theta,phi).
Returns:
pointer to the array J of 4 vectors calculated in the point magCoord
   (R )(Rs )(Rt )(Rp )           (R )       (Rs )
J= (fi)(fis)(fit)(fip), i.e J[0]=(fi), J[1]=(fis), ...
   (Z )(Zs )(Zt )(Zp )           (Z )       (Zs )
  where (R,fi,Z) is the corresponding point
  in cylindrical coordinates;
  Rs  = dR/ds,  Rt  = dR/dtheta,  Rp  = dR/dphi;
  fis = dfi/ds, fit = dfi/dtheta, fip = dfi/dphi;
Note:
Along with the Jacobian matrix calculation the method calculates other quantities, which are available through methods: getmodB(), getJac(), getJac2(), getJ(), getJ2(), getBxyz(), getBcyl(), getGradFlux(), getGrads(), getGradreff(),getMetricTensor().
Referenced by MCGETBCYL().
Vector3d* NJacobianL (const Vector3d & magCoord)
The method calculates Jacobian matrix for Newton's iteration using linear interpolation on s.
see CStconfig::NJacobian
Note:
Don't use this method, it is needed only for testing.
Vector3d cyl2mag (const Vector3d & cyl)
The method makes transformation from cylindrical to magnetic coordinates.
The method uses Newton's iteration to find magnetic coordinates, the guess value is estimated by CStconfig::cyl2guess or is taken from previous call.
Parameters:
cyl is the cylindrical coordinates
Returns:
magnetic coordinates.
Note:
After calling this function the other quantities are available through methods: getmodB(), getJac(), getJac2(), getJ(), getJ2(), getBxyz(), getBcyl(), getGradPsi(), getGrads(), getGradreff().
Examples:
2ndexample.cpp, and accuracytest.cpp.
Referenced by CStconfig::cyl2s(), MCCYL2MAG(), and MCCYL2MAG2().
Vector3d cyl2mag (const Vector3d & cyl, const Vector3d & magCoordGuess)
The method makes transformation from cylindrical to magnetic coordinates using guess value.
Parameters:
cyl is the cylindrical coordinates
magCoordGuess is the guess value
Returns:
magnetic coordinates.
Note:
After calling this function the other quantities are available through methods: getmodB(), getJac(), getJac2(), getJ(), getJ2(), getBxyz(), getBcyl(), getGradPsi(), getGrads(), getGradreff().
This method is obsolete, use cyl2mag(const Vector3d &cyl)
Vector3d xyz2mag (const Vector3d & xyz)
The method makes transformation from cartesian to magnetic coordinates.
The method uses Newton's iteration to find magnetic coordinates; the guess value is estimated by CStconfig::cyl2guess or is taken from previous call.
Parameters:
xyz is the cartesian coordinates
Returns:
magnetic coordinates.
Note:
After calling this function the other quantities are available through methods: getmodB(), getJac(), getJac2(), getJ(), getJ2(), getBxyz(), getBcyl(), getGradPsi(), getGrads(), getGradreff().
Examples:
raytrace1.cpp.
Referenced by MCxyz2mag(), MCXYZ2MAG2(), and CStconfig::xyz2s().
double cyl2s (const Vector3d & cyl)
The method finds the flux label s which corresponds to the point in space.
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest.
Returns:
flux label s.
Examples:
1stexample.cpp.
Definition at line 1892 of file CStconfig.h.
References CStconfig::cyl2mag().
Referenced by MCCYL2S(), MCGETSBCYL(), and MCM3DGETSBCYL().
double xyz2s (const Vector3d & xyz)
The method finds the flux label s which corresponds to the point in space.
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest.
Returns:
flux label s.
Definition at line 1896 of file CStconfig.h.
References CStconfig::xyz2mag().
Referenced by MCgetBxyz(), MCgetGradBxyz(), MCGETGRADSXYZ(), MCGETSBXYZ(), MCxyz2s(), and MCXYZ2S().
Vector3d cyl2guess (const Vector3d & cyl, double eps, double smax = 1, bool * inside = 0)
The method makes transformation from cylindrical to magnetic coordinates using 2d-iteration on R-Z plane.
The algorithm is robust and rather fast, use it for getting the guess value for the Newton method implemented in cyl2mag().
Parameters:
[in] cyl is the cylindrical coordinates
[in] eps is the relative accuracy of the transformation, use eps ~ 0.06 (for W7-X plasma, 0.06 is 3cm/50cm) if you need only guess for Newton method, use eps ~ 0.001 if you need exact coordinate transformation.
[in] smax is the value of the 'extra' surface beyond LCMS, use smax <= 1.2
[out] inside is the address of the flag that is true if cyl is inside smax.
Returns:
magnetic coordinates.
Note:
the quantities getmodB(), getJac(), getJac2(), getJ(), getJ2(), getBxyz(), getBcyl(), getGradPsi(), getGrads(), getGradreff() are not available after calling this function. Call NJacobian() in oder to calculate these quantities.
double getmodB () const
The method returns |B|.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
double getmodB (const Vector3d & cyl)
The method returns |B|.
double getJac () const
The method returns Jacobian=mu0*(Ipol+iota*Itor)/(4pi2B2).
Jacobian for coordinates (Flux,theta,phi)
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
double getJac (const Vector3d & cyl)
The method returns Jacobian=mu0*(Ipol+iota*Itor)/(4pi2B2).
double getJ () const
The method returns Jacobian=Flux(1)*mu0*(Ipol+iota*Itor)/(4pi2B2).
Jacobian for coordinates (s,theta,phi)
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
double getJ (const Vector3d & cyl)
Jacobian for coordinates (s,theta,phi).
double getJac2 () const
The method returns Jacobian=dX/dFlux*(dX/dtheta^dX/dphi).
Jacobian for coordinates (Flux,theta,phi)
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
double getJac2 (const Vector3d & cyl)
The method returns Jacobian=dX/dFlux*(dX/dtheta^dX/dphi).
Jacobian for coordinates (Flux,theta,phi)
double getJ2 () const
The method returns Jacobian=dX/ds*(dX/dtheta^dX/dphi).
Jacobian for coordinates (s,theta,phi)
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
double getJ2 (const Vector3d & cyl)
The method returns Jacobian=dX/ds*(dX/dtheta^dX/dphi).
Jacobian for coordinates (s,theta,phi)
const Vector3d& getBxyz ()
The method returns cartesian B-vector.
Note:
Use this function after calling NJacobian(),cyl2mag(),or xyz2mag().
See also:
NJacobian().
Referenced by MCgetBxyz(), MCGETSBXYZ(), and MCXYZ2MAG2().
const Vector3d& getBxyz (const Vector3d & xyz)
The method returns cartesian B-vector at cartesian point xyz.
const Vector3d& getBcyl () const
The method returns cylindrical B-vector.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
Examples:
2ndexample.cpp, and raytrace1.cpp.
Referenced by MCCYL2MAG(), MCCYL2MAG2(), MCGETBCYL(), and MCGETSBCYL().
const Vector3d& getBcyl (const Vector3d & cyl)
The method returns cylindrical B-vector.
const Vector3d& getGradtheta () const
The method returns cylindrical vector grad(theta).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGradtheta (const Vector3d & cyl)
The method returns cylindrical vector grad(theta).
Vector3d getGradlambda (const Vector3d & cyl)
The method returns cylindrical vector grad(lambda) for VMEC coordinates, where lambda is the stream function.
Vector3d getGradlambda () const
The method returns cylindrical vector grad(lambda) for VMEC coordinates, where lambda is the stream function.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGradphi () const
The method returns cylindrical vector grad(phi).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGradphi (const Vector3d & cyl)
The method returns cylindrical vector grad(phi).
const Vector3d& getGradFlux () const
The method returns cylindrical vector grad(Flux).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGradFlux (const Vector3d & cyl)
The method returns cylindrical vector grad(Flux).
const Vector3d& getGrads () const
The method returns cylindrical vector grad(s).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGrads (const Vector3d & cyl)
The method returns cylindrical vector grad(s).
Vector3d getGradsxyz () const
The method returns cartesian vector grad(s).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
Referenced by MCGETGRADSXYZ().
Vector3d getGradsxyz (const Vector3d & xyz)
The method returns cartesian vector grad(s).
const Vector3d& getGradreff () const
The method returns cylindrical vector grad(reff).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getGradreff (const Vector3d & cyl)
The method returns cylindrical vector grad(reff).
const Vector3d* getNJmatrix ()
The method retuns pointer to the Jacobian matrix for Newton's iteration calculated by CStconfig::NJacobian().
This matrix is calculated during coordinate transformation inside following functions: cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
CStconfig::NJacobian()
const Vector3d* getNJmatrix (const Vector3d & cyl)
The method retuns pointer to the Jacobian matrix for Newton's iteration calculated by CStconfig::NJacobian() for point cyl.
const Vector3d* getMetricTensor ()
The method retuns pointer to the MetricTensor calculated by CStconfig::NJacobian.
This tensor is for coordinates(s,theta,phi) and calculated also during coordinate transformation inside following functions: cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
CStconfig::NJacobian
Returns:
metric tensor gij, where i=(0,1,2)=(s,theta,phi) see example:
 #include "CStconfig.h"
 int main() {
   CStconfig mConf;
   if(!mConf.load("w7x-sc1.bc")) exit(1);
   Vector3d magCoord(0.5,1.,2.); // magnetic coordinates
   mConf.NJacobian(magCoord);
   Vector3d *g = mConf.getMetricTensor();
   double g12 =  g[1][2];  // g_theta,phi
 }
const Vector3d* getMetricTensor (const Vector3d & cyl)
The method returns pointer to the metricTensor calculated in the point cyl.
Returns:
metric tensor gij, where i=(0,1,2)=(s,theta,phi) see example:
 #include "CStconfig.h"
 int main() {
   CStconfig mConf;
   if(!mConf.load("w7x-sc1.bc")) exit(1);
   Vector3d cyl(5.5,2.,0.5); // cylindrical coordinates
   Vector3d *g = mConf.getMetricTensor(cyl);
   double g12 =  g[1][2];    // g_theta,phi
 }
Vector3d getRcyl () const
The method returns the cylindrical coordinates of the last point used in coordinate transformation.
See also:
cyl2mag() or xyz2mag()
Vector3d getRxyz () const
The method returns the cartesian coordinates of the last point used in coordinate transformation.
See also:
cyl2mag() or xyz2mag()
const Vector3d& getBcova () const
The method returns covariant components of B = (B_s,B_theta,B_phi) in (s,theta,phi) coordinates.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
const Vector3d& getBcontra () const
The method returns contravariant components of B = (0,B^theta,B^phi).
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
void getCovaBasis (Vector3d & e1, Vector3d & e2, Vector3d & e3) const
The method returns covariant-basis vectors e_i = dX/du^i in cylindrical coordinates.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
void getContraBasis (Vector3d & e1, Vector3d & e2, Vector3d & e3) const
The method returns contravariant-basis vectors e^i = grad(u^i) in cylindrical coordinates.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
Vector3d getGradBcyl ()
The method returns grad(|B|) in cylindrical coordinates.
Returns:
grad(|B|) in cylindrical coordinates.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
Vector3d getGradBcyl (const Vector3d & cyl)
The method returns grad(|B|) in cylindrical coordinates.
Parameters:
cyl is the point in cylindrical coordinates
Returns:
grad(|B|) in cylindrical coordinates.
Vector3d getGradBxyz ()
The method returns grad(|B|) in cartesian coordinates.
Returns:
grad(|B|) in cartesian coordinates.
Note:
Use this function after calling NJacobian(),cyl2mag(),xyz2mag(),cyl2s(),xyz2s().
See also:
NJacobian().
Referenced by MCgetGradBxyz().
Vector3d getGradBxyz (const Vector3d & xyz)
The method returns grad(|B|) in cartesian coordinates.
Parameters:
xyz is the point in cartesian coordinates.
Returns:
grad(|B|) in cartesian coordinates.
Vector3d Vmec2Pest (const Vector3d & vmec)
VMEC coordinates vmecCoord=(s,theta,phi).
Returns:
PEST coordinates The method transforms the VMEC coordinates to PEST. Transformation formulas
Parameters:
vmec is the VMEC coordinates (s,theta_v,phi)
Returns:
PEST coordinates (s,theta_pest,phi)
Note:
the input file must be the VMEC file
See also:
PEST coordinates
Referenced by MCVMEC2PEST().
Vector3d Pest2Vmec (const Vector3d & pest)
Referenced by MCPEST2VMEC().
Vector3d SFLcoordOnBlineAtTheta (const Vector3d & pest0, double theta, double iotA = 0)
Referenced by MCSFLCOORDONBLINEATTHETA().
void SFLcontraBasis (const Vector3d & pest, Vector3d & e1, Vector3d & e2, Vector3d & e3, Vector3d & vmec)
Referenced by MCSFLCONTRABASIS().
void BoozerContraBasis (const Vector3d & booz, Vector3d & e1, Vector3d & e2, Vector3d & e3, Vector3d & vmec)
Referenced by MCBOOZERCONTRABASIS().
void Vmec2PestContraBasis (const Vector3d & vmec, Vector3d & e1, Vector3d & e2, Vector3d & e3, Vector3d & pest)
Vector3d Vmec2Boozer (const Vector3d & vmecCoord)
The method transforms the VMEC coordinates to Boozer.
Transformation formulas
Parameters:
vmecCoord is the VMEC coordinates (s,theta_v,phi_v)
Returns:
Boozer coordinates (s,theta_B,phi_B)
Note:
the input file must be the VMEC file
See also:
Transformation from VMEC to Boozer Coordinates
Referenced by MCVMEC2BOOZER().
Vector3d Boozer2Vmec (const Vector3d & boozer)
The method transforms the Boozer coordinates to VMEC.
Transformation formulas
Parameters:
boozer is the Boozer coordinates (s,theta_B,phi_B)
Returns:
VMEC coordinates (s,theta_v,phi_v)
Note:
the input file must be the VMEC file
See also:
Transformation from VMEC to Boozer Coordinates
Referenced by MCBOOZER2VMEC().
bool writeVmec2Boozer (const char * fname, int method = 0, int M = 0, int N = 0)
The method transforms the VMEC wout-file to Boozer-coordinate data file.
Parameters:
fname is the filename under which the configuration is saved.
method if 0 then Boozer spectrum are obtained by integrating over Boozer angles, otherwise the integrations over VMEC angles are performed; the method 0 is faster, because summation (numerical integration) is performed using FFT;
M is the number of poloidal mods, if M==0 then the number of Fourier mods is three times of that of VMEC expansion;
N is the number of toroidal mods, if M==0 then the number of Fourier mods is three times of that of VMEC expansion:
Returns:
if the method succeeds, the return value is true; false otherwise.
 #include "CStconfig.h"
 int main() {
   MConf::CStconfig mConf;
   if(!mConf.load("wout.w7x-sc1.txt")) exit(1);
   mConf.writeVmec2Boozer("w7x-sc1.bc");
 }
See also:
Transformation from VMEC to Boozer Coordinates
double Vmec2BoozerTest (const Vector3d & vmecCoord)
The method peforms test, that d(theta_booz,phi_booz)/d(theta_vmec,phi_vmec) == (Jacobian_vmec/Jacobian_booz).
Parameters:
vmecCoord is the VMEC coordinates (s,theta_v,phi_v)
Returns:
ratio { d(theta_booz,phi_booz)/d(theta_vmec,phi_vmec) } / (Jacobian_vmec/Jacobian_booz)
bool cylIsInside (const Vector3d & cyl, double * distance = 0) const
The method tests whether the point lies inside LCMS.
Parameters:
cyl -- cylindrical coordinates of the point.
distance if not NULL then this address at return will contain the distance between cyl and the LCMS, distanse<0 if the point lies inside LCMS.
Returns:
the return value is true if the point lies inside LCMS; false otherwise.
Examples:
2ndexample.cpp.
Referenced by MCCYL2MAG(), and MCCYLISINSIDE().
bool xyzIsInside (const Vector3d & xyz, double * distance = 0) const
The method tests whether the point lies inside LCMS.
Parameters:
xyz -- cartesian coordinates of the point.
distance if not NULL then this address at return will contain the distance between xyz and the LCMS, distanse<0 if the point lies inside LCMS.
Returns:
the return value is true if the point lies inside LCMS; false otherwise.
Referenced by MCTRACELCMS(), and MCXYZISINSIDE().
bool cylIsInsideBorder (const Vector3d & cyl, double * distance = 0, Vector3d * point = 0, Vector3d * magCoord = 0) const
The method tests whether the point lies inside the given border.
Parameters:
cyl -- cylindrical coordinates of the point.
distance if not NULL then this address at return will contain the distance between cyl and the border, distanse<0 if the point lies inside the border.
point if not NULL then this address at return will contain the cylindrical coordinates of nearest point on the border.
magCoord if not NULL then this address at return will contain the magnetic coordinates of nearest point on the border.
Returns:
true if the point lies inside the border; false otherwise.
Note:
createBorder() method must be called before using this method.
Referenced by MCISINSIDEBORDER().
bool createBorder (double s, double ficyl, int borderSize = 150)
The method creates the border -- 's'-contour at cylindrical angle 'ficyl'.
Parameters:
s is the value of flux label
ficyl is the cylindrical angle
borderSize is the number of point in contour
Returns:
false if no memory
Referenced by MCCREATEBORDER().
int getBorderSize ()
The method returns the number of points in the border created by createBorder() method.
Definition at line 2202 of file CStconfig.h.
References CArray1d< TV >::size().
const Vector3d& getBorder (int k) const
The method returns the cylindrical cooordinates of the k-point of the border.
The border is created by createBorder() method and 0<=k<getBorderSize().
Definition at line 2206 of file CStconfig.h.
const Vector3d& getBorderMag (int k) const
The method returns the magnetic cooordinates of the k-point of the border.
The border is created by createBorder() method and 0<=k<getBorderSize().
Definition at line 2210 of file CStconfig.h.
const double& getBorderRmin () const
The method returns the min value of R-cooordinate of the border.
Definition at line 2212 of file CStconfig.h.
const double& getBorderRmax () const
The method returns the max value of R-cooordinate of the border.
Definition at line 2214 of file CStconfig.h.
const double& getBorderZmin () const
Definition at line 2215 of file CStconfig.h.
const double& getBorderZmax () const
Definition at line 2216 of file CStconfig.h.
bool getRayEntryPoint (const Vector3d & r0, const Vector3d & rd, Vector3d & entryPoint)
The method traces the Last Closed Magnetic Surface (LCMS).
The method finds the first intersection of the ray with the LCMS, where the ray is R(t)=r0+rd*t, and t>=0.
Parameters:
r0 is the Cartesian coordinates of the ray origin, must be outside with respect to the LCMS,
rd is the direction of the ray in Cartesian coordinates,
entryPoint this vector at return contains the Cartesian coordinates of the ray entry point into the plasma,
Returns:
if the method succeeds, the return value is true; false otherwise.
bool getRayIntersectionPoints (const Vector3d & r0, const Vector3d & rd, Vector3d & entryPoint, Vector3d & exitPoint)
The method traces the Last Closed Magnetic Surface (LCMS).
The method finds intersections of the ray with the LCMS, where the ray is R(t)=r0+rd*t, and t>=0.
Parameters:
r0 is the Cartesian coordinates of the ray origin, must be outside with respect to the LCMS,
rd is the direction of the ray in Cartesian coordinates,
entryPoint this vector at return contains the Cartesian coordinates of the ray entry point into the plasma,
exitPoint this vector at return contains the Cartesian coordinates of the ray exit point from the plasma,
Returns:
if the method succeeds, the return value is true; false otherwise.
Referenced by MCgetRayIntersectionPoints().
Vector3d xyzAtB (double Bres, const Vector3d & r0, const Vector3d & rd, const Vector3d & entryPoint)
void getCoeffForAstraCode (double sqrts, double & r, double & gradr2, double & J, double & G2, double & hV, double & B0, double & R0, double & h)
Referenced by MCgetCoeffForAstraCode().
void zeroStatistics ()
Clear statistics.
Examples:
accuracytest.cpp.
int& nJac ()
The method returns the number of NJacobian calls.
Note:
for benchmarking and timing.
Definition at line 2257 of file CStconfig.h.
References CStconfig::mNjac.
int& n2mag ()
The method returns the number of coordinate transformations from real space to magnetic coordinates.
Note:
for benchmarking and timing.
Examples:
accuracytest.cpp.
Definition at line 2260 of file CStconfig.h.
References CStconfig::mNcyl2mag.
double MAverage () const
The method returns the average number of poloidal harmonics used in summation during coordinate transformations from real space to magnetic coordinates.
Note:
for benchmarking and timing.
Examples:
accuracytest.cpp.
double NAverage () const
The method returns the average number of toroidal harmonics used in summation during coordinate transformations from real space to magnetic coordinates.
Note:
for benchmarking and timing.
Examples:
accuracytest.cpp.
double NNjacCalls () const
The method returns the number of NJacobian calls.
Note:
for benchmarking and timing.
Examples:
accuracytest.cpp.
double Nmag2cylCalls () const
The method returns the number of mag2cyl calls.
Note:
for benchmarking and timing.
double Ncyl2magCalls () const
The method returns the number of cyl2mag calls.
Note:
for benchmarking and timing.
double NGuessCalls () const
double phimag (double s, double theta, double ficyl) const
The method returns the magnetic toroidal angle which corresponds to the mixed coordinates.
Parameters:
s is the flux surface label
theta is the magnetic poloidal angle.
ficyl is the cylindrical angle.
Returns:
magnetic toroidal angle.
double phimag (const Vector3d & mixcoord) const
The method returns the magnetic toroidal angle which corresponds to the mixed coordinates.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters:
mixcoord is the Vector3d(s,theta,ficyl), see phimag(double s,double theta,double ficyl)
Returns:
magnetic toroidal angle.
void getExtent (double & Rmin, double & Rmax, double & Zmin, double & Zmax, double s, double fi) const
The method returns the sizes of a rectangle circumscribed about the cross section of the surface s at cylindrical angle fi.
Referenced by MCGETEXTENT().
void getExtent (double & Rmin, double & Rmax, double & Zmin, double & Zmax, double s) const
The method returns the sizes of a rectangle circumscribed about the cross section of the surface s.
void getExtentLCMS (double & Rmin, double & Rmax, double & Zmin, double & Zmax) const
The method returns the sizes of a rectangle circumscribed about the cross section of the LCMS.
Referenced by MCGETEXTENTLCMS().
void getExtent (Vector3d & rmin, Vector3d & rmax, double s, double f1, double f2) const
The method returns the sizes of parallelepiped circumscribed about the segment f1-f2<pi of the 's' surface, 'f' is the cylindrical angle.
int getJacobianSign ()
The method returns the sign of the Jacobian calculating the mixed product dX/ds*(dX/dtheta^dX/dphi).
Where ^ is a cross product signs,and the (s,theta,phi) are the magnetic coordinates: (flux label, poloidal, and toroidal angles); X is the cartesian vector.
int getThetaDirection ()
The method returns the direction of the poloidal angle.
Plus sign corresponds to counterclockwise direction on the R-Z plane when looking on it in fi-direction,where fi is the cylindrical angle. Plus sign also means that increasing theta increases angle = atan((Z(theta)-Zaxis)/(R(theta)-Raxis)).
int getPhiDirection ()
The method returns the direction of the toroidal angle.
Plus sign corresponds to the direction on the cylindrical angle.
int getSignOfCurrentThatIncreasesAbsIota () const
The method returns the direction of the toroidal current j^phi (in the right-handed cylindrical coordinates system), that increases the absolute value of the iota.
Returns:
1 or -1 depending on the direction of the toroidal current.
Definition at line 2320 of file CStconfig.h.
References CStconfig::iota(), and CStconfig::Ip().
Referenced by MCCURRENTSIGNTOINCREASEIOTA().
int getDeltaIotaSign (double Itor) const
The method returns the sign of iota increment due to non-inductive current <j*B>/<|B|>.
Parameters:
Itor is the current that is equal to integral_0^r <j*B>/<|B|> *(2*pi*R0)^-1 *dV
Returns:
1 or -1 depending on sign of the iota increment; 0 if current is zero.
Definition at line 2324 of file CStconfig.h.
const CArray2d<Vector3d>* LCMS ()
The method returns the pointer to the 2d-array of vertexes of LCMS.
Returns:
the pointer to the 2d-array of vertexes of LCMS, the vertexes are in cartesian coordinates.
const CArray2d<Vector3d>* BLCMS ()
The method returns the pointer to the 2d-array of the magnetic field value at the LCMS.
double mod2pi (double x) const
The method reduces x to the interval 0..2pi.
Examples:
accuracytest.cpp.
Definition at line 2341 of file CStconfig.h.
Referenced by MCISINSIDEBORDER().
double mod2piNoWrap (double x) const
The method reduces x to the interval 0.
.2pi. if 0=<x<=twopi then x is returned, otherwise (x<0)?(fmod(x,twopi)+twopi):fmod(x,twopi)
Definition at line 2345 of file CStconfig.h.
References CStconfig::twopi.
double modPeriod (double x) const
The method reduces x to the interval 0..2pi/mNp, where mNp is the number of stellarator periods.
Definition at line 2358 of file CStconfig.h.
References CStconfig::mPeriod.
void sortAngles (double & f1, double & f2) const
The method sorts angles, so that f1<f2 and f2-f1<pi.
bool createSurface (double s, int nTheta, int nPhi, CArray2d< Vector3d > & vertex, CArray2d< Vector3d > * Bfld = 0, bool cylPhi = true)
The method creates array of vertexes of the surface s.
void createNormals (const CArray2d< Vector3d > & Vertexes, CArray2d< Vector3d > & normals, int sign = 1) const
The method creates array of normals to the surface Vertexes.
Parameters:
Vertexes -- array of vertexes of a surface.
sign -- direction of normals
normals -- array of normals
Returns:
normals -- array of normals
Vector3d curvature (const Vector3d & magCoord)
The method calculates curvature at given point.
Parameters:
magCoord is the magnetic coordinates of the point of interest.
Returns:
Vector3d with component:
[0] - normal curvature
[1] - geodesic curvature
[2] - Jacobian in coordinates (s,theta,phi)
bool loadfile (const char * filename, fileFormat t, long fPostn = 0) [protected]
helper function for CStconfig::load()
Returns:
if the method succeeds, the return value is true; false otherwise.
Referenced by CStconfig::CStconfig(), CStconfig::load(), CStconfig::loadEFIT(), CStconfig::loadLHD(), CStconfig::loadVMEC(), and CStconfig::loadVMECFP().
bool loadEfitAndScale (const char * fname, double scaleBpol = 0, double scaleBtor = 0, int signBpol = 0, int signBtor = 0, int signQ = 0, int psiOverTwopi = 0)
The method loads the G EQDSK file and transforms it to the tokamak-symmetry flux coordinates.
Parameters:
[in] fname is the name of the file to load.
[in] scaleBpol is the scale factor for the poloidal field.
[in] scaleBtor is the scale factor for the toroidal field.
Returns:
if the function succeeds, the return value is non-zero, zero otherwise.
See also:
loadEfit_p()
Definition at line 2540 of file CStconfig.h.
Referenced by MCloadEQDSK().
bool loadTokamak (const CStconfig * mconf)
The method creates the circular tokamak with the same R0, a, and iota as in the mconf.
Returns:
if the method succeeds, the return value is true; false otherwise.
bool loadTopfile (const char * fname) [protected]
The method loads torbeam equilibria file.
helper function for CStconfig::load(), not implemented yet.
Returns:
if the method succeeds, the return value is true; false otherwise.
Definition at line 2550 of file CStconfig.h.
References CStconfig::mOK.
void adjustNumbersForSimpson (int & Npol, int & Ntor, double & dpol, double & dtor) const [protected]
Adjust number of integration points and steps.
void calculateCurrents () [protected]
The method calculates currents and dV/ds if needed.
void calculateVprime () [protected]
The method calculates dV/ds and then Volume integrating Jacobian.
void calculateFluxAverages1 (int npol = 180, int ntor = 200) [protected]
void calculateSMatrixArrays (int npol = 180, int ntor = 200) [protected]
The method tabulate arrays for finding Sij(s).
Note:
This method is obsolete.
void ajustFourierCoeffMeshes () [protected]
ajust Fourier coefficients and create radial meshes
void addSurfacesNearAxis () [protected]
The method adds surfaces near magnetic axis and calculates spline coefficients.
void addSurfacesAfterLCMS () [protected]
void createSplineCoeff () [protected]
int getSsegMN (double s, int & M, int & N) const [protected]
The method searches nearest to s segment in array ms.
Returns:
nearest to 's' index in array 'ms' and numbers of poloidal M and toroidal N harmonics for this surface. M, N are based on truncation level, see truncate(double level)
double VolumeInt (double s) const [protected]
The method returns the Volume inside surface s integrating Jacobian.
The Volume is negative if (s,theta,phi)-coordinate system is left handed.
double VolumeInt (double s1, double s2) const [protected]
The method returns the volume between surfaces s1 and s2 integrating Jacobian.
bool createLCMS () [protected]
The method creates array of vertexes of LCMS.
void signOfJacobianAndAngles () [protected]
The method calculates the sign of Jacobian and angle directions.
double FluxPoloidal (double s1, double s2) const [protected]
The method is used to create flux label based on normalized poloidal flux.
void init () [protected]
init everything before loading magnetic configuration
Referenced by CStconfig::CStconfig().
void clearImportantFlags () [protected]
the method is called when the configuration is reloaded to another coordinate system (L.H.S.
to/from R.H.S)
void freeConf () [protected]
Free all memory used.
void writeIdentificationComment (FILE * fp) const [protected]
write identification and comments into bc-file.
int getSignOfBnormFactor () const [protected]
return the sign of B-normalization factor
bool writebin (const char * fname, T szType, FILE * ff = NULL) const [protected]
helper function for write(), see also C3dMesh::writeMeshbin();
bool writebin4 (const char * fname, FILE * ff) const [protected]
helper function for write(), see also C3dMesh::writeMeshbin();
bool writebin8 (const char * fname, FILE * ff) const [protected]
helper function for write(), see also C3dMesh::writeMeshbin();
bool loadbin (const char * fname, T szType, FILE * ff = NULL) [protected]
helper function for load(), see also C3dMesh::loadMeshbin();
bool loadbin4 (const char * fname, FILE * ff) [protected]
helper function for load(), see also C3dMesh::loadMeshbin();
bool loadbin8 (const char * fname, FILE * ff) [protected]
helper function for load(), see also C3dMesh::loadMeshbin();
bool initAfterLoad (fileFormat fmt = UNDEFINED) [protected]
calculate spline coeffitients and add surfaces near axis.
int isInsideTriangle (const Vector3d * r, const Vector3d & n, Vector3d & ri) const [protected]
test whether point ri lies inside triangle r
int isTriangleHitted (const Vector3d * r, const Vector3d & rayR0) const [protected]
const char* fname_ext (const char * buf) const [protected]
Returns a pointer to the last period in buf.
const char* fname_name (const char * name) const [protected]
returns a pointer to the filename, or null if name ends with '/'
bool cylIsInsideEx (const Vector3d & cyl, const CArray2d< Vector3d > & vertex, double dFi, double * distance) const [protected]
The method tests whether the point lies inside LCMS.
Parameters:
cyl -- cylindrical coordinates of the point, fi=cyl[1] must be given on a period.
vertex
dFi -- toroidal angle step, which was used for tabulating array vertex
distance if not NULL then this address at return will contain the distance between cyl and the LCMS.
Returns:
the return value is true if the point lies inside LCMS; false otherwise.
void Swap (T & v1, T & v2) const [protected]
Definition at line 2848 of file CStconfig.h.
void SwapN (T & v1, T & v2) const [protected]
Definition at line 2849 of file CStconfig.h.
T square (const T x) const [protected]
Definition at line 2850 of file CStconfig.h.
T cube (const T x) const [protected]
Definition at line 2851 of file CStconfig.h.
T mmin (T x, T y) const [protected]
Definition at line 2852 of file CStconfig.h.
T mmax (T x, T y) const [protected]
Definition at line 2853 of file CStconfig.h.
T abs (T x) const [protected]
Definition at line 2854 of file CStconfig.h.
Referenced by CStconfig::setSign().
T setSign (T target, T sign) const [protected]
Definition at line 2855 of file CStconfig.h.
References CStconfig::abs().
int sign (T x) const [protected]
Definition at line 2856 of file CStconfig.h.
double mantissa (T x) [protected]
Definition at line 2857 of file CStconfig.h.
static double Heaviside (double x) [static, protected]
Definition at line 2860 of file CStconfig.h.
Referenced by CStconfig::smoothHeaviside().
double smoothHeaviside (double x, double w = 1) [protected]
Definition at line 2866 of file CStconfig.h.
References CStconfig::Heaviside().
Friends And Related Function Documentation
friend class sumDat [friend]
Definition at line 96 of file CStconfig.h.
friend class __lcms [friend]
Definition at line 99 of file CStconfig.h.
friend class __averagedData [friend]
Definition at line 376 of file CStconfig.h.
friend class __spline [friend]
Definition at line 564 of file CStconfig.h.
Member Data Documentation
bool mOK [protected]
result of the last operation
Definition at line 696 of file CStconfig.h.
Referenced by CStconfig::isOK(), CStconfig::isValid(), and CStconfig::loadTopfile().
std::string mfname [protected]
name of the file, that was read
Definition at line 697 of file CStconfig.h.
Referenced by CStconfig::fname().
double pi [protected]
= 3.14159265358979
Definition at line 698 of file CStconfig.h.
double twopi [protected]
Definition at line 699 of file CStconfig.h.
Referenced by CStconfig::mod2piNoWrap().
double twopiinv [protected]
Definition at line 700 of file CStconfig.h.
double degree [protected]
= pi/180;
Definition at line 701 of file CStconfig.h.
double mu0 [protected]
= pi*4e-7 [N/A^2 = henry/m]
Definition at line 702 of file CStconfig.h.
int mNp [protected]
number of periods
Definition at line 703 of file CStconfig.h.
Referenced by CStconfig::nPeriods().
double mPeriod [protected]
twopi/mNp
Definition at line 704 of file CStconfig.h.
Referenced by CStconfig::modPeriod().
double mepsA [protected]
Definition at line 705 of file CStconfig.h.
double mepsR [protected]
absolute and relative accuracy of coordinate transformation
Definition at line 705 of file CStconfig.h.
bool jacobianIsMixedProduct [protected]
Definition at line 2791 of file CStconfig.h.
bool Averages1Ready [protected]
Definition at line 2792 of file CStconfig.h.
bool ftrappedReady [protected]
Definition at line 2793 of file CStconfig.h.
bool BminmaxReady [protected]
Definition at line 2794 of file CStconfig.h.
bool SMatrixReady [protected]
Definition at line 2795 of file CStconfig.h.
bool tokamakSymmetryFluxCoordinates [protected]
Definition at line 2796 of file CStconfig.h.
Referenced by CStconfig::isTokamakSymmetryFluxCoordinates().
bool vmecCoordinates [protected]
VMEC Coordinates if true.
Definition at line 2797 of file CStconfig.h.
Referenced by CStconfig::isVmecCoordinates(), and CStconfig::useVmecLambdaOff().
bool vmecAsym [protected]
VMEC additional fourier coefficients in asymmetrical mode if true.
Definition at line 2798 of file CStconfig.h.
bool fpCoordinates [protected]
VMEC Coordinates from FP if true.
Definition at line 2799 of file CStconfig.h.
Referenced by CStconfig::isVmecCoordinatesFromFP().
bool fpCoordinates2 [protected]
Definition at line 2800 of file CStconfig.h.
bool fpCoordinates5 [protected]
Definition at line 2801 of file CStconfig.h.
bool tokamakEQDSK [protected]
same as tokamakSymmetryFluxCoordinates
Definition at line 2802 of file CStconfig.h.
bool tokamakConfig [protected]
mN==0 && mNp==1
Definition at line 2803 of file CStconfig.h.
Referenced by CStconfig::isTokamak().
bool polCurrentNeeded [protected]
signal to load() function that currents must be calculated
Definition at line 2804 of file CStconfig.h.
bool torCurrentNeeded [protected]
signal to load() function that currents must be calculated
Definition at line 2805 of file CStconfig.h.
bool vprimeNeeded [protected]
signal to load() function that dV/ds must be calculated
Definition at line 2806 of file CStconfig.h.
The documentation for this class was generated from the following file:
CStconfig.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik