MConf: rkf45 Class Reference
rkf45 Class Reference
Fehlberg fourth-fifth order Runge-Kutta method.
#include <rkf45.h>
Public Member Functions
rkf45 ()
rkf45 (RightHandSide *rhs, int neqn, double atol=ATOL, double rtol=RTOL)
void init (RightHandSide *rhs, int neqn, double atol=ATOL, double rtol=RTOL)
void init ()
virtual ~rkf45 ()
void advance (double *u, double &t, double tout)
Detailed Description
Fehlberg fourth-fifth order Runge-Kutta method.
Definition at line 21 of file rkf45.h.
Constructor & Destructor Documentation
rkf45 ()
Definition at line 24 of file rkf45.h.
References rkf45::init().
rkf45 (RightHandSide * rhs, int neqn, double atol = ATOL, double rtol = RTOL)
Definition at line 25 of file rkf45.h.
References rkf45::init().
virtual ~rkf45 () [virtual]
Definition at line 42 of file rkf45.h.
Member Function Documentation
void init (RightHandSide * rhs, int neqn, double atol = ATOL, double rtol = RTOL)
Definition at line 28 of file rkf45.h.
Referenced by CBtrace< Bfield >::CBtrace(), and CBtrace< Bfield >::init().
void init ()
Definition at line 39 of file rkf45.h.
Referenced by rkf45::rkf45().
void advance (double * u, double & t, double tout)
Definition at line 45 of file rkf45.h.
Referenced by CBtrace< Bfield >::advance(), and CBtrace< Bfield >::advancePoloidally().
The documentation for this class was generated from the following file:
rkf45.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik