MConf: ngArray< T > Class Template Reference
ngArray< T > Class Template Reference
Array of objects.
#include <ngarray.h>
Classes
struct Rep
Protected class holds data.
Public Member Functions
ngArray ()
Create ngArray.
ngArray (size_t size, const T &val=T())
Create and initialize ngArray.
ngArray (int min, int max, const T &val=T())
Create and initialize ngArray. This creates a new ngArray and fills all elements with a constant value. If you don't specify a fill value, the default constructor for that type is called.
virtual ~ngArray ()
Destructor.
ngArray (const ngArray &that)
Copy constructor.
ngArray & operator= (const ngArray &that)
Assignment operator.
T & operator[] (int i)
Gives access to element i,.
T & wd (int i)
Gives direct access to element i, copy on write is not performed.
const T & operator[] (int i) const
Returns a constant reference to the element at i.
void clear ()
clear the array
void init (size_t size, const T &val=T())
reshape and initialize the array
void init (int min, int max, const T &val=T())
reshape and initialize the array
virtual void fill (const T &val)
initialize all elements with a constant value.
size_t size () const
Returns actual array size.
int minIdx () const
return the minimum index. This function returns the minimum valid index to the array. If the array is empty, this value is INT_MAX.
int maxIdx () const
return the maximum index. This function returns the maximum valid index to the array. If the array is empty, the value INT_MAX-1 is returned - just to make constructs like
bool empty () const
return whether the array is empty
T * array ()
Returns memory pointer.
const T * constArray () const
returns constant pointer to the elements
Protected Member Functions
void detach ()
Protected Attributes
Rep * p
Detailed Description
template<typename T>
class MConf::pBase::ngArray< T >
Array of objects.
This template class is a generic array container for object of type T. The objects stored should meet the requirements that usual containers oppose to them. They must have a default constructor, a copy operator and copy constructor. Furthermore, it is required that the objects are capable of writing and reading themselves to and from a stream using the usual indirection operators << and >>.
A great difference from normal C/C++ array types is that this class has an arbitrary index for the first element. Where a normal C/C++ array type has it's indices always starting at zero, you can construct or initialize a ngArray with an arbitrary start index. Using zero-based indices is supported and as easy as usual. Examples:
    pBase::ngArray<double> a(-10, 10)   // valid indices range from -10 to 10, size() = 21
    pBase::ngArray<double> b(20, 30)    // valid indices range from 20 to 30, size() = 11
    a.init(0, 9);                       // valid indices range from 0 to 9, size() = 10
    b.init(10);                         // same as above, but easier and more intuitive
This class uses implicit data sharing, it is not expensive to copy it or pass it around as argument. Writing to the array may, however, take some time because the data is automatically copied if it is shared between different instances.
To reshape or resize the array, the init() function is supplied. Note that this will destroy the data stored. The array will be initialized with the new dimensions provided. When an array created or reshaped, all elements are initialized with a default value. You may pass the initialization value in the constructor or init() function.
Note:
If you create a ngArray<T> where T is an integer type, you should avoid passing the initialization value. Use fill() instead to initialize the array. This is because the compiler can't destinguish between ngArray<T>::init(size, init) and ngArray<T>::init(minIdx, maxIdx).
If you create a ngArray<double>, you should explicitely convert the initialization value to a double when calling the constructors and init() functions. See the following example for explanation.
    int someVal = 1;
    ...
    ngArray<double> a(size, someVal);               // will use ngArray<double>::ngArray<double>(int, int, const double & = double())
    ngArray<double> b(size, 1);                     // will use ngArray<double>::ngArray<double>(int, int, const double & = double())
    ngArray<double> c(size, double(someVal));       // correct
Author:
Stefan Zegenhagen, Andreas Werner
Definition at line 81 of file ngarray.h.
Constructor & Destructor Documentation
ngArray ()
Create ngArray.
Generates a new empty ngArray. If you try to access any element of this array, you will probably get a segmentation fault.
Definition at line 89 of file ngarray.h.
ngArray (size_t size, const T & val = T())
Create and initialize ngArray.
This creates a new ngArray with valid indices ranging from 0 to size - 1 and fills all elements with a constant value. If you don't specify a fill value, the default constructor for that type is called.
Definition at line 99 of file ngarray.h.
ngArray (int min, int max, const T & val = T())
Create and initialize ngArray. This creates a new ngArray and fills all elements with a constant value. If you don't specify a fill value, the default constructor for that type is called.
Definition at line 109 of file ngarray.h.
virtual ~ngArray () [virtual]
Destructor.
Definition at line 116 of file ngarray.h.
ngArray (const ngArray< T > & that)
Copy constructor.
Definition at line 121 of file ngarray.h.
Member Function Documentation
ngArray& operator= (const ngArray< T > & that)
Assignment operator.
Definition at line 127 of file ngarray.h.
T& operator[] (int i)
Gives access to element i,.
Returns a reference of the element at i for reading and writing. i should be limited to min ... max, otherwise it is made to fit into that range.
Note:
You should check that the array is not empty. Accessing elements from an empty ngArray will cause a segmentation fault.
This operator may take some time to return the element. It may be necessary to copy the whole array.
Reimplemented in CArray3d< TV >, CArray3d< double >, CArray3d< char >, and CArray3d< Vector3d >.
Definition at line 146 of file ngarray.h.
T& wd (int i)
Gives direct access to element i, copy on write is not performed.
Returns a reference of the element at i for reading and writing. i should be limited to min ... max, otherwise it is made to fit into that range.
Note:
You should check that the array is not empty. Accessing elements from an empty ngArray will cause a segmentation fault.
This method doesn't detach this object memory from clones, all ngArray clones will see changes after assignment A.wd(i) = x, i.e.: ngArray A,B; A.init(10,1); // all A elements are 1 B = A; A.wd(1) = 10; // B[1] will be also 10; compare with T & operator[] (int i)
Definition at line 167 of file ngarray.h.
const T& operator[] (int i) const
Returns a constant reference to the element at i.
The function returns a constant reference to the element at i. i should be limited to min ... max, otherwise it is made to fit into that range.
Note:
You should check that the array is not empty. Accessing elements from an empty ngArray will cause a segmentation fault.
This operator usually returns quite fast, no copying will be performed.
Reimplemented in CArray1d< TV >, CArray2d< TV >, CArray3d< TV >, CArray1d< double >, CArray1d< CComplex >, CArray1d< int >, CArray1d< Vector3d >, CArray2d< double >, CArray2d< Vector3d >, CArray3d< double >, CArray3d< char >, and CArray3d< Vector3d >.
Definition at line 182 of file ngarray.h.
void clear ()
clear the array
This function will clear the array. Afterwards, you can't access any element or you might get a segmentation fault.
Note:
All stored data will be forgotten.
Reimplemented in CArray1d< TV >, CArray2d< TV >, CArray3d< TV >, CArray1d< double >, CArray1d< CComplex >, CArray1d< int >, CArray1d< Vector3d >, CArray2d< double >, CArray2d< Vector3d >, CArray3d< double >, CArray3d< char >, and CArray3d< Vector3d >.
Definition at line 194 of file ngarray.h.
Referenced by CProfile::clear(), and MConf::pBase::operator>>().
void init (size_t size, const T & val = T())
reshape and initialize the array
This function will reshape the array to range from index 0 to size - 1. All stored data will be forgotten and the new array elements are initialized with a constant value. If you don't specify an initialization value, the default constructor for the type will be called.
Definition at line 208 of file ngarray.h.
Referenced by CArray2d< Vector3d >::resize(), and CProfile::set().
void init (int min, int max, const T & val = T())
reshape and initialize the array
This function will reshape the array to the provided dimensions. All stored data will be forgotten and the new array elements are initialized with a constant value. If you don't specify an initialization value, the default constructor for the type will be called.
Reimplemented in CArray1d< TV >, CArray1d< double >, CArray1d< CComplex >, CArray1d< int >, and CArray1d< Vector3d >.
Definition at line 222 of file ngarray.h.
virtual void fill (const T & val) [virtual]
initialize all elements with a constant value.
Definition at line 230 of file ngarray.h.
Referenced by ngArray< CArray2d< Vector3d > >::init(), and ngArray< CArray2d< Vector3d > >::ngArray().
size_t size () const
Returns actual array size.
Reimplemented in CArray1d< TV >, CArray1d< double >, CArray1d< CComplex >, CArray1d< int >, and CArray1d< Vector3d >.
Definition at line 238 of file ngarray.h.
Referenced by ngArray< CArray2d< Vector3d > >::empty(), and CProfile::scale().
int minIdx () const
return the minimum index. This function returns the minimum valid index to the array. If the array is empty, this value is INT_MAX.
Definition at line 246 of file ngarray.h.
int maxIdx () const
return the maximum index. This function returns the maximum valid index to the array. If the array is empty, the value INT_MAX-1 is returned - just to make constructs like
 for (int i = array.minIdx(); i < array.maxIdx(); i++)
      do_something(array[i]);
work as expected. It's better you check that the array is not empty before trying to access it.
Definition at line 261 of file ngarray.h.
bool empty () const
return whether the array is empty
Definition at line 267 of file ngarray.h.
Referenced by CProfile::empty().
T* array ()
Returns memory pointer.
This function may be expensive because the whole array may need to be copied. This function may also be dangerous because the access to the elements is not protected.
Definition at line 278 of file ngarray.h.
const T* constArray () const
returns constant pointer to the elements
This function returns a pointer to the memory where the elements are stored. It is just like a normal C style array. If the array is empty, you get a NULL pointer returned. This function may be dangerous because the access to the elements is not protected.
Definition at line 291 of file ngarray.h.
Referenced by CArray2d< Vector3d >::addweighted(), CRayTrace::getTraceLen(), CRayTrace::getTracereff(), CRayTrace::getTraceRxyz(), CRayTrace::getTraceSurfNum(), CRayTrace::getTraceVolume(), CArray2d< Vector3d >::operator+=(), CArray2d< Vector3d >::operator-=(), and CArray3d< Vector3d >::operator=().
void detach () [protected]
Definition at line 369 of file ngarray.h.
Referenced by ngArray< CArray2d< Vector3d > >::array(), ngArray< CArray2d< Vector3d > >::fill(), and ngArray< CArray2d< Vector3d > >::operator[]().
Member Data Documentation
Rep* p [protected]
Definition at line 376 of file ngarray.h.
Referenced by ngArray< CArray2d< Vector3d > >::array(), ngArray< CArray2d< Vector3d > >::clear(), ngArray< CArray2d< Vector3d > >::constArray(), ngArray< CArray2d< Vector3d > >::detach(), ngArray< CArray2d< Vector3d > >::fill(), ngArray< CArray2d< Vector3d > >::init(), ngArray< CArray2d< Vector3d > >::maxIdx(), ngArray< CArray2d< Vector3d > >::minIdx(), ngArray< CArray2d< Vector3d > >::ngArray(), ngArray< CArray2d< Vector3d > >::operator=(), ngArray< CArray2d< Vector3d > >::operator[](), ngArray< CArray2d< Vector3d > >::size(), ngArray< CArray2d< Vector3d > >::wd(), and ngArray< CArray2d< Vector3d > >::~ngArray().
The documentation for this class was generated from the following file:
ngarray.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik