MConf: Vector3d Class Reference
Vector3d Class Reference
This class provides 3d-vector type.
#include <CVector3d.h>
Public Member Functions
Vector3d ()
Default constructor.
Vector3d (Vector3d const &v)
Copy constructor.
Vector3d (double x, double y=0., double z=0.)
Constructor.
template<class T >
Vector3d (const T *a)
Constructor.
void set (double x, double y=0., double z=0.)
Set components.
template<class T >
void setFrom (const T *a)
Set components from T array.
template<class T >
void copyTo (T *a)
Copy components to T array.
void zero ()
Zero components.
double & operator[] (int row)
operator []
const double & operator[] (int row) const
operator []
double & x ()
Get reference to the first component for reading/writing.
const double & x () const
Get the first component.
double & y ()
Get reference to the second component for reading/writing.
const double & y () const
Get the second component.
double & z ()
Get reference to the third component for reading/writing.
const double & z () const
Get the third component.
void print () const
Print, printf is used.
template<class T >
size_t write (T x, FILE *fp) const
Write into binary file.
template<class T >
size_t read (T x, FILE *fp)
Read from binary file.
double sum () const
Length of Vector3d.
double abs () const
Length of Vector3d.
double abs2 () const
Square of the length of Vector3d.
Vector3d & norm ()
Normalize, set Length of Vector3d to 1.
double mmin () const
minimum value of component
double mmax () const
maximum value of component
int maxComponent () const
Find dominant coordinate.
void delComponent (int m)
Delete component.
Vector3d & operator= (Vector3d const &v)
Simple assignment.
Vector3d & operator= (double d)
Simple assignment of double to the first component of Vector3d.
Vector3d & operator+= (Vector3d const &v)
Addition assignment.
Vector3d & operator-= (Vector3d const &v)
Subtraction assignment.
Vector3d & operator*= (double d)
Multiplication assignment.
Vector3d & operator/= (double d)
Division assignment.
Vector3d & operator/= (Vector3d const &v)
Componentwise division assignment.
Vector3d & operator&= (Vector3d const &v)
Componentwise multiplication assignment.
Vector3d operator^= (Vector3d const &v)
Cross product assignment.
Vector3d operator+ () const
Plus sign.
Vector3d operator- () const
Minus sign, change sign of Vector3d.
Vector3d toCylindrical () const
The method returns cylindrical coordinates of the point assuming this object contains cartesian coordinates of the point.
Vector3d toCartesian () const
The method returns cartesian coordinates of the point assuming this object contains cylindrical coordinates of the point.
Vector3d cylVector2Cartesian (const Vector3d &cyl) const
The method returns cartesian vector assuming this object contains vector given in cylindrical coordinates.
Vector3d Cartesian2cylVector (const Vector3d &cyl) const
The method returns vector in cylindrical coordinates assuming this object contains vector given in cartesian coordinates.
double diffCyl2 (const Vector3d &c)
The method returns dR^2, where dR is the distance between points c and this vector.
double diffCyl2x (const Vector3d &r)
The method returns dR.abs2(), where dR is the distance between points r and this vector.
Static Public Member Functions
static Vector3d exp (Vector3d const &v)
Componentwise exponent of Vector3d.
static Vector3d cos (Vector3d const &v)
Componentwise cosine of Vector3d.
static Vector3d sin (Vector3d const &v)
Componentwise sine of Vector3d.
Friends
std::ostream & operator<< (std::ostream &o, const Vector3d &v)
Write to stream.
std::istream & operator>> (std::istream &i, Vector3d &v)
Read from stream.
Vector3d operator+ (Vector3d const &v1, Vector3d const &v2)
Sum of two Vector3d.
Vector3d operator- (Vector3d const &v1, Vector3d const &v2)
Subtraction of two Vector3d.
Vector3d operator^ (Vector3d const &v1, Vector3d const &v2)
Cross product of two Vector3d.
Vector3d operator& (Vector3d const &v1, Vector3d const &v2)
Componentwise product of two Vector3d.
double operator* (Vector3d const &v1, Vector3d const &v2)
Dot product of two Vector3d.
Vector3d operator* (Vector3d const &v, double d)
Product of Vector3d and double.
Vector3d operator* (double d, Vector3d const &v)
Product of Vector3d and double.
Vector3d operator/ (Vector3d const &v, double d)
Devide Vector3d by double.
Vector3d operator/ (Vector3d const &v1, Vector3d const &v2)
Componentwise division of two Vector3d.
Vector3d operator/ (double d, Vector3d const &v)
Componentwise division: Vector3d=double/Vector3d.
int operator== (Vector3d const &v1, Vector3d const &v2)
Compare two Vector3d.
int operator== (Vector3d const &v, double d)
Compare the first component of Vector3d with double.
int operator== (double d, Vector3d const &v)
Compare the first component of Vector3d with double.
int operator!= (Vector3d const &v1, Vector3d const &v2)
Compare two Vector3d.
int operator!= (Vector3d const &v, double d)
Compare the first component of Vector3d with double.
int operator!= (double d, Vector3d const &v)
Compare the first component of Vector3d with double.
Detailed Description
This class provides 3d-vector type.
Basically this is a cartesian vector. In addition to the usual operation with vectors in Cartesian coordinates the following operation are provided:
componentwise product,
componentwise division,
reading/writing from/to binary file,
seting/coping components from/to array.
This class can be used for storing the coordinates of a point or vector in other coordinate system. The transformations between cartesian and cylindrical point or vector are provided; Operations with vectors in cylindrical(or other) coordinates are not defined.
Usage:
 #include "CVector3d.h"
 int main() {
   Vector3d a(1,2,3),b(4,2,3),c;
   a.x()= b.y();
   a[0] = b[1];  //the same as above
   double x=a*b; //dot product
   c=2/b; //componentwise division
   c=a/b; //componentwise division
   c=a^b; //cross product
   c=a&b; //componentwise product
   Vector3d *d = new Vector3d[100]; // array of vectors
 // do something with d, then save
   FILE *fp=fopen("test","wb");
   for(int i=0; i<100; i++) d[i].write(double(1),fp);
 }
Author:
Yuriy Turkin @ ipp mpg de
Examples:
1stexample.cpp, 2ndexample.cpp, 3dmeshtest.cpp, accuracytest.cpp, cpp2for.cpp, raytrace1.cpp, raytrace2.cpp, and remesh.cpp.
Definition at line 52 of file CVector3d.h.
Constructor & Destructor Documentation
Vector3d ()
Default constructor.
Definition at line 58 of file CVector3d.h.
Referenced by Vector3d::cos(), Vector3d::exp(), Vector3d::operator-(), Vector3d::sin(), Vector3d::toCartesian(), and Vector3d::toCylindrical().
Vector3d (Vector3d const & v)
Copy constructor.
Definition at line 60 of file CVector3d.h.
Vector3d (double x, double y = 0., double z = 0.)
Constructor.
Definition at line 62 of file CVector3d.h.
Vector3d (const T * a)
Constructor.
Parameters:
a is the array with 3 elements at least.
Definition at line 65 of file CVector3d.h.
Member Function Documentation
void set (double x, double y = 0., double z = 0.)
Set components.
Definition at line 67 of file CVector3d.h.
References Vector3d::x(), Vector3d::y(), and Vector3d::z().
void setFrom (const T * a)
Set components from T array.
Definition at line 69 of file CVector3d.h.
Referenced by MCCYL2MAG(), MCGETCOVAGRADB(), and MCGETGRADB().
void copyTo (T * a)
Copy components to T array.
Definition at line 71 of file CVector3d.h.
Referenced by M3DgetBandGradB(), M3DgetBandGradBxyz(), M3DgetBGradsxyz(), M3DgetdB_Gradsxyz(), M3DgetdGradsxyz(), M3DgetGradBxyz(), M3DgetRayEntryPoint(), MCBOOZER2VMEC(), MCBOOZERCONTRABASIS(), MCCOORDFIELDLINE(), MCCYL2MAG(), MCCYL2MAG2(), MCGETALLXYZ(), MCgetBandBasisVectorsxyz(), MCGETBANDGRADIENTS(), MCgetBandGradientsxyz(), MCGETBCURLBGRADFCYL(), MCGETBCYL(), MCgetBxyz(), MCGETCOVAGRADB(), MCgetdB_Gradsxyz(), MCGETDBCYL(), MCGETGRADB(), MCgetGradBxyz(), MCGETGRADSXYZ(), MCGETMAGCOORDATB(), MCgetRayIntersectionPoints(), MCGETSBCYL(), MCGETSBXYZ(), MCM3DGETALLCYL(), MCM3DGETALLXYZ(), MCM3DGETDBCYL(), MCM3DGETDBXYZ(), MCM3DGETGRADS(), MCM3DGETGRADSXYZ(), MCM3DGETRAYENTRYPOINT(), MCMAG2CYL(), MCmag2xyz(), MCMAG2XYZ(), MCmix2xyz(), MCMIXCOORD2CYL(), MCMIXCOORD2XYZ(), MCPEST2VMEC(), MCSFLCONTRABASIS(), MCSFLCOORDONBLINEATTHETA(), MCTRACELCMS(), MCVMEC2BOOZER(), MCVMEC2PEST(), MCxyz2mag(), and MCXYZ2MAG2().
void zero ()
Zero components.
Definition at line 73 of file CVector3d.h.
double& operator[] (int row)
operator []
Parameters:
row =0,1,2 is the component number
Returns:
reference to the correspondent component
Definition at line 77 of file CVector3d.h.
const double& operator[] (int row) const
operator []
Parameters:
row =0,1,2 is the component number
Returns:
reference to the correspondent component
Definition at line 81 of file CVector3d.h.
double& x ()
Get reference to the first component for reading/writing.
Returns:
reference to the first component of the vector
Definition at line 84 of file CVector3d.h.
Referenced by Vector3d::Cartesian2cylVector(), Vector3d::cos(), Vector3d::cylVector2Cartesian(), CStconfig::ctResults::diffCyl2(), Vector3d::exp(), MCISINSIDEBORDER(), Vector3d::operator^=(), Vector3d::set(), and Vector3d::sin().
const double& x () const
Get the first component.
Returns:
reference to the first component of the vector
Definition at line 87 of file CVector3d.h.
double& y ()
Get reference to the second component for reading/writing.
Returns:
reference to the second component of the vector
Definition at line 90 of file CVector3d.h.
Referenced by Vector3d::Cartesian2cylVector(), Vector3d::cos(), Vector3d::cylVector2Cartesian(), CStconfig::ctResults::diffCyl2(), Vector3d::exp(), MCISINSIDEBORDER(), Vector3d::operator^=(), Vector3d::set(), and Vector3d::sin().
const double& y () const
Get the second component.
Returns:
reference to the second component of the vector
Definition at line 93 of file CVector3d.h.
double& z ()
Get reference to the third component for reading/writing.
Returns:
reference to the third component of the vector
Definition at line 96 of file CVector3d.h.
Referenced by Vector3d::Cartesian2cylVector(), Vector3d::cos(), Vector3d::cylVector2Cartesian(), CStconfig::ctResults::diffCyl2(), Vector3d::exp(), MCISINSIDEBORDER(), Vector3d::set(), and Vector3d::sin().
const double& z () const
Get the third component.
Returns:
reference to the third component of the vector
Definition at line 99 of file CVector3d.h.
void print () const
Print, printf is used.
Definition at line 101 of file CVector3d.h.
size_t write (T x, FILE * fp) const
Write into binary file.
Parameters:
x is a dummy parameter used to choose float or double format for writing of vector components; x must be float(1) or double(1).
fp is the pointer to FILE structure
Returns:
3 - the number of components actually written, which may be less than 3 if an error occurs; see fwrite in <stdio.h>
Note:
fwrite from <stdio.h> is used because it fast; file must be opened before writing in binary mode: FILE *fp=fopen("test","wb");
Definition at line 123 of file CVector3d.h.
size_t read (T x, FILE * fp)
Read from binary file.
Parameters:
x is a dummy parameter used to specify the file format; x must be float(1) or double(1).
fp is the pointer to FILE structure
Returns:
3 - the number of components actually read, which may be less than 3 if an error occurs or if the end of the file is encountered; see fread in <stdio.h>
Note:
fread from <stdio.h> is used because it fast file must be opened before reading in binary mode: FILE *fp=fopen("test","rb");
Definition at line 138 of file CVector3d.h.
double sum () const
Length of Vector3d.
Returns:
x()+y()+z()
Definition at line 147 of file CVector3d.h.
double abs () const
Length of Vector3d.
Returns:
sqrt(x()*x()+y()*y()+z()*z())
Examples:
accuracytest.cpp, and raytrace1.cpp.
Definition at line 150 of file CVector3d.h.
Referenced by MCTRACELCMS(), and Vector3d::norm().
double abs2 () const
Square of the length of Vector3d.
Returns:
x()*x()+y()*y()+z()*z()
Definition at line 153 of file CVector3d.h.
Referenced by Vector3d::diffCyl2x().
Vector3d& norm ()
Normalize, set Length of Vector3d to 1.
Returns:
this vector
Definition at line 158 of file CVector3d.h.
References Vector3d::abs().
double mmin () const
minimum value of component
Returns:
min (x(),y(),z())
Definition at line 164 of file CVector3d.h.
double mmax () const
maximum value of component
Returns:
max (x(),y(),z())
Definition at line 170 of file CVector3d.h.
int maxComponent () const
Find dominant coordinate.
Returns:
the component number with maximum absolute value
Definition at line 176 of file CVector3d.h.
void delComponent (int m)
Delete component.
Method sets deleted component to zero and moves it to the end. Vector3d(1,2,3).delComponent(2) transforms to Vector3d(1,3,0)
Parameters:
m is the component to delete, m=0,1,2
Definition at line 187 of file CVector3d.h.
Vector3d& operator= (Vector3d const & v)
Simple assignment.
Definition at line 200 of file CVector3d.h.
References Vector3d::xx, Vector3d::yy, and Vector3d::zz.
Vector3d& operator= (double d)
Simple assignment of double to the first component of Vector3d.
Definition at line 209 of file CVector3d.h.
Vector3d& operator+= (Vector3d const & v)
Addition assignment.
Definition at line 215 of file CVector3d.h.
References Vector3d::xx, Vector3d::yy, and Vector3d::zz.
Vector3d& operator-= (Vector3d const & v)
Subtraction assignment.
Definition at line 222 of file CVector3d.h.
References Vector3d::xx, Vector3d::yy, and Vector3d::zz.
Vector3d& operator*= (double d)
Multiplication assignment.
Definition at line 229 of file CVector3d.h.
Vector3d& operator/= (double d)
Division assignment.
Definition at line 236 of file CVector3d.h.
Vector3d& operator/= (Vector3d const & v)
Componentwise division assignment.
Returns:
Vector3d
Definition at line 244 of file CVector3d.h.
References Vector3d::xx, Vector3d::yy, and Vector3d::zz.
Vector3d& operator&= (Vector3d const & v)
Componentwise multiplication assignment.
Definition at line 251 of file CVector3d.h.
References Vector3d::xx, Vector3d::yy, and Vector3d::zz.
Vector3d operator^= (Vector3d const & v)
Cross product assignment.
Definition at line 258 of file CVector3d.h.
References Vector3d::x(), Vector3d::xx, Vector3d::y(), Vector3d::yy, and Vector3d::zz.
Vector3d operator+ () const
Plus sign.
Definition at line 268 of file CVector3d.h.
Vector3d operator- () const
Minus sign, change sign of Vector3d.
Definition at line 272 of file CVector3d.h.
References Vector3d::Vector3d().
static Vector3d exp (Vector3d const & v) [static]
Componentwise exponent of Vector3d.
Definition at line 352 of file CVector3d.h.
References Vector3d::Vector3d(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
static Vector3d cos (Vector3d const & v) [static]
Componentwise cosine of Vector3d.
Definition at line 356 of file CVector3d.h.
References Vector3d::Vector3d(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
Referenced by Vector3d::Cartesian2cylVector(), Vector3d::cylVector2Cartesian(), Vector3d::diffCyl2(), and Vector3d::toCartesian().
static Vector3d sin (Vector3d const & v) [static]
Componentwise sine of Vector3d.
Definition at line 360 of file CVector3d.h.
References Vector3d::Vector3d(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
Referenced by Vector3d::Cartesian2cylVector(), Vector3d::cylVector2Cartesian(), and Vector3d::toCartesian().
Vector3d toCylindrical () const
The method returns cylindrical coordinates of the point assuming this object contains cartesian coordinates of the point.
Definition at line 365 of file CVector3d.h.
References Vector3d::Vector3d().
Vector3d toCartesian () const
The method returns cartesian coordinates of the point assuming this object contains cylindrical coordinates of the point.
Definition at line 370 of file CVector3d.h.
References Vector3d::cos(), Vector3d::sin(), and Vector3d::Vector3d().
Referenced by Vector3d::diffCyl2x(), and CStconfig::ctResults::saveLastJacobian().
Vector3d cylVector2Cartesian (const Vector3d & cyl) const
The method returns cartesian vector assuming this object contains vector given in cylindrical coordinates.
Parameters:
cyl is the cylindrical coordinates of the point at which the object vector is given
Definition at line 377 of file CVector3d.h.
References Vector3d::cos(), Vector3d::sin(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
Vector3d Cartesian2cylVector (const Vector3d & cyl) const
The method returns vector in cylindrical coordinates assuming this object contains vector given in cartesian coordinates.
Parameters:
cyl is the cylindrical coordinates of the point at which the object vector is given
Definition at line 392 of file CVector3d.h.
References Vector3d::cos(), Vector3d::sin(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
double diffCyl2 (const Vector3d & c)
The method returns dR^2, where dR is the distance between points c and this vector.
Both vectors are given in cylindrical coordinates.
Definition at line 406 of file CVector3d.h.
References Vector3d::cos(), Vector3d::xx, Vector3d::yy, and Vector3d::zz.
double diffCyl2x (const Vector3d & r)
The method returns dR.abs2(), where dR is the distance between points r and this vector.
Both vectors are given in cylindrical coordinates.
Definition at line 416 of file CVector3d.h.
References Vector3d::abs2(), and Vector3d::toCartesian().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const Vector3d & v) [friend]
Write to stream.
Definition at line 103 of file CVector3d.h.
std::istream& operator>> (std::istream & i, Vector3d & v) [friend]
Read from stream.
Definition at line 110 of file CVector3d.h.
Vector3d operator+ (Vector3d const & v1, Vector3d const & v2) [friend]
Sum of two Vector3d.
Definition at line 276 of file CVector3d.h.
Vector3d operator- (Vector3d const & v1, Vector3d const & v2) [friend]
Subtraction of two Vector3d.
Definition at line 280 of file CVector3d.h.
Vector3d operator^ (Vector3d const & v1, Vector3d const & v2) [friend]
Cross product of two Vector3d.
Definition at line 284 of file CVector3d.h.
Vector3d operator& (Vector3d const & v1, Vector3d const & v2) [friend]
Componentwise product of two Vector3d.
Definition at line 290 of file CVector3d.h.
double operator* (Vector3d const & v1, Vector3d const & v2) [friend]
Dot product of two Vector3d.
Definition at line 294 of file CVector3d.h.
Vector3d operator* (Vector3d const & v, double d) [friend]
Product of Vector3d and double.
Definition at line 298 of file CVector3d.h.
Vector3d operator* (double d, Vector3d const & v) [friend]
Product of Vector3d and double.
Definition at line 302 of file CVector3d.h.
Vector3d operator/ (Vector3d const & v, double d) [friend]
Devide Vector3d by double.
Definition at line 306 of file CVector3d.h.
Vector3d operator/ (Vector3d const & v1, Vector3d const & v2) [friend]
Componentwise division of two Vector3d.
Returns:
Vector3d
Definition at line 312 of file CVector3d.h.
Vector3d operator/ (double d, Vector3d const & v) [friend]
Componentwise division: Vector3d=double/Vector3d.
Returns:
Vector3d
Definition at line 318 of file CVector3d.h.
int operator== (Vector3d const & v1, Vector3d const & v2) [friend]
Compare two Vector3d.
Returns:
true if equal
Definition at line 323 of file CVector3d.h.
int operator== (Vector3d const & v, double d) [friend]
Compare the first component of Vector3d with double.
Returns:
true if equal and two other components are zero
Definition at line 328 of file CVector3d.h.
int operator== (double d, Vector3d const & v) [friend]
Compare the first component of Vector3d with double.
Returns:
true if equal and two other components are zero
Definition at line 333 of file CVector3d.h.
int operator!= (Vector3d const & v1, Vector3d const & v2) [friend]
Compare two Vector3d.
Returns:
true if not equal
Definition at line 338 of file CVector3d.h.
int operator!= (Vector3d const & v, double d) [friend]
Compare the first component of Vector3d with double.
Returns:
true if not equal
Definition at line 343 of file CVector3d.h.
int operator!= (double d, Vector3d const & v) [friend]
Compare the first component of Vector3d with double.
Returns:
true if not equal
Definition at line 348 of file CVector3d.h.
The documentation for this class was generated from the following file:
CVector3d.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik