MConf: vectorOfPtr< pT > Class Template Reference
vectorOfPtr< pT > Class Template Reference
The class provides vector of pointers to simplify dealocation.
#include <mathf.h>
Public Member Functions
~vectorOfPtr ()
void clear ()
void resize (int n)
Protected Member Functions
pT This (int i)
Detailed Description
template<typename pT>
class mathf::vectorOfPtr< pT >
The class provides vector of pointers to simplify dealocation.
pT is the pointer to some object, memory for which was allocated by new The memory is deallocated by clear() or automatically by destructor when this class is deleted.
Definition at line 325 of file mathf.h.
Constructor & Destructor Documentation
~vectorOfPtr ()
Definition at line 330 of file mathf.h.
References vectorOfPtr< pT >::clear().
Member Function Documentation
pT This (int i) [protected]
Definition at line 328 of file mathf.h.
void clear ()
Definition at line 333 of file mathf.h.
Referenced by vectorOfPtr< pT >::resize(), and vectorOfPtr< pT >::~vectorOfPtr().
void resize (int n)
Definition at line 340 of file mathf.h.
References vectorOfPtr< pT >::clear().
The documentation for this class was generated from the following file:
mathf.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik