MConf: Threads2< T, TR > Class Template Reference
Threads2< T, TR > Class Template Reference
#include <threads.h>
Classes
struct Args
Public Member Functions
Threads2 (T *ob, TExeFun exe, TR *oRHS, const char *name=0)
virtual ~Threads2 ()
void run (int low, int upper, int nThreads, int NPPT=5)
Detailed Description
template<class T, class TR>
class MConf::Threads2< T, TR >
Definition at line 259 of file threads.h.
Constructor & Destructor Documentation
Threads2 (T * ob, TExeFun exe, TR * oRHS, const char * name = 0)
Definition at line 264 of file threads.h.
virtual ~Threads2 () [virtual]
Definition at line 265 of file threads.h.
Member Function Documentation
void run (int low, int upper, int nThreads, int NPPT = 5)
Parameters:
[in] low
[in] upper; low and upper are the first and last indexes in arrays to be filled, low<=upper.
[in] nThreads is the number of threads to run
[in] NPPT is the min number of array indexes per thread to be filled
See also:
void(T::*TExeFun)(TR *objR, int i1, int i2, bool setup), where [i1 - i2] is the portion interval of the full interval [low - upper] if setup is false
Definition at line 272 of file threads.h.
References TESTPRINT, MConf::ui_beginthreadex(), MConf::ui_mutex_destroy(), MConf::ui_mutex_init(), and MConf::ui_waitthread().
The documentation for this class was generated from the following file:
threads.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik