MConf: CArray3d< TV > Class Template Reference
CArray3d< TV > Class Template Reference
This class provides 3d-array.
#include <CArray3d.h>
Public Member Functions
CArray3d ()
Default constructor.
CArray3d (int dim1, int dim2, int dim3)
Constructor, creates array with dimentions dim1,dim2,and dim2.
CArray3d (CArray3d const &z)
bool isOK () const
The method returns true if no error occurs in the last operation with array.
CArray2d< TV > & operator[] (int i)
The operator returns the reference to the CArray2d.
const CArray2d< TV > & operator[] (int i) const
The operator returns the constant reference to the CArray2d.
CArray3d & operator= (const TV &x)
The operator assigns x to all element.
CArray3d & operator= (const CArray3d &z)
Assignment operator.
bool resize (int low, int upper)
The method changes the shape of the array.
bool resize (int dim1)
The method changes the fisrt dimention of the array.
bool resize (int dim1, int dim2, int dim3)
The method changes the dimentions of the array.
void clear ()
The method frees memory This function will clear the array.
void print () const
The method prints all elements of the array.
template<class T >
size_t write (T x, FILE *fp, int i1=0, int i2=0) const
Write into binary file.
template<class T >
size_t read (T x, FILE *fp)
Read from binary file the array that was written by write() method.
Detailed Description
template<class TV>
class MConf::CArray3d< TV >
This class provides 3d-array.
For internal use only. Strictly speaking this is not 3d-array, but 1d-array of CArray2d. The class is designed for internal use in class C3dMesh.
Definition at line 17 of file CArray3d.h.
Constructor & Destructor Documentation
CArray3d ()
Default constructor.
Definition at line 22 of file CArray3d.h.
CArray3d (int dim1, int dim2, int dim3)
Constructor, creates array with dimentions dim1,dim2,and dim2.
Use isOK() method to check whether the method succeeds.
Definition at line 25 of file CArray3d.h.
CArray3d (CArray3d< TV > const & z)
Definition at line 28 of file CArray3d.h.
Member Function Documentation
bool isOK () const
The method returns true if no error occurs in the last operation with array.
Definition at line 30 of file CArray3d.h.
Referenced by CArray3d< Vector3d >::operator=(), CArray3d< Vector3d >::print(), CArray3d< Vector3d >::resize(), and CArray3d< Vector3d >::write().
CArray2d<TV>& operator[] (int i)
The operator returns the reference to the CArray2d.
Parameters:
i is the index of CArray2d.
Returns:
reference to the CArray2d.
Note:
method ngArray::array() is very specific, see ngArray::detach() where the whole array may need to be copied if clones exist, but the clones are not affected!
Reimplemented from ngArray< CArray2d< TV > >.
Definition at line 36 of file CArray3d.h.
const CArray2d<TV>& operator[] (int i) const
The operator returns the constant reference to the CArray2d.
Reimplemented from ngArray< CArray2d< TV > >.
Definition at line 38 of file CArray3d.h.
CArray3d& operator= (const TV & x)
The operator assigns x to all element.
Definition at line 40 of file CArray3d.h.
CArray3d& operator= (const CArray3d< TV > & z)
Assignment operator.
Definition at line 48 of file CArray3d.h.
bool resize (int low, int upper)
The method changes the shape of the array.
Previous content of the array is not preserved.
Parameters:
low,upper are the bounds for the 1st index,
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds.
Note:
the memory for other dimentions must be allocated as follows:
 MConf::CArray3d<double> B;
 B.resize(-2,10);
 B[-1].resize(-10,20, -1,200); // resize the plane number -1
Definition at line 71 of file CArray3d.h.
Referenced by CArray3d< Vector3d >::CArray3d(), CArray3d< Vector3d >::operator=(), CArray3d< Vector3d >::read(), and CArray3d< Vector3d >::resize().
bool resize (int dim1)
The method changes the fisrt dimention of the array.
Previous content of the array is not preserved.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds.
Note:
the memory for other dimentions must be allocated as follows:
 MConf::CArray3d<double> B;
 B.resize(20);
 B[5].resize(-10,20, -1,200); // resize the plane number 5
Definition at line 87 of file CArray3d.h.
bool resize (int dim1, int dim2, int dim3)
The method changes the dimentions of the array.
Previous content of the array is not preserved.
Parameters:
dim1,dim2,dim3 are the new dimentions.
Returns:
if the method succeeds, the return value is true; false otherwise. You can also use isOK() method to check whether the method succeeds.
Definition at line 95 of file CArray3d.h.
void clear ()
The method frees memory This function will clear the array.
Afterwards, you can't access any element or you might get a segmentation fault.
Note:
All stored data will be forgotten.
Reimplemented from ngArray< CArray2d< TV > >.
Definition at line 111 of file CArray3d.h.
Referenced by CArray3d< Vector3d >::resize().
void print () const
The method prints all elements of the array.
Definition at line 117 of file CArray3d.h.
size_t write (T x, FILE * fp, int i1 = 0, int i2 = 0) const
Write into binary file.
Parameters:
x is a dummy parameter used to choose char or float or double format for writing of array elements; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure.
i1,i2 if i1<i2 then write planes number from i1 to i2, where the plane number means the values of the 1st index of array.
Returns:
number of elements actually written,which may be less than dim1*dim2*dim3(or dim1*dim2*dim3*3 for TV==Vector3d) if an error occurs; see fwrite in <stdio.h>
Note:
fwrite from <stdio.h> is used because it fast; file must be opened in binary mode before writing: FILE *fp=fopen("test","wb");
Definition at line 134 of file CArray3d.h.
Referenced by CArray3d< Vector3d >::write().
size_t read (T x, FILE * fp)
Read from binary file the array that was written by write() method.
Parameters:
x is a dummy parameter used to specify the file format; x must be char(1) or float(1) or double(1).
fp is the pointer to FILE structure
Returns:
number of elements actually read. which may be less than dim1*dim2*dim3(or dim1*dim2*dim3*3 for TV==Vector3d) if an error occurs or if the end of the file is encountered; see fread in <stdio.h>
Note:
fread from <stdio.h> is used because it fast file must be opened in binary mode before reading: FILE *fp=fopen("test","rb");
Definition at line 167 of file CArray3d.h.
Referenced by CArray3d< Vector3d >::read().
The documentation for this class was generated from the following file:
CArray3d.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik