MConf: CPfunction Class Reference
CPfunction Class Reference
This class provides the function for creating a plasma profile.
#include <CPfunction.h>
Public Member Functions
CPfunction ()
virtual ~CPfunction ()
double PF (double x, const double *parm) const
PF(x) = g-h+(1-g+h)(1-xp)q + h(1-e-x2/w2), where 0<=x<=1.
void setHoleCenter (double c)
Detailed Description
This class provides the function for creating a plasma profile.
f(x) = g-h+(1-g+h)(1-xp)q + h(1-e-x2/w2), where 0<=x<=1,
properties: g=PF(1)/PF(0), PF(0) = 1, PF(x)>0,
Note:
don't use it directly, use CProfile instead
Examples:
cpp2for.cpp.
Definition at line 15 of file CPfunction.h.
Constructor & Destructor Documentation
CPfunction ()
Definition at line 18 of file CPfunction.h.
virtual ~CPfunction () [virtual]
Definition at line 19 of file CPfunction.h.
Member Function Documentation
double PF (double x, const double * parm) const
PF(x) = g-h+(1-g+h)(1-xp)q + h(1-e-x2/w2), where 0<=x<=1.
Parameters:
x is the abscissa, 0<=x<=1, can be reff/a.
parm is the array[5] of coefficients: g,p,q,h,w.
Returns:
function's value.
Definition at line 26 of file CPfunction.h.
Referenced by PROFILEFUNCTION().
void setHoleCenter (double c)
Definition at line 43 of file CPfunction.h.
Referenced by CProfile::clear(), CProfile::CProfile(), and CProfile::set().
The documentation for this class was generated from the following file:
CPfunction.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik