MConf: C3dMesh Class Reference
C3dMesh Class Reference
This class tabulates magnetic field, flux surface label, grad(s) on a 3d-mesh in cylindrical coordinates and provides functions for interpolation.
#include <C3dMesh.h>
Public Member Functions
C3dMesh * clone ()
The method creates a clone of C3dMesh using operator new.
C3dMesh ()
The constructor creates an empty instance of C3dMesh.
virtual ~C3dMesh ()
The destructor is a virtual method that frees all memory used.
virtual bool load (const char *fname)
The method loads the 3d-mesh and/or magnetic configuration stored in the file fname.
virtual bool load (const char *fname, CStconfig::fileFormat fmt)
bool isMeshOK () const
The method returns true if no error occurs during last operation.
void clearMesh ()
This method frees internal mesh arrays.
virtual void clear ()
This method frees all internal arrays (including base classes) and makes this object empty.
virtual void restoreB0 ()
Restore initial value of the magnetic field.
virtual void setB0 (double B)
Set minimum magnetic field on magnetic axis equals B.
virtual void setB0 (double B, double ficyl)
Set the value of magnetic field on magnetic axis at given cylindrical angle.
virtual void setB00 (double B00)
Set B00-component of magnetic field on magnetic axis.
virtual void scaleB (double multiplier)
Set scaling factor for value of the magnetic field.
virtual void setIcoil (double I)
Set the Ipol value of the coil currents at LCMS.
virtual double getBscaleFactor ()
Get the scaling factor for the magnetic field value.
void setsMax (double smax)
Set the last surface for the mesh creation.
double getsMax () const
Get the value of normalized toroidal flux on the outermost surface used for the mesh creation.
bool createMesh (double dr, double dz, double dfi, int numThreads=8)
The method creates 3d-mesh in cylindrical coordinates.
bool createMeshUsingSymmetry (double dr, double dz, double dfi, int numThreads=4)
The method creates 3d-mesh in cylindrical coordinates.
bool writeMesh (const char *fname) const
The method writes the mesh and current magnetic configuration into file.
bool writeMeshAscii (const char *fname) const
Methods to retrieve data from the mesh
bool M3DcylIsInsideMesh (const Vector3d &cyl, double *distance=NULL) const
The method tests whether the point cyl lies inside sMax.
bool M3DxyzIsInsideMesh (const Vector3d &xyz, double *distance=NULL) const
The method tests whether the point xyz lies inside sMax.
void M3DpositionTestOn ()
The method enables the test of a point position before data retrieving.
void M3DpositionTestOff ()
The method disables the test of a point position.
bool M3DpositionTest () const
The method returns true if position test is enabled.
bool M3DgetRayEntryPoint (const Vector3d &r0, const Vector3d &rd, Vector3d &entryPoint) const
The method traces the Last Closed Magnetic Surface (LCMS).
double M3Dcyl2s (const Vector3d &cyl) const
The method finds the flux label s which corresponds to the point in space.
double M3Dxyz2s (const Vector3d &xyz) const
The method finds the flux label s which corresponds to the point in space.
Vector3d M3DgetBcyl (const Vector3d &cyl) const
The method returns cylindrical B-vector.
Vector3d M3DgetBcyl (const Vector3d &cyl, double &s) const
The method returns cylindrical B-vector.
Vector3d M3DgetBxyz (const Vector3d &xyz) const
The method returns cartesian B-vector.
Vector3d M3DgetBxyz (const Vector3d &xyz, double &s) const
The method returns cartesian B-vector.
Vector3d M3DgetdBcyl (const Vector3d &cyl, Vector3d &dBdr, Vector3d &dBdfir, Vector3d &dBdz) const
The method returns cylindrical vectors B and partial derivatives of B.
Vector3d M3DgetdBxyz (const Vector3d &xyz, Vector3d &dBdx, Vector3d &dBdy, Vector3d &dBdz) const
The method returns cartesian vectors B and partial derivatives of B.
double M3DgetdBGradsxyz (const Vector3d &xyz, Vector3d &B, Vector3d &dBdx, Vector3d &dBdy, Vector3d &dBdz, Vector3d &grads) const
The method returns cartesian vectors B, partial derivatives of B, and grad(s).
double M3DgetdBGradscyl (const Vector3d &cyl, Vector3d &B, Vector3d &dBdr, Vector3d &dBdfir, Vector3d &dBdz, Vector3d &grads) const
The method returns cylindrical vectors B, partial derivatives of B, and grad(s).
Vector3d M3DgetGrads (const Vector3d &cyl) const
The method returns cylindrical vector grad(s).
Vector3d M3DgetGradsxyz (const Vector3d &xyz) const
The method returns cartesian vector grad(s).
Vector3d M3DgetGradB (const Vector3d &cyl) const
The method returns cylindrical vector grad(B).
Vector3d M3DgetGradBxyz (const Vector3d &xyz) const
The method returns cartesian vector grad(B).
double M3DgetBandGradB (const Vector3d &cyl, Vector3d &B, Vector3d &gradB, Vector3d &grads) const
The method returns cylindrical vectors B, grad(|B|), and grad(s).
double M3DgetBandGradBxyz (const Vector3d &xyz, Vector3d &B, Vector3d &gradB, Vector3d &grads) const
The method returns Cartesian vectors B, grad(|B|), and grad(s).
Vector3d M3Dgetdgradscyl (const Vector3d &cyl, Vector3d &dgradsdr, Vector3d &dgradsdfir, Vector3d &dgradsdz) const
Vector3d M3Dgetdgradsxyz (const Vector3d &xyz, Vector3d &dgradsdx, Vector3d &dgradsdy, Vector3d &dgradsdz) const
Detailed Description
This class tabulates magnetic field, flux surface label, grad(s) on a 3d-mesh in cylindrical coordinates and provides functions for interpolation.
4 point Lagrange interpolation in each direction is used.
Usage:
 #include "C3dMesh.h"
 #include <iostream>
 int main() {
   C3dMesh magConf;
   if(!magConf.load ("w7x-sc1.bin4")) exit(1);   // exit if not OK
   if(!magConf.isMeshOK()) // create mesh if needed
      magConf.createMesh(0.02,0.02,pi/180); // mesh=2cm X 2cm X 1degree
   if(!magConf.isMeshOK()) exit(1);    // exit if not OK
   Vector3d cyl(6,0,0); double s;
   Vector3d B, dBdr,dBdfir,dBdz, grads, curlB;
   s = magConf.M3Dcyl2s(cyl);
   B = magConf.M3DgetdBcyl(cyl,dBdr,dBdfir,dBdz);
   std::cout <<dBdr<<std::endl;
   if(magConf.cylIsInside(cyl)) { ;/*do something*/ }
   if(s<1.001) { ;/*do something*/ }
   return 0;
 }
See also:
class CStconfig, class CRayTrace.
Examples:
2ndexample.cpp, 3dmeshtest.cpp, cpp2for.cpp, and raytrace2.cpp.
Definition at line 48 of file C3dMesh.h.
Constructor & Destructor Documentation
C3dMesh ()
The constructor creates an empty instance of C3dMesh.
virtual ~C3dMesh () [virtual]
The destructor is a virtual method that frees all memory used.
Definition at line 102 of file C3dMesh.h.
Member Function Documentation
C3dMesh* clone ()
The method creates a clone of C3dMesh using operator new.
The caller is responsible for deleting the clone.
Reimplemented from CStconfig.
Definition at line 94 of file C3dMesh.h.
Referenced by MCCLONE().
virtual bool load (const char * fname) [virtual]
The method loads the 3d-mesh and/or magnetic configuration stored in the file fname.
The method understands format of a file by analyzing its contents.
See also:
the detailed description of CStconfig::load()
Returns:
if the method succeeds, the return value is true; false otherwise.
Reimplemented from CStconfig.
Examples:
2ndexample.cpp.
Definition at line 108 of file C3dMesh.h.
References C3dMesh::load(), and CStconfig::UNDEFINED.
Referenced by C3dMesh::load(), mc_load(), MC_load(), and MCsetLCMS().
virtual bool load (const char * fname, CStconfig::fileFormat fmt) [virtual]
bool isMeshOK () const
The method returns true if no error occurs during last operation.
Definition at line 111 of file C3dMesh.h.
Referenced by MCISMESHOK().
void clearMesh ()
This method frees internal mesh arrays.
virtual void clear () [virtual]
This method frees all internal arrays (including base classes) and makes this object empty.
Reimplemented from CRayTrace.
virtual void restoreB0 () [virtual]
Restore initial value of the magnetic field.
Reimplemented from CStconfig.
virtual void setB0 (double B) [virtual]
Set minimum magnetic field on magnetic axis equals B.
Parameters:
B is the value[Tesla] of magnetic field to set
Reimplemented from CStconfig.
Examples:
2ndexample.cpp.
Referenced by MCsetB0(), MCSETB0(), and MCSETMINB0().
virtual void setB0 (double B, double ficyl) [virtual]
Set the value of magnetic field on magnetic axis at given cylindrical angle.
Parameters:
B is the value[Tesla] of magnetic field to set
ficyl is the value[radians] of cylindrical angle
Reimplemented from CStconfig.
virtual void setB00 (double B00) [virtual]
Set B00-component of magnetic field on magnetic axis.
Parameters:
B00 is the value[Tesla] of magnetic field to set
Reimplemented from CStconfig.
Referenced by MCsetB00(), and MCSETB00().
virtual void scaleB (double multiplier) [virtual]
Set scaling factor for value of the magnetic field.
Parameters:
multiplier is the scaling factor
Reimplemented from CStconfig.
Referenced by MCSCALEB().
virtual void setIcoil (double I) [virtual]
Set the Ipol value of the coil currents at LCMS.
Parameters:
I is the value[Ampers] of the current to set
Reimplemented from CStconfig.
Referenced by MCSETICOIL(), and MCsetIpLCMS().
virtual double getBscaleFactor () [virtual]
Get the scaling factor for the magnetic field value.
Reimplemented from CStconfig.
void setsMax (double smax)
Set the last surface for the mesh creation.
Parameters:
smax is the label value of the outermost surface used for the mesh creation, recommended value is 1.3, default value is 1.3 This surface is needed for creating the extrapolated region, see also M3Dcyl2s(),getsMax().
Definition at line 146 of file C3dMesh.h.
Referenced by MCM3DSETSMAX(), and MCsetsmax().
double getsMax () const
Get the value of normalized toroidal flux on the outermost surface used for the mesh creation.
Returns:
sMax the label value of the outermost surface used for the mesh creation. This surface is needed for creating the extrapolated region, see also M3Dcyl2s(),setsMax().
Definition at line 150 of file C3dMesh.h.
Referenced by MCM3DGETSMAX().
bool createMesh (double dr, double dz, double dfi, int numThreads = 8)
The method creates 3d-mesh in cylindrical coordinates.
The method tabulates the magnetic field, the flux surface label, and grad(s); the periodicity of the device is taken into account.
Parameters:
dr is the mesh step in r-direction.
dz is the mesh step in z-direction.
dfi is the mesh step in fi-direction, where fi is the cylindrical angle in radians.
numThreads is the number of execution threads used to speed up calculation on a multiprocessor system.
Returns:
if the method succeeds, the return value is true; false otherwise.
Note:
Recomended value of mesh parameters for W7-X are as follows:
dr = 0.02; dz = 0.02; dfi = pi/180; (1degree)
please keep in mind that the function adjusts dfi parameter in accordance with the periodicity.
Attention:
The current truncation level of spectrum, value of magnetic field, and accuracy of coordinate transformatiom are used, see CStconfig::truncate(double level), CStconfig::setB0(), CStconfig::setAccuracy()
Performance
In the following program the createMesh() needs 32sec to build the 3d-mesh on Intel Core 2 Duo CPU P8400 at 2.26GHz using two execution threads; the code is compiled by Visual C++ 2005; the size of saved mesh file is about 13MB.
  C3dMesh mc;
  mc.load ("w7x-sc1.bc");
  mc.truncate(1e-6);                // truncate spectrum
  mc.setAccuracy(1e-3);             // set accuracy of coordinate transformation
  mc.createMesh(0.02,0.02,pi/180,2);// create mesh  2cm X 2cm X 1degree
  mc.writeMesh("w7x-sc1.mesh.bin4");// save mesh
Referenced by MCcreateMesh(), and MCCREATEMESH().
bool createMeshUsingSymmetry (double dr, double dz, double dfi, int numThreads = 4)
The method creates 3d-mesh in cylindrical coordinates.
The method tabulates the magnetic field, the flux surface label, and grad(s); the periodicity (B(r,fi,z)=B(r,fi+period,z)) and symmetry (Br(r,fi,z)=-Br(r,-fi,-z)) of the device are used.
Parameters:
dr is the mesh step in r-direction.
dz is the mesh step in z-direction.
dfi is the mesh step in fi-direction, where fi is the cylindrical angle in radians.
numThreads is the number of execution threads used to speed up calculation on a multiprocessor system.
Returns:
if the method succeeds, the return value is true; false otherwise.
Note:
Recomended value of mesh parameters for W7-X are as follows:
dr = 0.02; dz = 0.02; dfi = pi/180; (1degree)
this method needs two times less memory then createMesh() and works two times faster.
Performance
In the following program the createMeshUsingSymmetry() needs 18sec to build the 3d-mesh on Intel Core 2 Duo CPU P8400 at 2.26GHz using two execution threads; the code is compiled by Visual C++ 2005 ; the size of saved mesh file is about 8MB.
  C3dMesh mc;
  mc.load ("w7x-sc1.bc");
  mc.truncate(1e-6);                // truncate spectrum
  mc.setAccuracy(1e-3);             // set accuracy of coordinate transformation
  mc.createMeshUsingSymmetry(0.02,0.02,pi/180,2);  // create mesh  2cm X 2cm X 1degree
  mc.writeMesh("w7x-sc1.mesh.bin4");// save mesh
Referenced by MCcreateMeshUsingSymmetry(), and MCCREATEMESHUSINGSYMMETRY().
bool writeMesh (const char * fname) const
The method writes the mesh and current magnetic configuration into file.
The format of the file is derived from the file extension. The following file extention are possible:
bin4 -- writeMesh("w.bin4"); //save into binary file 'w.bin4' using float numbers
bin8 -- writeMesh("w.bin8"); //save into binary file 'w.bin8' using double numbers
Parameters:
fname -- filename
Returns:
if the method succeeds, the return value is true; false otherwise.
Attention:
The current truncation level of spectrum, value of magnetic field, and accuracy of coordinate transformatiom are used.
Referenced by MCWRITEMESH().
bool writeMeshAscii (const char * fname) const
bool M3DcylIsInsideMesh (const Vector3d & cyl, double * distance = NULL) const
The method tests whether the point cyl lies inside sMax.
Parameters:
cyl -- cylindrical coordinates of the point.
distance if not NULL then this address at return will contain the distance between cyl and the sMax, the distance is negativ if the point lies inside sMax.
Returns:
the return value is true if the point lies inside sMax; false otherwise.
See also:
setsMax()
bool M3DxyzIsInsideMesh (const Vector3d & xyz, double * distance = NULL) const
The method tests whether the point xyz lies inside sMax.
Parameters:
xyz -- cartesian coordinates of the point.
distance if not NULL then this address at return will contain the distance between xyz and the sMax, the distance is negativ if the point lies inside sMax.
Returns:
the return value is true if the point lies inside sMax; false otherwise.
See also:
setsMax()
void M3DpositionTestOn ()
The method enables the test of a point position before data retrieving.
The methods M3Dcyl2s(), M3DgetBcyl(), and others take as input parameter cylindrical/cartesian coordinates of the point and return values of s, B,... in this point. With the position test enabled the all function, which retrieve data from the mesh, at first do test whether point lies inside sMax-surface. Use this method if you don't know where the point is.
Definition at line 246 of file C3dMesh.h.
void M3DpositionTestOff ()
The method disables the test of a point position.
If you know that the point, in which you need s and B lies inside sMax-surface then use this method to disable test of a position with respect to the sMax. This speeds up calculation.
See also:
M3DpositionTestOn(), M3Dcyl2s().
Definition at line 251 of file C3dMesh.h.
bool M3DpositionTest () const
The method returns true if position test is enabled.
See also:
M3DpositionTestOn().
Definition at line 254 of file C3dMesh.h.
bool M3DgetRayEntryPoint (const Vector3d & r0, const Vector3d & rd, Vector3d & entryPoint) const
The method traces the Last Closed Magnetic Surface (LCMS).
The method finds intersections of the ray with the LCMS, where the ray is R(t)=r0+rd*t, and t>=0.
Parameters:
r0 is the origin of the ray, must be outside with respect to the LCMS.
rd is the direction of the ray
entryPoint this vector at return contains the coordinates of the ray entry point into the plasma
Returns:
if the method succeeds, the return value is true; false otherwise.
Referenced by M3DgetRayEntryPoint(), and MCM3DGETRAYENTRYPOINT().
double M3Dcyl2s (const Vector3d & cyl) const
The method finds the flux label s which corresponds to the point in space.
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest.
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax(),getsMax().
Referenced by MCM3DCYL2S(), and MCM3DGETSBCYL().
double M3Dxyz2s (const Vector3d & xyz) const
The method finds the flux label s which corresponds to the point in space.
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest.
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax().
Referenced by M3DgetBGradsxyz(), M3DgetBxyz(), M3DgetdGradsxyz(), M3DgetGradBxyz(), M3Dxyz2s(), MCM3DGETSBXYZ(), and MCM3DXYZ2S().
Vector3d M3DgetBcyl (const Vector3d & cyl) const
The method returns cylindrical B-vector.
4-points Lagrange interpolation is used.
Parameters:
cyl is the cylindrical coordinates
Returns:
cylindrical B-vector or zero-vector if cyl lies outside the sMax-surface, see M3Dcyl2s()
Referenced by MCM3DGETSBCYL().
Vector3d M3DgetBcyl (const Vector3d & cyl, double & s) const
The method returns cylindrical B-vector.
4-points Lagrange interpolation is used.
Parameters:
cyl is the cylindrical coordinates
s is the reference to the output parameter, at return it contains the flux surface label
Returns:
cylindrical B-vector or zero-vector if cyl lies outside the sMax-surface, see M3Dcyl2s()
Vector3d M3DgetBxyz (const Vector3d & xyz) const
The method returns cartesian B-vector.
4-points Lagrange interpolation is used.
Parameters:
xyz is the cartesian coordinates
Returns:
cartesian B-vector or zero-vector if xyz lies outside the sMax-surface, see M3Dcyl2s()
Referenced by M3DgetBGradsxyz(), M3DgetBxyz(), and MCM3DGETSBXYZ().
Vector3d M3DgetBxyz (const Vector3d & xyz, double & s) const
The method returns cartesian B-vector.
4-points Lagrange interpolation is used.
Parameters:
xyz is the cartesian coordinates
s is the reference to the output parameter, at return it contains the flux surface label
Returns:
cartesian B-vector or zero-vector if xyz lies outside the sMax-surface, see M3Dcyl2s()
Vector3d M3DgetdBcyl (const Vector3d & cyl, Vector3d & dBdr, Vector3d & dBdfir, Vector3d & dBdz) const
The method returns cylindrical vectors B and partial derivatives of B.
4-points Lagrange interpolation is used.
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest
dBdr,dBdfir,dBdz are the references to the output parameters, where B is a vector in cylindrical coordinates and dBdr=dB/dr, dBdfir=dB/dfi/r, dBdz=dB/dz
Returns:
cylindrical B-vector or zero-vector if cyl lies outside the sMax-surface, see M3Dcyl2s()
Referenced by MCM3DGETDBCYL().
Vector3d M3DgetdBxyz (const Vector3d & xyz, Vector3d & dBdx, Vector3d & dBdy, Vector3d & dBdz) const
The method returns cartesian vectors B and partial derivatives of B.
4-points Lagrange interpolation is used.
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest
dBdx,dBdy,dBdz are the references to the output parameters, where B is a vector in cartesian coordinates and dBdx=dB/dx, dBy=dB/dy, dBdz=dB/dz
Returns:
cartesian B-vector or zero-vector if xyz lies outside the sMax-surface, see M3Dcyl2s()
Referenced by MCM3DGETDBXYZ().
double M3DgetdBGradsxyz (const Vector3d & xyz, Vector3d & B, Vector3d & dBdx, Vector3d & dBdy, Vector3d & dBdz, Vector3d & grads) const
The method returns cartesian vectors B, partial derivatives of B, and grad(s).
4-points Lagrange interpolation is used.
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest
B,dBdx,dBdy,dBdz are the references to the output parameters, where B is a vector in cartesian coordinates and dBdx=dB/dx, dBy=dB/dy, dBdz=dB/dz.
grads is the references to the storage for grad(s).
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax().
Referenced by M3DgetdB_Gradsxyz(), and MCM3DGETALLXYZ().
double M3DgetdBGradscyl (const Vector3d & cyl, Vector3d & B, Vector3d & dBdr, Vector3d & dBdfir, Vector3d & dBdz, Vector3d & grads) const
The method returns cylindrical vectors B, partial derivatives of B, and grad(s).
4-points Lagrange interpolation is used.
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest
B,dBdr,dBdfir,dBdz are the references to the output parameters, where B is a vector in cylindrical coordinates and dBdr=dB/dr, dBdfir=dB/dfi/r, dBdz=dB/dz
grads is the references to the storage for grad(s).
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax-surface.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax().
Referenced by MCM3DGETALLCYL().
Vector3d M3DgetGrads (const Vector3d & cyl) const
The method returns cylindrical vector grad(s).
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest.
Returns:
grad(s) or zero-vector if cyl lies outside the sMax-surface, see M3Dcyl2s()
Referenced by MCM3DGETGRADS().
Vector3d M3DgetGradsxyz (const Vector3d & xyz) const
The method returns cartesian vector grad(s).
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest.
Returns:
cartesian coordinates of grad(s) or zero-vector if xyz lies outside the sMax-surface, see M3Dcyl2s()
Referenced by M3DgetBGradsxyz(), and MCM3DGETGRADSXYZ().
Vector3d M3DgetGradB (const Vector3d & cyl) const
The method returns cylindrical vector grad(B).
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest.
Returns:
grad(|B|) or zero-vector if cyl lies outside the sMax-surface, see M3Dcyl2s()
Vector3d M3DgetGradBxyz (const Vector3d & xyz) const
The method returns cartesian vector grad(B).
Parameters:
xyz is the input parameter with the cartesian coordinates of the point of interest.
Returns:
grad(|B|) or zero-vector if xyz lies outside the sMax-surface, see M3Dcyl2s()
Referenced by M3DgetGradBxyz().
double M3DgetBandGradB (const Vector3d & cyl, Vector3d & B, Vector3d & gradB, Vector3d & grads) const
The method returns cylindrical vectors B, grad(|B|), and grad(s).
Parameters:
cyl is the input parameter with the cylindrical coordinates of the point of interest
B is the references to the B.
gradB is the references to the storage for grad(|B|).
grads is the references to the storage for grad(s).
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax-surface.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax().
Referenced by M3DgetBandGradB().
double M3DgetBandGradBxyz (const Vector3d & xyz, Vector3d & B, Vector3d & gradB, Vector3d & grads) const
The method returns Cartesian vectors B, grad(|B|), and grad(s).
Parameters:
xyz is the input parameter with the Cartesian coordinates of the point of interest
B is the references to the B.
gradB is the references to the storage for grad(|B|).
grads is the references to the storage for grad(s).
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<sMax means that the point lies in the extrapolated region, retuned parameters are not reliable here;
s>1000 means that the point lies outside the sMax-surface.
The extrapolated region is needed in order to do interpolation near LCMS, see also setsMax().
Referenced by M3DgetBandGradBxyz().
Vector3d M3Dgetdgradscyl (const Vector3d & cyl, Vector3d & dgradsdr, Vector3d & dgradsdfir, Vector3d & dgradsdz) const
Vector3d M3Dgetdgradsxyz (const Vector3d & xyz, Vector3d & dgradsdx, Vector3d & dgradsdy, Vector3d & dgradsdz) const
Referenced by M3DgetdGradsxyz().
The documentation for this class was generated from the following file:
C3dMesh.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik