MConf: cpp2for.cpp File Reference
cpp2for.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "../include/C3dMesh.h"
#include "../include/CPfunction.h"
#include <iostream>
Defines
#define NOMIXED_STR_LEN_ARG
Functions
static const int True (1)
static const int False (0)
template<class T >
static T mmin (T x, T y)
template<class T >
static T mmax (T x, T y)
static void strtrim (char *f)
static void strtrim (char *dest, char *fname, int i)
WINDLLEXPORT double STDCALL PROFILEFUNCTION (double *x, double *g)
WINDLLEXPORT void STDCALL MCFREE (C3dMesh **mConf)
WINDLLEXPORT C3dMesh *STDCALL MCCLONE (C3dMesh **mConf)
static int MC_load (C3dMesh **mConf, char *fname, int i, CStconfig::fileFormat fmt)
WINDLLEXPORT int STDCALL MCLOAD (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT int STDCALL MCLOADVMEC (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT int STDCALL MCLOADLHD (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT int STDCALL MCLOADEFIT (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT int STDCALL MCISMESHOK (C3dMesh **mConf)
WINDLLEXPORT int STDCALL MCISOK (C3dMesh **mConf)
WINDLLEXPORT void STDCALL MCTRUNCATE (C3dMesh **mConf, double *epsTrunc)
WINDLLEXPORT void STDCALL MCSETACCURACY (C3dMesh **mConf, double *epsA)
WINDLLEXPORT void STDCALL MCSETB0 (C3dMesh **mConf, double *b, double *ficyl)
WINDLLEXPORT void STDCALL MCSETMINB0 (C3dMesh **mConf, double *b)
WINDLLEXPORT double STDCALL MCGETB0 (C3dMesh **mConf, double *ficyl)
WINDLLEXPORT void STDCALL MCSETB00 (C3dMesh **mConf, double *b)
WINDLLEXPORT void STDCALL MCSETICOIL (C3dMesh **mConf, double *I)
WINDLLEXPORT void STDCALL MCSETBDIRECTION (C3dMesh **mConf, int *dir)
WINDLLEXPORT int STDCALL MCGETBDIRECTION (C3dMesh **mConf)
WINDLLEXPORT void STDCALL MCRESTOREBDIRECTION (C3dMesh **mConf)
WINDLLEXPORT double STDCALL MCGETB00 (C3dMesh **mConf)
WINDLLEXPORT void STDCALL MCSFLCOORDONBLINEATTHETA (C3dMesh **mConf, const double *pest0, const double *thetaStar, double *pest)
WINDLLEXPORT void STDCALL MCSFLCONTRABASIS (C3dMesh **mConf, const double *pest, double *gradS, double *gradThetaStar, double *gradPhi, double *mag)
WINDLLEXPORT void STDCALL MCBOOZERCONTRABASIS (C3dMesh **mConf, const double *u, double *gradS, double *gradThetaStar, double *gradPhi, double *mag)
WINDLLEXPORT void STDCALL MCGETBANDGRADIENTS (C3dMesh **mConf, double *magCoord, double *B, double *gradB, double *gradF, double *gradTh, double *gradPh)
WINDLLEXPORT void STDCALL MCGETBCURLBGRADFCYL (C3dMesh **mConf, double *u, double *B, double *curlB, double *gradF)
The method returns B and curl(B) in cylindrical coordinates.
WINDLLEXPORT void STDCALL MCGETGRADB (C3dMesh **mConf, double *magCoord, double *gradB)
WINDLLEXPORT void STDCALL MCGETCOVAGRADB (C3dMesh **mConf, double *magCoord, double *gradB)
WINDLLEXPORT void STDCALL MCSCALEB (C3dMesh **mConf, double *factor)
WINDLLEXPORT void STDCALL MCCYL2MAG (C3dMesh **mConf, double *cyl, double *magCoord, double *Bfield)
WINDLLEXPORT void STDCALL MCCYL2MAG2 (C3dMesh **mConf, double *cyl, double *magCoord, double *Bfield)
WINDLLEXPORT void STDCALL MCXYZ2MAG2 (C3dMesh **mConf, double *xyz, double *magCoord, double *Bfield)
WINDLLEXPORT double STDCALL MCXYZ2S (C3dMesh **mConf, double *xyz)
WINDLLEXPORT double STDCALL MCCYL2S (C3dMesh **mConf, double *cyl)
WINDLLEXPORT void STDCALL MCGETSBXYZ (C3dMesh **mConf, double *xyz, double *S, double *B)
WINDLLEXPORT void STDCALL MCGETSBCYL (C3dMesh **mConf, double *cyl, double *S, double *B)
WINDLLEXPORT void STDCALL MCGETBCYL (C3dMesh **mConf, double *magCoord, double *B)
WINDLLEXPORT double STDCALL MCTORFLUX (C3dMesh **mConf, double *s)
WINDLLEXPORT int STDCALL MCCURRENTSIGNTOINCREASEIOTA (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCREFF (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCVPRIME (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCVOLUME (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCFTRAPPED (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCBAVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCB2AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCB_2AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCGRADS2B_2AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCR2AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCR_2AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCNEOPOLARIZATION (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCNEOPOLARIZATIONPASS (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCNEOPOLARIZATIONTRAP (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCBPHI (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCIPOL (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCITOR (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCB (C3dMesh **mConf, double *s, double *polAngle, double *torAngle)
WINDLLEXPORT double STDCALL MCJACOBIAN (C3dMesh **mConf, double *s, double *polAngle, double *torAngle)
WINDLLEXPORT void STDCALL MCBANDJACOBIAN (C3dMesh **mConf, double *s, double *polAngle, double *torAngle, double *B, double *jac)
WINDLLEXPORT double STDCALL MCRHPOTENCIAL (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCDB12AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCDB32AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCBDB12AVRG (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCROPARINVAVRG (C3dMesh **mConf, double *s, double *x)
WINDLLEXPORT double STDCALL MCPAVRG (C3dMesh **mConf, double *s, double *x)
WINDLLEXPORT double STDCALL MCINTINVPAVRG (C3dMesh **mConf, double *s, double *x)
WINDLLEXPORT double STDCALL MCIOTA (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCIOTAPRIME (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCPRESSUREPRIME (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCPRESSURE (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCTORFLUX2POLFLUX (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCR0 (C3dMesh **mConf)
WINDLLEXPORT double STDCALL MCRMN (C3dMesh **mConf, int *m, int *n, double *s)
WINDLLEXPORT double STDCALL MCZMN (C3dMesh **mConf, int *m, int *n, double *s)
WINDLLEXPORT double STDCALL MCFMN (C3dMesh **mConf, int *m, int *n, double *s)
WINDLLEXPORT double STDCALL MCBMN (C3dMesh **mConf, int *m, int *n, double *s)
WINDLLEXPORT double STDCALL MCBOOZERBMN (C3dMesh **mConf, int *m, int *n, double *s)
WINDLLEXPORT double STDCALL MCAVERAGECROSSSECTIONAREA (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCRMINOR (C3dMesh **mConf)
WINDLLEXPORT int STDCALL MCNPERIODS (C3dMesh **mConf)
WINDLLEXPORT int STDCALL MCTRACELCMS (C3dMesh **mConf, double *R1, double *R2, double *Entry, double *Exit)
The method traces the Last Closed Magnetic Surface (LCMS).
WINDLLEXPORT int STDCALL MCM3DGETRAYENTRYPOINT (C3dMesh **mConf, double *r0, double *rd, double *entryPoint)
WINDLLEXPORT int STDCALL MCCREATEBORDER (C3dMesh **mConf, double *slast, double *ficyl, int *BrdSize)
WINDLLEXPORT int STDCALL MCISINSIDEBORDER (C3dMesh **mConf, double *XYZ)
WINDLLEXPORT void STDCALL MCGETDBCYL (C3dMesh **mConf, double *cyl, double *B, double *dBdr, double *dBdfir, double *dBdz)
WINDLLEXPORT void STDCALL MCCOORDFIELDLINE (C3dMesh **mConf, double *mixCoord0, double *fcyl, double *magCoord)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,ficyl0).
WINDLLEXPORT int STDCALL MCCREATEMESH (C3dMesh **mConf, double *dr, double *dz, double *dfi)
WINDLLEXPORT int STDCALL MCCREATEMESHUSINGSYMMETRY (C3dMesh **mConf, double *dr, double *dz, double *dfi)
WINDLLEXPORT void STDCALL MCM3DGETDBXYZ (C3dMesh **mConf, double *xyz, double *B, double *dBdx, double *dBdy, double *dBdz)
WINDLLEXPORT void STDCALL MCM3DGETDBCYL (C3dMesh **mConf, double *cyl, double *B, double *dBdr, double *dBdfir, double *dBdz)
WINDLLEXPORT double STDCALL MCM3DXYZ2S (C3dMesh **mConf, double *xyz)
WINDLLEXPORT double STDCALL MCM3DCYL2S (C3dMesh **mConf, double *cyl)
WINDLLEXPORT void STDCALL MCM3DGETGRADS (C3dMesh **mConf, double *cyl, double *grads)
WINDLLEXPORT void STDCALL MCM3DGETGRADSXYZ (C3dMesh **mConf, double *xyz, double *grads)
WINDLLEXPORT void STDCALL MCGETGRADSXYZ (C3dMesh **mConf, double *xyz, double *grads)
WINDLLEXPORT int STDCALL MCXYZISINSIDE (C3dMesh **mConf, double *XYZ)
WINDLLEXPORT int STDCALL MCCYLISINSIDE (C3dMesh **mConf, double *cyl)
WINDLLEXPORT int STDCALL MCWRITEMESH (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT int STDCALL MCWRITE (C3dMesh **mConf, char *fname, int i)
WINDLLEXPORT void STDCALL MCGETALLXYZ (C3dMesh **mConf, double *xyz, double *s, double *B, double *gradS, double *dB)
WINDLLEXPORT void STDCALL MCM3DGETALLXYZ (C3dMesh **mConf, double *xyz, double *S, double *B, double *gradS, double *dB)
WINDLLEXPORT void STDCALL MCM3DGETSBXYZ (C3dMesh **mConf, double *xyz, double *S, double *B)
WINDLLEXPORT void STDCALL MCM3DGETALLCYL (C3dMesh **mConf, double *cyl, double *S, double *B, double *gradS, double *gradB)
WINDLLEXPORT void STDCALL MCM3DGETSBCYL (C3dMesh **mConf, double *cyl, double *S, double *B)
WINDLLEXPORT void STDCALL MCGETBMINMAX (C3dMesh **mConf, double *s, double *Bmin, double *Bmax)
WINDLLEXPORT void STDCALL MCGETBMINMAXGLOBAL (C3dMesh **mConf, double *Bmin, double *Bmax)
WINDLLEXPORT double STDCALL MCBMIN (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCBMAX (C3dMesh **mConf, double *s)
WINDLLEXPORT double STDCALL MCRAXIS (C3dMesh **mConf, double *ficyl)
WINDLLEXPORT void STDCALL MCMAG2CYL (C3dMesh **mConf, double *magCoord, double *cyl)
WINDLLEXPORT void STDCALL MCMAG2XYZ (C3dMesh **mConf, double *magCoord, double *cyl)
WINDLLEXPORT void STDCALL MCMIXCOORD2CYL (C3dMesh **mConf, double *mixCoord, double *cyl)
WINDLLEXPORT void STDCALL MCMIXCOORD2XYZ (C3dMesh **mConf, double *mixCoord, double *xyz)
WINDLLEXPORT void STDCALL MCGETEXTENT (C3dMesh **mConf, double *s, double *fi, double *Rmin, double *Rmax, double *Zmin, double *Zmax)
WINDLLEXPORT void STDCALL MCGETEXTENTLCMS (C3dMesh **mConf, double *Rmin, double *Rmax, double *Zmin, double *Zmax)
WINDLLEXPORT void STDCALL MCM3DSETSMAX (C3dMesh **mConf, double *sMax)
WINDLLEXPORT double STDCALL MCM3DGETSMAX (C3dMesh **mConf)
WINDLLEXPORT int STDCALL MCSAVEREDUCED (C3dMesh **mConf, int *nsmax, double *eps, int *appendWrite, char *fname, int i)
The function transforms the current magnetic configuration to new volume or to new mesh on s.
WINDLLEXPORT void STDCALL MCGETGFACTORS (C3dMesh **mConf, double *s, double *Gw, double *Gs, double *Gv)
The methods return the bounce-averade gradB drift velocity of trapped particles averaged over flux surface.
WINDLLEXPORT void STDCALL MCGETEPSEFF (C3dMesh **mConf, double *s, double *epsEffGraz, double *epsEffDkes, double *epsEffVmec)
The method returns the effective helical ripple for transport.
WINDLLEXPORT void STDCALL MCEPSEFFPARAMS (C3dMesh **mConf, double *xmin, double *xmax, int *maxPoints)
The method sets parameters for calculating eps_eff and Gw, Gs, Gv.
WINDLLEXPORT int STDCALL MCISVMEC (C3dMesh **mConf)
WINDLLEXPORT int STDCALL MCISTOKPEST (C3dMesh **mConf)
WINDLLEXPORT void STDCALL MCPEST2VMEC (C3dMesh **mConf, double *pest, double *vmec)
WINDLLEXPORT void STDCALL MCVMEC2PEST (C3dMesh **mConf, double *vmec, double *pest)
WINDLLEXPORT void STDCALL MCBOOZER2VMEC (C3dMesh **mConf, double *boozer, double *vmec)
WINDLLEXPORT void STDCALL MCVMEC2BOOZER (C3dMesh **mConf, double *vmec, double *boozer)
WINDLLEXPORT void STDCALL SETARGV (int n, char *opt, int i)
WINDLLEXPORT void STDCALL MCJINVARIANT (C3dMesh **mConf, double *mag, double *dphi, int *iotaDenominator, double *Jinv, double *Tbounce, double *Bt)
The method returns the parallel adiabatic invariant with the integral taken between two turning points according formula .
WINDLLEXPORT void STDCALL MCGETMAGCOORDATB (C3dMesh **mConf, double *mag, double *Bt, double *magBt)
The method returns the magnetic coordinates of the point (that belongs to the given field line) at which the magnetic field is equal to the given value.
WINDLLEXPORT void STDCALL MCUSEMIXEDPRODUCTFORJACOBIAN (C3dMesh **mConf, int *yesNo)
If yesNo>0 then the method forces to use Jacobian=dX/dFlux*(dX/dtheta^dX/dphi) for calculating B field.
Variables
static const double pi = 3.14159265358979323846
static const double degree = pi/180
Define Documentation
#define NOMIXED_STR_LEN_ARG
Definition at line 70 of file cpp2for.cpp.
Function Documentation
static const int True (1) [static]
Examples:
cpp2for.cpp.
Referenced by M3DgetRayEntryPoint(), MC_load(), MCCREATEBORDER(), MCcreateMesh(), MCCREATEMESH(), MCcreateMeshUsingSymmetry(), MCCREATEMESHUSINGSYMMETRY(), MCCYLISINSIDE(), MCgetRayIntersectionPoints(), MCISINSIDEBORDER(), MCISMESHOK(), MCISOK(), MCISTOKPEST(), MCISVMEC(), MCM3DGETRAYENTRYPOINT(), MCSAVEREDUCED(), MCWRITE(), MCWRITEMESH(), and MCXYZISINSIDE().
static const int False (0) [static]
Examples:
cpp2for.cpp.
Referenced by M3DgetRayEntryPoint(), MC_load(), MCCREATEBORDER(), MCcreateMesh(), MCCREATEMESH(), MCcreateMeshUsingSymmetry(), MCCREATEMESHUSINGSYMMETRY(), MCCYLISINSIDE(), MCgetRayIntersectionPoints(), MCISINSIDEBORDER(), MCISMESHOK(), MCISOK(), MCISTOKPEST(), MCISVMEC(), MCM3DGETRAYENTRYPOINT(), MCSAVEREDUCED(), MCWRITE(), MCWRITEMESH(), and MCXYZISINSIDE().
static T mmin (T x, T y) [static]
Examples:
cpp2for.cpp.
Definition at line 263 of file cpp2for.cpp.
static T mmax (T x, T y) [static]
Examples:
cpp2for.cpp, and remesh.cpp.
Definition at line 264 of file cpp2for.cpp.
static void strtrim (char * f) [static]
Examples:
cpp2for.cpp.
Definition at line 266 of file cpp2for.cpp.
Referenced by MC_load(), MCSAVEREDUCED(), MCWRITE(), MCWRITEMESH(), and SETARGV().
static void strtrim (char * dest, char * fname, int i) [static]
Definition at line 278 of file cpp2for.cpp.
WINDLLEXPORT double STDCALL PROFILEFUNCTION (double * x, double * g)
Examples:
cpp2for.cpp.
Definition at line 292 of file cpp2for.cpp.
References CPfunction::PF().
WINDLLEXPORT void STDCALL MCFREE (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 300 of file cpp2for.cpp.
WINDLLEXPORT C3dMesh* STDCALL MCCLONE (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 308 of file cpp2for.cpp.
References C3dMesh::clone().
static int MC_load (C3dMesh ** mConf, char * fname, int i, CStconfig::fileFormat fmt) [static]
Examples:
cpp2for.cpp.
Definition at line 321 of file cpp2for.cpp.
References False(), C3dMesh::load(), strtrim(), and True().
Referenced by MCLOAD(), MCLOADEFIT(), MCLOADLHD(), and MCLOADVMEC().
WINDLLEXPORT int STDCALL MCLOAD (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 344 of file cpp2for.cpp.
References MC_load().
WINDLLEXPORT int STDCALL MCLOADVMEC (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 349 of file cpp2for.cpp.
References MC_load().
WINDLLEXPORT int STDCALL MCLOADLHD (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 359 of file cpp2for.cpp.
References MC_load().
WINDLLEXPORT int STDCALL MCLOADEFIT (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 364 of file cpp2for.cpp.
References MC_load().
WINDLLEXPORT int STDCALL MCISMESHOK (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 370 of file cpp2for.cpp.
References False(), C3dMesh::isMeshOK(), and True().
WINDLLEXPORT int STDCALL MCISOK (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 377 of file cpp2for.cpp.
References False(), CStconfig::isOK(), and True().
WINDLLEXPORT void STDCALL MCTRUNCATE (C3dMesh ** mConf, double * epsTrunc)
Examples:
cpp2for.cpp.
Definition at line 385 of file cpp2for.cpp.
References CStconfig::truncate().
WINDLLEXPORT void STDCALL MCSETACCURACY (C3dMesh ** mConf, double * epsA)
Examples:
cpp2for.cpp.
Definition at line 393 of file cpp2for.cpp.
References CStconfig::setAccuracy().
WINDLLEXPORT void STDCALL MCSETB0 (C3dMesh ** mConf, double * b, double * ficyl)
Examples:
cpp2for.cpp.
Definition at line 401 of file cpp2for.cpp.
References C3dMesh::setB0().
WINDLLEXPORT void STDCALL MCSETMINB0 (C3dMesh ** mConf, double * b)
Examples:
cpp2for.cpp.
Definition at line 409 of file cpp2for.cpp.
References C3dMesh::setB0().
WINDLLEXPORT double STDCALL MCGETB0 (C3dMesh ** mConf, double * ficyl)
Examples:
cpp2for.cpp.
Definition at line 417 of file cpp2for.cpp.
References CStconfig::getB0().
WINDLLEXPORT void STDCALL MCSETB00 (C3dMesh ** mConf, double * b)
Examples:
cpp2for.cpp.
Definition at line 425 of file cpp2for.cpp.
References C3dMesh::setB00().
WINDLLEXPORT void STDCALL MCSETICOIL (C3dMesh ** mConf, double * I)
Examples:
cpp2for.cpp.
Definition at line 433 of file cpp2for.cpp.
References C3dMesh::setIcoil().
WINDLLEXPORT void STDCALL MCSETBDIRECTION (C3dMesh ** mConf, int * dir)
Examples:
cpp2for.cpp.
Definition at line 441 of file cpp2for.cpp.
References CStconfig::setBdirection().
WINDLLEXPORT int STDCALL MCGETBDIRECTION (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 449 of file cpp2for.cpp.
References CStconfig::getBdirection().
WINDLLEXPORT void STDCALL MCRESTOREBDIRECTION (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 457 of file cpp2for.cpp.
References CStconfig::restoreBdirection().
WINDLLEXPORT double STDCALL MCGETB00 (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 465 of file cpp2for.cpp.
References CStconfig::getB00().
WINDLLEXPORT void STDCALL MCSFLCOORDONBLINEATTHETA (C3dMesh ** mConf, const double * pest0, const double * thetaStar, double * pest)
Examples:
cpp2for.cpp.
Definition at line 475 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::SFLcoordOnBlineAtTheta().
WINDLLEXPORT void STDCALL MCSFLCONTRABASIS (C3dMesh ** mConf, const double * pest, double * gradS, double * gradThetaStar, double * gradPhi, double * mag)
Examples:
cpp2for.cpp.
Definition at line 491 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::SFLcontraBasis().
WINDLLEXPORT void STDCALL MCBOOZERCONTRABASIS (C3dMesh ** mConf, const double * u, double * gradS, double * gradThetaStar, double * gradPhi, double * mag)
Examples:
cpp2for.cpp.
Definition at line 511 of file cpp2for.cpp.
References CStconfig::BoozerContraBasis(), and Vector3d::copyTo().
WINDLLEXPORT void STDCALL MCGETBANDGRADIENTS (C3dMesh ** mConf, double * magCoord, double * B, double * gradB, double * gradF, double * gradTh, double * gradPh)
Examples:
cpp2for.cpp.
Definition at line 532 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::Flux(), and CStconfig::getBandGradients().
WINDLLEXPORT void STDCALL MCGETBCURLBGRADFCYL (C3dMesh ** mConf, double * u, double * B, double * curlB, double * gradF)
The method returns B and curl(B) in cylindrical coordinates.
Parameters:
[in] mConf is the pointer to memory at which the address of C3dMesh-object is stored.
[in] u is the point (s,theta,phi) in magnetic coordinates.
[out] B is the magnetic field in cylindrical coordinates.
[out] curlB is the curl(B).
[out] gradF is the grad(torFlux)
Examples:
cpp2for.cpp.
Definition at line 555 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::Flux(), and CStconfig::getBcurlBGradscyl().
WINDLLEXPORT void STDCALL MCGETGRADB (C3dMesh ** mConf, double * magCoord, double * gradB)
Examples:
cpp2for.cpp.
Definition at line 574 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::gradB(), and Vector3d::setFrom().
WINDLLEXPORT void STDCALL MCGETCOVAGRADB (C3dMesh ** mConf, double * magCoord, double * gradB)
Examples:
cpp2for.cpp.
Definition at line 586 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::getCovaGradB(), and Vector3d::setFrom().
WINDLLEXPORT void STDCALL MCSCALEB (C3dMesh ** mConf, double * factor)
Examples:
cpp2for.cpp.
Definition at line 597 of file cpp2for.cpp.
References C3dMesh::scaleB().
WINDLLEXPORT void STDCALL MCCYL2MAG (C3dMesh ** mConf, double * cyl, double * magCoord, double * Bfield)
Examples:
cpp2for.cpp.
Definition at line 611 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::cyl2mag(), CStconfig::cylIsInside(), CStconfig::getBcyl(), and Vector3d::setFrom().
WINDLLEXPORT void STDCALL MCCYL2MAG2 (C3dMesh ** mConf, double * cyl, double * magCoord, double * Bfield)
Examples:
cpp2for.cpp.
Definition at line 638 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::cyl2mag(), and CStconfig::getBcyl().
WINDLLEXPORT void STDCALL MCXYZ2MAG2 (C3dMesh ** mConf, double * xyz, double * magCoord, double * Bfield)
Examples:
cpp2for.cpp.
Definition at line 655 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::getBxyz(), and CStconfig::xyz2mag().
WINDLLEXPORT double STDCALL MCXYZ2S (C3dMesh ** mConf, double * xyz)
Examples:
cpp2for.cpp.
Definition at line 674 of file cpp2for.cpp.
References CStconfig::xyz2s().
WINDLLEXPORT double STDCALL MCCYL2S (C3dMesh ** mConf, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 689 of file cpp2for.cpp.
References CStconfig::cyl2s().
WINDLLEXPORT void STDCALL MCGETSBXYZ (C3dMesh ** mConf, double * xyz, double * S, double * B)
Examples:
cpp2for.cpp.
Definition at line 697 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::getBxyz(), and CStconfig::xyz2s().
WINDLLEXPORT void STDCALL MCGETSBCYL (C3dMesh ** mConf, double * cyl, double * S, double * B)
Examples:
cpp2for.cpp.
Definition at line 707 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::cyl2s(), and CStconfig::getBcyl().
WINDLLEXPORT void STDCALL MCGETBCYL (C3dMesh ** mConf, double * magCoord, double * B)
Examples:
cpp2for.cpp.
Definition at line 722 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::getBcyl(), and CStconfig::NJacobian().
WINDLLEXPORT double STDCALL MCTORFLUX (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 733 of file cpp2for.cpp.
References CStconfig::Flux().
WINDLLEXPORT int STDCALL MCCURRENTSIGNTOINCREASEIOTA (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 744 of file cpp2for.cpp.
References CStconfig::getSignOfCurrentThatIncreasesAbsIota().
WINDLLEXPORT double STDCALL MCREFF (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 752 of file cpp2for.cpp.
References CStconfig::r().
WINDLLEXPORT double STDCALL MCVPRIME (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 761 of file cpp2for.cpp.
References CStconfig::Vprime().
WINDLLEXPORT double STDCALL MCVOLUME (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 770 of file cpp2for.cpp.
References CStconfig::Volume().
WINDLLEXPORT double STDCALL MCFTRAPPED (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 778 of file cpp2for.cpp.
References CStconfig::ftrapped().
WINDLLEXPORT double STDCALL MCBAVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 786 of file cpp2for.cpp.
References CStconfig::Bavrg().
WINDLLEXPORT double STDCALL MCB2AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 794 of file cpp2for.cpp.
References CStconfig::B2avrg().
WINDLLEXPORT double STDCALL MCB_2AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 802 of file cpp2for.cpp.
References CStconfig::B_2avrg().
WINDLLEXPORT double STDCALL MCGRADS2B_2AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 810 of file cpp2for.cpp.
References CStconfig::grads2B_2avrg().
WINDLLEXPORT double STDCALL MCR2AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 818 of file cpp2for.cpp.
References CStconfig::R2avrg().
WINDLLEXPORT double STDCALL MCR_2AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 826 of file cpp2for.cpp.
References CStconfig::R_2avrg().
WINDLLEXPORT double STDCALL MCNEOPOLARIZATION (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 834 of file cpp2for.cpp.
References CStconfig::NeoPolarization().
WINDLLEXPORT double STDCALL MCNEOPOLARIZATIONPASS (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 842 of file cpp2for.cpp.
References CStconfig::NeoPolarizationPass().
WINDLLEXPORT double STDCALL MCNEOPOLARIZATIONTRAP (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 850 of file cpp2for.cpp.
References CStconfig::NeoPolarizationTrap().
WINDLLEXPORT double STDCALL MCBPHI (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 859 of file cpp2for.cpp.
References CStconfig::Ip(), pi, and mathf::twopi.
WINDLLEXPORT double STDCALL MCIPOL (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 871 of file cpp2for.cpp.
References CStconfig::Ip().
WINDLLEXPORT double STDCALL MCITOR (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 879 of file cpp2for.cpp.
References CStconfig::It().
WINDLLEXPORT double STDCALL MCB (C3dMesh ** mConf, double * s, double * polAngle, double * torAngle)
Examples:
cpp2for.cpp.
Definition at line 887 of file cpp2for.cpp.
References CStconfig::B().
WINDLLEXPORT double STDCALL MCJACOBIAN (C3dMesh ** mConf, double * s, double * polAngle, double * torAngle)
Examples:
cpp2for.cpp.
Definition at line 896 of file cpp2for.cpp.
References CStconfig::Jacobian().
WINDLLEXPORT void STDCALL MCBANDJACOBIAN (C3dMesh ** mConf, double * s, double * polAngle, double * torAngle, double * B, double * jac)
Examples:
cpp2for.cpp.
Definition at line 906 of file cpp2for.cpp.
References CStconfig::Jacobian().
WINDLLEXPORT double STDCALL MCRHPOTENCIAL (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 918 of file cpp2for.cpp.
References CStconfig::B_2avrg(), CStconfig::Ip(), CStconfig::NeoPolarization(), pi, CStconfig::R2avrg(), and mathf::twopi.
WINDLLEXPORT double STDCALL MCDB12AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 934 of file cpp2for.cpp.
References CStconfig::db12Avrg().
WINDLLEXPORT double STDCALL MCDB32AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 942 of file cpp2for.cpp.
References CStconfig::db32Avrg().
WINDLLEXPORT double STDCALL MCBDB12AVRG (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 950 of file cpp2for.cpp.
References CStconfig::db12Avrg(), and CStconfig::db32Avrg().
WINDLLEXPORT double STDCALL MCROPARINVAVRG (C3dMesh ** mConf, double * s, double * x)
Examples:
cpp2for.cpp.
Definition at line 959 of file cpp2for.cpp.
References CStconfig::roParInvAvrg().
WINDLLEXPORT double STDCALL MCPAVRG (C3dMesh ** mConf, double * s, double * x)
Examples:
cpp2for.cpp.
Definition at line 969 of file cpp2for.cpp.
References CStconfig::pavrg().
WINDLLEXPORT double STDCALL MCINTINVPAVRG (C3dMesh ** mConf, double * s, double * x)
Examples:
cpp2for.cpp.
Definition at line 978 of file cpp2for.cpp.
References CStconfig::integralInvPavrg().
WINDLLEXPORT double STDCALL MCIOTA (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 996 of file cpp2for.cpp.
References CStconfig::iota().
WINDLLEXPORT double STDCALL MCIOTAPRIME (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1004 of file cpp2for.cpp.
References CStconfig::iotaPrime().
WINDLLEXPORT double STDCALL MCPRESSUREPRIME (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1012 of file cpp2for.cpp.
References CStconfig::pp().
WINDLLEXPORT double STDCALL MCPRESSURE (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1020 of file cpp2for.cpp.
References CStconfig::pressure().
WINDLLEXPORT double STDCALL MCTORFLUX2POLFLUX (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1028 of file cpp2for.cpp.
References CStconfig::sPol().
WINDLLEXPORT double STDCALL MCR0 (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1036 of file cpp2for.cpp.
References CStconfig::R0().
WINDLLEXPORT double STDCALL MCRMN (C3dMesh ** mConf, int * m, int * n, double * s)
Examples:
cpp2for.cpp.
Definition at line 1044 of file cpp2for.cpp.
References CStconfig::Rmn_sp().
WINDLLEXPORT double STDCALL MCZMN (C3dMesh ** mConf, int * m, int * n, double * s)
Examples:
cpp2for.cpp.
Definition at line 1052 of file cpp2for.cpp.
References CStconfig::Zmn_sp().
WINDLLEXPORT double STDCALL MCFMN (C3dMesh ** mConf, int * m, int * n, double * s)
Examples:
cpp2for.cpp.
Definition at line 1060 of file cpp2for.cpp.
References CStconfig::Phimn_sp().
WINDLLEXPORT double STDCALL MCBMN (C3dMesh ** mConf, int * m, int * n, double * s)
Examples:
cpp2for.cpp.
Definition at line 1068 of file cpp2for.cpp.
References CStconfig::Bmn_sp().
WINDLLEXPORT double STDCALL MCBOOZERBMN (C3dMesh ** mConf, int * m, int * n, double * s)
Examples:
cpp2for.cpp.
Definition at line 1076 of file cpp2for.cpp.
References CStconfig::BoozerBmn().
WINDLLEXPORT double STDCALL MCAVERAGECROSSSECTIONAREA (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1085 of file cpp2for.cpp.
References CStconfig::averageCrossSectionArea().
WINDLLEXPORT double STDCALL MCRMINOR (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1093 of file cpp2for.cpp.
References CStconfig::rminor().
WINDLLEXPORT int STDCALL MCNPERIODS (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1101 of file cpp2for.cpp.
References CStconfig::nPeriods().
WINDLLEXPORT int STDCALL MCTRACELCMS (C3dMesh ** mConf, double * R1, double * R2, double * Entry, double * Exit)
The method traces the Last Closed Magnetic Surface (LCMS).
The method finds intersections of the ray with the LCMS, where the ray is R(t)=r1+(r2-r1)/|r2-r1|*t, and t>=0.
Parameters:
mConf is the address of the variable which contains the address of C3dMesh-object
R1 is the cartesian coordinates of the first point of the ray, must be outside with respect to the LCMS.
R2 is the cartesian coordinates of the second point of the ray
Entry this vector at return contains the coordinates of the entry point of the ray into plasma
Exit this vector at return contains the coordinates of the exit point
Returns:
-2 -- the origin r1 of the ray lies inside LCMS;
-1 -- the ray does not enters into plasma;
0 -- segment r1--r2 is outside plasma;
1 -- only entry point lies on the segment r1--r2, i.e. r2 is inside plasma;
2 -- entry and exit points lie on the segment r1--r2, i.e. r1 and r2 are outside plasma;
if returned value >= 0 then entry and exit points of the ray are in entrypoint and exitpoint
Examples:
cpp2for.cpp.
Definition at line 1135 of file cpp2for.cpp.
References Vector3d::abs(), Vector3d::copyTo(), degree, CRayTrace::getTraceRxyz(), CRayTrace::getTraceSize(), CStconfig::isOK(), CRayTrace::traceLast(), and CStconfig::xyzIsInside().
WINDLLEXPORT int STDCALL MCM3DGETRAYENTRYPOINT (C3dMesh ** mConf, double * r0, double * rd, double * entryPoint)
Examples:
cpp2for.cpp.
Definition at line 1183 of file cpp2for.cpp.
References Vector3d::copyTo(), False(), C3dMesh::M3DgetRayEntryPoint(), and True().
WINDLLEXPORT int STDCALL MCCREATEBORDER (C3dMesh ** mConf, double * slast, double * ficyl, int * BrdSize)
Examples:
cpp2for.cpp.
Definition at line 1199 of file cpp2for.cpp.
References CStconfig::createBorder(), False(), and True().
WINDLLEXPORT int STDCALL MCISINSIDEBORDER (C3dMesh ** mConf, double * XYZ)
Examples:
cpp2for.cpp.
Definition at line 1213 of file cpp2for.cpp.
References CStconfig::cylIsInsideBorder(), False(), CStconfig::mod2pi(), True(), Vector3d::x(), Vector3d::y(), and Vector3d::z().
WINDLLEXPORT void STDCALL MCGETDBCYL (C3dMesh ** mConf, double * cyl, double * B, double * dBdr, double * dBdfir, double * dBdz)
Examples:
cpp2for.cpp.
Definition at line 1236 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::getdBGradscyl().
WINDLLEXPORT void STDCALL MCCOORDFIELDLINE (C3dMesh ** mConf, double * mixCoord0, double * fcyl, double * magCoord)
The method returns magnetic coordinates of the point of a field line, that passes through the given point (s0,theta0,ficyl0).
The method calculates function
where is non zero for VMEC coordinates.
Parameters:
mConf is the address of the variable which contains the address of C3dMesh-object
[in] mixCoord0 is the point of B-line in mixed coordinates, where s and theta coincide with correspondent magnetic coordinates, but toroidal angle is cylindricyl angle
[in] fcyl is the cylindricyl angle
[out] magCoord is the magCoord(s0,theta(ficyl),phi(ficyl))
Examples:
cpp2for.cpp.
Definition at line 1260 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::mixCoordFieldLine().
WINDLLEXPORT int STDCALL MCCREATEMESH (C3dMesh ** mConf, double * dr, double * dz, double * dfi)
Examples:
cpp2for.cpp.
Definition at line 1274 of file cpp2for.cpp.
References C3dMesh::createMesh(), False(), and True().
WINDLLEXPORT int STDCALL MCCREATEMESHUSINGSYMMETRY (C3dMesh ** mConf, double * dr, double * dz, double * dfi)
Examples:
cpp2for.cpp.
Definition at line 1284 of file cpp2for.cpp.
References C3dMesh::createMeshUsingSymmetry(), False(), and True().
WINDLLEXPORT void STDCALL MCM3DGETDBXYZ (C3dMesh ** mConf, double * xyz, double * B, double * dBdx, double * dBdy, double * dBdz)
Examples:
cpp2for.cpp.
Definition at line 1302 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetdBxyz().
WINDLLEXPORT void STDCALL MCM3DGETDBCYL (C3dMesh ** mConf, double * cyl, double * B, double * dBdr, double * dBdfir, double * dBdz)
Examples:
cpp2for.cpp.
Definition at line 1327 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetdBcyl().
WINDLLEXPORT double STDCALL MCM3DXYZ2S (C3dMesh ** mConf, double * xyz)
Examples:
cpp2for.cpp.
Definition at line 1350 of file cpp2for.cpp.
References C3dMesh::M3Dxyz2s().
WINDLLEXPORT double STDCALL MCM3DCYL2S (C3dMesh ** mConf, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 1364 of file cpp2for.cpp.
References C3dMesh::M3Dcyl2s().
WINDLLEXPORT void STDCALL MCM3DGETGRADS (C3dMesh ** mConf, double * cyl, double * grads)
Examples:
cpp2for.cpp.
Definition at line 1377 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetGrads().
WINDLLEXPORT void STDCALL MCM3DGETGRADSXYZ (C3dMesh ** mConf, double * xyz, double * grads)
Examples:
cpp2for.cpp.
Definition at line 1391 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetGradsxyz().
WINDLLEXPORT void STDCALL MCGETGRADSXYZ (C3dMesh ** mConf, double * xyz, double * grads)
Examples:
cpp2for.cpp.
Definition at line 1405 of file cpp2for.cpp.
References Vector3d::copyTo(), CStconfig::getGradsxyz(), and CStconfig::xyz2s().
WINDLLEXPORT int STDCALL MCXYZISINSIDE (C3dMesh ** mConf, double * XYZ)
Examples:
cpp2for.cpp.
Definition at line 1418 of file cpp2for.cpp.
References False(), True(), and CStconfig::xyzIsInside().
WINDLLEXPORT int STDCALL MCCYLISINSIDE (C3dMesh ** mConf, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 1431 of file cpp2for.cpp.
References CStconfig::cylIsInside(), False(), and True().
WINDLLEXPORT int STDCALL MCWRITEMESH (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 1442 of file cpp2for.cpp.
References False(), strtrim(), True(), and C3dMesh::writeMesh().
WINDLLEXPORT int STDCALL MCWRITE (C3dMesh ** mConf, char * fname, int i)
Examples:
cpp2for.cpp.
Definition at line 1457 of file cpp2for.cpp.
References False(), strtrim(), True(), and CStconfig::write().
WINDLLEXPORT void STDCALL MCGETALLXYZ (C3dMesh ** mConf, double * xyz, double * s, double * B, double * gradS, double * dB)
Examples:
cpp2for.cpp.
Definition at line 1482 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::getdBGradsxyz().
WINDLLEXPORT void STDCALL MCM3DGETALLXYZ (C3dMesh ** mConf, double * xyz, double * S, double * B, double * gradS, double * dB)
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<1.5 means that point lies outside LCMS in the extrapolated region;
s>1000 means that point lies far outside from LCMS;
Examples:
cpp2for.cpp.
Definition at line 1513 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetdBGradsxyz().
WINDLLEXPORT void STDCALL MCM3DGETSBXYZ (C3dMesh ** mConf, double * xyz, double * S, double * B)
Examples:
cpp2for.cpp.
Definition at line 1537 of file cpp2for.cpp.
References C3dMesh::M3DgetBxyz(), and C3dMesh::M3Dxyz2s().
WINDLLEXPORT void STDCALL MCM3DGETALLCYL (C3dMesh ** mConf, double * cyl, double * S, double * B, double * gradS, double * gradB)
Returns:
s (normalized toroidal flux), which normally satisfies 0<=s<=1;
1<s<1.5 means that point lies outside LCMS in the extrapolated region;
s>1000 means that point lies far outside from LCMS;
Examples:
cpp2for.cpp.
Definition at line 1551 of file cpp2for.cpp.
References Vector3d::copyTo(), and C3dMesh::M3DgetdBGradscyl().
WINDLLEXPORT void STDCALL MCM3DGETSBCYL (C3dMesh ** mConf, double * cyl, double * S, double * B)
Examples:
cpp2for.cpp.
Definition at line 1574 of file cpp2for.cpp.
References CStconfig::cyl2s(), C3dMesh::M3Dcyl2s(), and C3dMesh::M3DgetBcyl().
WINDLLEXPORT void STDCALL MCGETBMINMAX (C3dMesh ** mConf, double * s, double * Bmin, double * Bmax)
Examples:
cpp2for.cpp.
Definition at line 1586 of file cpp2for.cpp.
References CStconfig::Bmax(), and CStconfig::Bmin().
WINDLLEXPORT void STDCALL MCGETBMINMAXGLOBAL (C3dMesh ** mConf, double * Bmin, double * Bmax)
Examples:
cpp2for.cpp.
Definition at line 1601 of file cpp2for.cpp.
References CStconfig::Bmax(), and CStconfig::Bmin().
WINDLLEXPORT double STDCALL MCBMIN (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1610 of file cpp2for.cpp.
References CStconfig::Bmin().
WINDLLEXPORT double STDCALL MCBMAX (C3dMesh ** mConf, double * s)
Examples:
cpp2for.cpp.
Definition at line 1619 of file cpp2for.cpp.
References CStconfig::Bmax().
WINDLLEXPORT double STDCALL MCRAXIS (C3dMesh ** mConf, double * ficyl)
Examples:
cpp2for.cpp.
Definition at line 1629 of file cpp2for.cpp.
References CStconfig::mixcoord2cyl().
WINDLLEXPORT void STDCALL MCMAG2CYL (C3dMesh ** mConf, double * magCoord, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 1637 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::mag2cyl().
WINDLLEXPORT void STDCALL MCMAG2XYZ (C3dMesh ** mConf, double * magCoord, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 1647 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::mag2xyz().
WINDLLEXPORT void STDCALL MCMIXCOORD2CYL (C3dMesh ** mConf, double * mixCoord, double * cyl)
Examples:
cpp2for.cpp.
Definition at line 1662 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::mixcoord2cyl().
WINDLLEXPORT void STDCALL MCMIXCOORD2XYZ (C3dMesh ** mConf, double * mixCoord, double * xyz)
Examples:
cpp2for.cpp.
Definition at line 1676 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::mixcoord2xyz().
WINDLLEXPORT void STDCALL MCGETEXTENT (C3dMesh ** mConf, double * s, double * fi, double * Rmin, double * Rmax, double * Zmin, double * Zmax)
Examples:
cpp2for.cpp.
Definition at line 1686 of file cpp2for.cpp.
References CStconfig::getExtent().
WINDLLEXPORT void STDCALL MCGETEXTENTLCMS (C3dMesh ** mConf, double * Rmin, double * Rmax, double * Zmin, double * Zmax)
Examples:
cpp2for.cpp.
Definition at line 1695 of file cpp2for.cpp.
References CStconfig::getExtentLCMS().
WINDLLEXPORT void STDCALL MCM3DSETSMAX (C3dMesh ** mConf, double * sMax)
Examples:
cpp2for.cpp.
Definition at line 1704 of file cpp2for.cpp.
References C3dMesh::setsMax().
WINDLLEXPORT double STDCALL MCM3DGETSMAX (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1712 of file cpp2for.cpp.
References C3dMesh::getsMax().
WINDLLEXPORT int STDCALL MCSAVEREDUCED (C3dMesh ** mConf, int * nsmax, double * eps, int * appendWrite, char * fname, int i)
The function transforms the current magnetic configuration to new volume or to new mesh on s.
Parameters:
[in] mConf is the pointer to memory at which the address of C3dMesh-object is stored,
[in] *nsmax is the number of surfaces to store, if zero then the original flux surfaces are stored, otherwise store the surfaces using a new mesh which is equidistant on sqrt(s).
[in] *eps is the truncation level to reduce the number of harmonics used in summation, the only harmonics with m<M and |n|<N satisfying Bmn/B00 > eps are used in summation, eps<=1e-6 is a good choice.
[in] *appendWrite if true then the magnetic configuration is appended to a file set by next parameter,
[in] fname is the filename under which the configuration is saved.
[in] i is the strlen(fname), skip this parameter if this function is called from fortran.
Returns:
if the method succeeds, the return value is 1; 0 otherwise.
Examples:
cpp2for.cpp.
Definition at line 1732 of file cpp2for.cpp.
References False(), strtrim(), True(), CStconfig::truncate(), and CStconfig::writeasciiReduced().
WINDLLEXPORT void STDCALL MCGETGFACTORS (C3dMesh ** mConf, double * s, double * Gw, double * Gs, double * Gv)
The methods return the bounce-averade gradB drift velocity of trapped particles averaged over flux surface.
See eq(21,26,28) for Gw,Gs,Gv in Physics of Plasmas 12,112507(2005), http://link.aip.org/link/doi/10.1063/1.2131848
Examples:
cpp2for.cpp.
Definition at line 1755 of file cpp2for.cpp.
References CStconfig::Gs(), CStconfig::Gv(), and CStconfig::Gw().
WINDLLEXPORT void STDCALL MCGETEPSEFF (C3dMesh ** mConf, double * s, double * epsEffGraz, double * epsEffDkes, double * epsEffVmec)
The method returns the effective helical ripple for transport.
See also:
V.V.Nemov, S.V.Kasilov, W. Kernbichler, and M.F.Heyn, Physics of Plasmas, vol. 6, 4622(1999), http://link.aip.org/link/PHPAEN/v6/i12/p4622/s1
28th EPS, http://epsppd.epfl.ch/Madeira/html/pdf/P5.055.pdf , EGA Vol.25A (2001) 1985-1988
Parameters:
[in] mConf is the pointer to memory at which the address of C3dMesh-object is stored,
[in] s is the normalized toroidal flux
[out] epsEffGraz -- using Graz definition of the minor radius dr=ds/<|grad(s)|>,
[out] epsEffDkes -- using DKES definition of minor radius r=sqrt(Flux(s)/(pi*B_00(s))),
[out] epsEffVmec -- using VMEC definition of minor radius r=a*sqrt(s),
Examples:
cpp2for.cpp.
Definition at line 1773 of file cpp2for.cpp.
References CStconfig::epsEffDkes(), CStconfig::epsEffGraz(), and CStconfig::epsEffVmec().
WINDLLEXPORT void STDCALL MCEPSEFFPARAMS (C3dMesh ** mConf, double * xmin, double * xmax, int * maxPoints)
The method sets parameters for calculating eps_eff and Gw, Gs, Gv.
Parameters:
xmin is the minimal value of sqrt(s), where s is the normalized toroidal flux,
xmax is the maximal value of sqrt(s),
maxPoints is the number of points for creating look-up table
Examples:
cpp2for.cpp.
Definition at line 1788 of file cpp2for.cpp.
References CStconfig::epsEffSetXeffParam().
WINDLLEXPORT int STDCALL MCISVMEC (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1795 of file cpp2for.cpp.
References False(), CStconfig::isVmecCoordinates(), and True().
WINDLLEXPORT int STDCALL MCISTOKPEST (C3dMesh ** mConf)
Examples:
cpp2for.cpp.
Definition at line 1802 of file cpp2for.cpp.
References False(), CStconfig::isTokamakSymmetryFluxCoordinates(), and True().
WINDLLEXPORT void STDCALL MCPEST2VMEC (C3dMesh ** mConf, double * pest, double * vmec)
Examples:
cpp2for.cpp.
Definition at line 1810 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::Pest2Vmec().
WINDLLEXPORT void STDCALL MCVMEC2PEST (C3dMesh ** mConf, double * vmec, double * pest)
Examples:
cpp2for.cpp.
Definition at line 1821 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::Vmec2Pest().
WINDLLEXPORT void STDCALL MCBOOZER2VMEC (C3dMesh ** mConf, double * boozer, double * vmec)
Examples:
cpp2for.cpp.
Definition at line 1831 of file cpp2for.cpp.
References CStconfig::Boozer2Vmec(), and Vector3d::copyTo().
WINDLLEXPORT void STDCALL MCVMEC2BOOZER (C3dMesh ** mConf, double * vmec, double * boozer)
Examples:
cpp2for.cpp.
Definition at line 1842 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::Vmec2Boozer().
WINDLLEXPORT void STDCALL SETARGV (int n, char * opt, int i)
Examples:
cpp2for.cpp.
Definition at line 1851 of file cpp2for.cpp.
References strtrim().
WINDLLEXPORT void STDCALL MCJINVARIANT (C3dMesh ** mConf, double * mag, double * dphi, int * iotaDenominator, double * Jinv, double * Tbounce, double * Bt)
The method returns the parallel adiabatic invariant with the integral taken between two turning points according formula .
Parameters:
mag is the magnetic coordinates of the point from which integrating along field line is started and where
dphi is the toroidal step in radians for fild line integration (default value is 0.4degree if dphi==0)
iotaDenominator if not zero then this number is the denominator in iota aproximation by rational number.
[out] Jinv is the array with the parallel adiabatic invariant in the first element, dJ/ds in the second element, dJ/dalpha in the third element
[out] Tbounce is the bounce time , and
[out] Bt is the
See also:
getMagCoordAtB()
Examples:
cpp2for.cpp.
Definition at line 1886 of file cpp2for.cpp.
References CStconfig::Jinvariant().
WINDLLEXPORT void STDCALL MCGETMAGCOORDATB (C3dMesh ** mConf, double * mag, double * Bt, double * magBt)
The method returns the magnetic coordinates of the point (that belongs to the given field line) at which the magnetic field is equal to the given value.
Parameters:
mag defines the field line;
Bt is the magnetic field value, must be within the interval Bmin..Bmax for the considered field line; @param[out] magBt array with the magnetic coordinates at which the magnetic field value is Bt or array with elements (-1,Bmin,Bmax) if Bt is not within the interval Bmin..Bmax;
Note:
the method seaches the point of interest starting from the point where B=Bmin; Bmin is seached within one machine period (0<=phi<2*pi/Np) along given field line.
See also:
Jinvariant(), Bmin(double s), Bmax(double s)
Examples:
cpp2for.cpp.
Definition at line 1908 of file cpp2for.cpp.
References Vector3d::copyTo(), and CStconfig::getMagCoordAtB().
WINDLLEXPORT void STDCALL MCUSEMIXEDPRODUCTFORJACOBIAN (C3dMesh ** mConf, int * yesNo)
If yesNo>0 then the method forces to use Jacobian=dX/dFlux*(dX/dtheta^dX/dphi) for calculating B field.
Examples:
cpp2for.cpp.
Definition at line 1917 of file cpp2for.cpp.
References CStconfig::useMixedProductForJacobian().
Variable Documentation
const double pi = 3.14159265358979323846 [static]
Examples:
2ndexample.cpp, 3dmeshtest.cpp, accuracytest.cpp, cpp2for.cpp, raytrace1.cpp, raytrace2.cpp, and remesh.cpp.
Definition at line 59 of file cpp2for.cpp.
Referenced by MCBPHI(), and MCRHPOTENCIAL().
const double degree = pi/180 [static]
Examples:
1stexample.cpp, 2ndexample.cpp, 3dmeshtest.cpp, accuracytest.cpp, cpp2for.cpp, raytrace1.cpp, and raytrace2.cpp.
Definition at line 60 of file cpp2for.cpp.
Referenced by MCTRACELCMS().
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik