MConf: MConf Namespace Reference
MConf Namespace Reference
Library namespace.
Namespaces
namespace pBase
Container namespace.
Classes
class C3dMesh
This class tabulates magnetic field, flux surface label, grad(s) on a 3d-mesh in cylindrical coordinates and provides functions for interpolation.
class CArray1d
This class provides 1d-array.
class CArray2d
This class provides 2d-array.
class CArray3d
This class provides 3d-array.
class CBtrace
The class is used for B-field line tracing.
class CEfit
Helper class that reads EFIT GEQDSK file and transforms it to the Tokamak Symmetry flux coordinates.
class CPfunction
This class provides the function for creating a plasma profile.
class CProfile
This class provides the plasma profile which can be set by set of points or parameterized by CPfunction().
class CRayTrace
Find intersections of straight ray with the flux surfaces, this class is obsolete.
class CStconfig
Magnetic configuration of a stellarator.
class Vector3d
This class provides 3d-vector type.
class RightHandSide
class rkf45
Fehlberg fourth-fifth order Runge-Kutta method.
class Threads
class Threads2
Functions
uiThread ui_beginthreadex (void *(*f)(void *), void *p)
void ui_waitthread (uiThread thread)
void ui_endthreadex (void *retval)
uiMutex ui_mutex_init ()
int ui_mutex_lock (uiMutex mutex)
int ui_mutex_unlock (uiMutex mutex)
void ui_mutex_destroy (uiMutex mutex)
Variables
static const int nODE = 2
static const double ATOL = 1e-10
static const double RTOL = 1e-10
Detailed Description
Library namespace.
Function Documentation
uiThread MConf::ui_beginthreadex (void *(*)(void *) f, void * p)
Definition at line 75 of file threads.h.
Referenced by Threads2< T, TR >::run(), and Threads< T >::run().
void MConf::ui_waitthread (uiThread thread)
Definition at line 87 of file threads.h.
Referenced by Threads2< T, TR >::run(), and Threads< T >::run().
void MConf::ui_endthreadex (void * retval)
Definition at line 91 of file threads.h.
uiMutex MConf::ui_mutex_init ()
Definition at line 93 of file threads.h.
Referenced by Threads2< T, TR >::run().
int MConf::ui_mutex_lock (uiMutex mutex)
Definition at line 101 of file threads.h.
int MConf::ui_mutex_unlock (uiMutex mutex)
Definition at line 102 of file threads.h.
void MConf::ui_mutex_destroy (uiMutex mutex)
Definition at line 103 of file threads.h.
Referenced by Threads2< T, TR >::run().
Variable Documentation
const int nODE = 2 [static]
Definition at line 11 of file CBtrace.h.
const double ATOL = 1e-10 [static]
Definition at line 12 of file CBtrace.h.
const double RTOL = 1e-10 [static]
Definition at line 13 of file CBtrace.h.
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik