MConf: mathf Namespace Reference
mathf Namespace Reference
Classes
class StopWatch
StopWatch provides functions for timings 2006.12.28 turkin 2007.09.12.
class vectorOfPtr
The class provides vector of pointers to simplify dealocation.
class autoPtr
Functions
static double wall_clock ()
template<class T >
T cube (T x)
template<class T >
T square (T x)
template<class T >
T mmin (T x, T y)
template<class T >
T mmax (T x, T y)
template<class T >
T clamp (T x, T a, T b)
template<class T >
void swap (T &v1, T &v2)
template<class T >
int sign (T x)
template<class T >
double modpi (T x)
template<class T >
double modPeriod (T x, double mPeriod)
template<class T >
std::string itoa (T value, int base)
static void getPathNameExt (std::string &fullname, std::string &path, std::string &name, std::string &ext)
static int isDir (const char *path)
static std::string createTempSubdir (std::string &subdir)
static std::string createUniqueFilename (const std::string &name)
static std::string createUniqueSubdir (const std::string &path, const std::string &subdir)
static std::string createOutputDir (std::string &outputFile)
Variables
const double pi = 3.14159265358979323846
const double twopi = 2*pi
const double degree = pi/180
Function Documentation
static double mathf::wall_clock () [static]
Definition at line 26 of file mathf.h.
T mathf::cube (T x)
Definition at line 33 of file mathf.h.
T mathf::square (T x)
Definition at line 34 of file mathf.h.
T mathf::mmin (T x, T y)
Definition at line 35 of file mathf.h.
Referenced by clamp().
T mathf::mmax (T x, T y)
Definition at line 36 of file mathf.h.
Referenced by clamp().
T mathf::clamp (T x, T a, T b)
Definition at line 37 of file mathf.h.
References mmax(), and mmin().
void mathf::swap (T & v1, T & v2)
Definition at line 38 of file mathf.h.
int mathf::sign (T x)
Definition at line 39 of file mathf.h.
double mathf::modpi (T x)
Definition at line 41 of file mathf.h.
References pi, and twopi.
double mathf::modPeriod (T x, double mPeriod)
Definition at line 42 of file mathf.h.
std::string mathf::itoa (T value, int base)
Definition at line 44 of file mathf.h.
static void mathf::getPathNameExt (std::string & fullname, std::string & path, std::string & name, std::string & ext) [static]
Definition at line 60 of file mathf.h.
Referenced by createOutputDir().
static int mathf::isDir (const char * path) [static]
Definition at line 85 of file mathf.h.
Referenced by createOutputDir(), createTempSubdir(), createUniqueFilename(), and createUniqueSubdir().
static std::string mathf::createTempSubdir (std::string & subdir) [static]
Definition at line 101 of file mathf.h.
References isDir().
static std::string mathf::createUniqueFilename (const std::string & name) [static]
Definition at line 141 of file mathf.h.
References isDir().
static std::string mathf::createUniqueSubdir (const std::string & path, const std::string & subdir) [static]
Definition at line 163 of file mathf.h.
References isDir().
static std::string mathf::createOutputDir (std::string & outputFile) [static]
Definition at line 190 of file mathf.h.
References getPathNameExt(), and isDir().
Variable Documentation
const double pi = 3.14159265358979323846
Definition at line 29 of file mathf.h.
Referenced by modpi().
const double twopi = 2*pi
Examples:
3dmeshtest.cpp, accuracytest.cpp, and cpp2for.cpp.
Definition at line 30 of file mathf.h.
Referenced by MCBPHI(), MCRHPOTENCIAL(), and modpi().
const double degree = pi/180
Definition at line 31 of file mathf.h.
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik