MConf: CStconfig::ctStack::saveState Struct Reference
CStconfig::ctStack::saveState Struct Reference
The internal class increments an index at given address, the destructor restores the index.
#include <CStconfig.h>
Public Member Functions
saveState (ctStack &ct)
~saveState ()
Public Attributes
ctStack * pct
Detailed Description
The internal class increments an index at given address, the destructor restores the index.
Definition at line 830 of file CStconfig.h.
Constructor & Destructor Documentation
saveState (ctStack & ct)
Definition at line 832 of file CStconfig.h.
References CStconfig::ctStack::idx, CStconfig::ctStack::saveState::pct, and CStconfig::ctStack::top().
~saveState ()
Definition at line 837 of file CStconfig.h.
References CStconfig::ctStack::idx, CStconfig::ctResults::invalidate(), CStconfig::ctStack::saveState::pct, and CStconfig::ctStack::top().
Member Data Documentation
ctStack* pct
Definition at line 831 of file CStconfig.h.
Referenced by CStconfig::ctStack::saveState::saveState(), and CStconfig::ctStack::saveState::~saveState().
The documentation for this struct was generated from the following file:
CStconfig.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik