MConf: CStconfig::ctStack Struct Reference
CStconfig::ctStack Struct Reference
[Internal stuff for Newton's method.]
The internal fast stack for ctResults.
#include <CStconfig.h>
Classes
struct saveState
The internal class increments an index at given address, the destructor restores the index.
Public Member Functions
ctStack ()
const ctResults & operator() () const
ctResults & operator() ()
ctResults & top ()
Public Attributes
size_t idx
ctResults a
Detailed Description
The internal fast stack for ctResults.
Definition at line 816 of file CStconfig.h.
Constructor & Destructor Documentation
ctStack ()
Definition at line 819 of file CStconfig.h.
References CStconfig::ctStack::idx.
Member Function Documentation
const ctResults& operator() () const
Definition at line 820 of file CStconfig.h.
References CStconfig::ctStack::idx.
ctResults& operator() ()
Definition at line 821 of file CStconfig.h.
References CStconfig::ctStack::top().
ctResults& top ()
Definition at line 822 of file CStconfig.h.
References CStconfig::ctStack::idx.
Referenced by CStconfig::ctStack::operator()(), CStconfig::ctStack::saveState::saveState(), and CStconfig::ctStack::saveState::~saveState().
Member Data Documentation
size_t idx
Definition at line 817 of file CStconfig.h.
Referenced by CStconfig::ctStack::ctStack(), CStconfig::ctStack::operator()(), CStconfig::ctStack::saveState::saveState(), CStconfig::ctStack::top(), and CStconfig::ctStack::saveState::~saveState().
ctResults a
Definition at line 818 of file CStconfig.h.
The documentation for this struct was generated from the following file:
CStconfig.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik