MConf: CStconfig::ctResults Struct Reference
CStconfig::ctResults Struct Reference
[Internal stuff for Newton's method.]
The internal structure holds things after last coordinate transformation/NJacobian calculation.
#include <CStconfig.h>
Public Member Functions
ctResults ()
void invalidate ()
bool isCoordValid ()
bool isBnormValid (double mBnorma)
bool isAxisValid (const Vector3d &cyl)
bool isCylValid (const Vector3d &cyl, double mBnorma)
bool isXyzValid (const Vector3d &xyz, double mBnorma)
double diffCyl2 (const Vector3d &c)
double diffXyz2 (const Vector3d &r)
void saveLastJacobian (double Bnorm)
Public Attributes
int is
double s
double modB
double jac
double jacMixProd
double jacVmec
double jacBoozer
double p
double ps
double pt
double pp
double lambda
double lambdas
double lambdat
double lambdap
double mBnormLast
Vector3d axisLast
Vector3d xyzLast
Vector3d cylLast
Vector3d magLast
Vector3d Jlast [5]
Vector3d Bxyz
Vector3d Bcyl
Vector3d Bcontra
Vector3d Bcova
Vector3d gradTheta
Vector3d gradPhi
Vector3d gradtorFlux
Vector3d gradS
Vector3d gradReff
Vector3d Jmatr [5]
Vector3d gsTensor [3]
Detailed Description
The internal structure holds things after last coordinate transformation/NJacobian calculation.
Definition at line 722 of file CStconfig.h.
Constructor & Destructor Documentation
ctResults ()
Definition at line 723 of file CStconfig.h.
References CStconfig::ctResults::axisLast, CStconfig::ctResults::cylLast, CStconfig::ctResults::is, CStconfig::ctResults::jac, CStconfig::ctResults::jacBoozer, CStconfig::ctResults::jacMixProd, CStconfig::ctResults::jacVmec, CStconfig::ctResults::lambda, CStconfig::ctResults::lambdap, CStconfig::ctResults::lambdas, CStconfig::ctResults::lambdat, CStconfig::ctResults::mBnormLast, CStconfig::ctResults::modB, CStconfig::ctResults::p, CStconfig::ctResults::pp, CStconfig::ctResults::ps, CStconfig::ctResults::pt, and CStconfig::ctResults::xyzLast.
Member Function Documentation
void invalidate ()
Definition at line 729 of file CStconfig.h.
References CStconfig::ctResults::axisLast, CStconfig::ctResults::cylLast, CStconfig::ctResults::mBnormLast, and CStconfig::ctResults::xyzLast.
Referenced by CStconfig::ctStack::saveState::~saveState().
bool isCoordValid ()
Definition at line 730 of file CStconfig.h.
References CStconfig::ctResults::cylLast.
Referenced by CStconfig::ctResults::isAxisValid(), CStconfig::ctResults::isCylValid(), and CStconfig::ctResults::isXyzValid().
bool isBnormValid (double mBnorma)
Definition at line 731 of file CStconfig.h.
References CStconfig::ctResults::mBnormLast.
Referenced by CStconfig::ctResults::isCylValid(), and CStconfig::ctResults::isXyzValid().
bool isAxisValid (const Vector3d & cyl)
Definition at line 732 of file CStconfig.h.
References CStconfig::ctResults::axisLast, and CStconfig::ctResults::isCoordValid().
bool isCylValid (const Vector3d & cyl, double mBnorma)
Definition at line 736 of file CStconfig.h.
References CStconfig::ctResults::cylLast, CStconfig::ctResults::isBnormValid(), and CStconfig::ctResults::isCoordValid().
bool isXyzValid (const Vector3d & xyz, double mBnorma)
Definition at line 742 of file CStconfig.h.
References CStconfig::ctResults::diffXyz2(), CStconfig::ctResults::isBnormValid(), and CStconfig::ctResults::isCoordValid().
double diffCyl2 (const Vector3d & c)
Definition at line 747 of file CStconfig.h.
References CStconfig::ctResults::cylLast, Vector3d::x(), Vector3d::y(), and Vector3d::z().
double diffXyz2 (const Vector3d & r)
Definition at line 758 of file CStconfig.h.
References CStconfig::ctResults::xyzLast.
Referenced by CStconfig::ctResults::isXyzValid().
void saveLastJacobian (double Bnorm)
Definition at line 761 of file CStconfig.h.
References CStconfig::ctResults::cylLast, CStconfig::ctResults::Jlast, CStconfig::ctResults::Jmatr, CStconfig::ctResults::magLast, CStconfig::ctResults::mBnormLast, Vector3d::toCartesian(), and CStconfig::ctResults::xyzLast.
Member Data Documentation
int is
Definition at line 772 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double s
Definition at line 773 of file CStconfig.h.
double modB
Definition at line 774 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double jac
Definition at line 775 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double jacMixProd
Definition at line 776 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double jacVmec
Definition at line 777 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double jacBoozer
Definition at line 778 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double p
Definition at line 779 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double ps
Definition at line 780 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double pt
Definition at line 781 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double pp
Definition at line 782 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double lambda
Definition at line 783 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double lambdas
Definition at line 784 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double lambdat
Definition at line 785 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double lambdap
Definition at line 786 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults().
double mBnormLast
Definition at line 787 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults(), CStconfig::ctResults::invalidate(), CStconfig::ctResults::isBnormValid(), and CStconfig::ctResults::saveLastJacobian().
Vector3d axisLast
Definition at line 788 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults(), CStconfig::ctResults::invalidate(), and CStconfig::ctResults::isAxisValid().
Vector3d xyzLast
Definition at line 789 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults(), CStconfig::ctResults::diffXyz2(), CStconfig::ctResults::invalidate(), and CStconfig::ctResults::saveLastJacobian().
Vector3d cylLast
Definition at line 790 of file CStconfig.h.
Referenced by CStconfig::ctResults::ctResults(), CStconfig::ctResults::diffCyl2(), CStconfig::ctResults::invalidate(), CStconfig::ctResults::isCoordValid(), CStconfig::ctResults::isCylValid(), and CStconfig::ctResults::saveLastJacobian().
Vector3d magLast
Definition at line 791 of file CStconfig.h.
Referenced by CStconfig::ctResults::saveLastJacobian().
Vector3d Jlast[5]
Definition at line 792 of file CStconfig.h.
Referenced by CStconfig::ctResults::saveLastJacobian().
Vector3d Bxyz
Definition at line 793 of file CStconfig.h.
Vector3d Bcyl
Definition at line 794 of file CStconfig.h.
Vector3d Bcontra
Definition at line 795 of file CStconfig.h.
Vector3d Bcova
Definition at line 796 of file CStconfig.h.
Vector3d gradTheta
Definition at line 797 of file CStconfig.h.
Vector3d gradPhi
Definition at line 798 of file CStconfig.h.
Vector3d gradtorFlux
Definition at line 799 of file CStconfig.h.
Vector3d gradS
Definition at line 800 of file CStconfig.h.
Vector3d gradReff
Definition at line 801 of file CStconfig.h.
Vector3d Jmatr[5]
Definition at line 803 of file CStconfig.h.
Referenced by CStconfig::ctResults::saveLastJacobian().
Vector3d gsTensor[3]
Definition at line 809 of file CStconfig.h.
The documentation for this struct was generated from the following file:
CStconfig.h
[ top ] [ back ]
13 Oct 2021 Max-Planck-Institut
für Plasmaphysik